import type { Row } from './expand'

/**
 * Другий ешелон: дієслова для розгорнутої розмови, робота й навчання,
 * спілкування, почуття, здоров’я.
 */
export const BAND_4: Row[] = [
  // --- дієслова ---
  ['w_appartenir_v', 'appartenir', 'належати', 'a.paʁ.tə.niʁ', 'v'],
  ['w_ajouter', 'ajouter', 'додавати', 'a.ʒu.te', 'v'],
  ['w_enlever', 'enlever', 'знімати, прибирати', 'ɑ̃l.ve', 'v'],
  ['w_remplir', 'remplir', 'заповнювати', 'ʁɑ̃.pliʁ', 'v'],
  ['w_vider', 'vider', 'спорожняти', 'vi.de', 'v'],
  ['w_ranger', 'ranger', 'прибирати, складати', 'ʁɑ̃.ʒe', 'v'],
  ['w_nettoyer', 'nettoyer', 'чистити, прибирати', 'nɛ.twa.je', 'v'],
  ['w_laver', 'laver', 'мити, прати', 'la.ve', 'v'],
  ['w_preparer', 'préparer', 'готувати (загалом)', 'pʁe.pa.ʁe', 'v'],
  ['w_cuisiner', 'cuisiner', 'готувати їжу', 'kɥi.zi.ne', 'v'],
  ['w_gouter', 'goûter', 'куштувати', 'ɡu.te', 'v'],
  ['w_reveiller', 'se réveiller', 'прокидатися', 'sə ʁe.vɛ.je', 'v'],
  ['w_coucher', 'se coucher', 'лягати спати', 'sə ku.ʃe', 'v'],
  ['w_habiller', "s'habiller", 'одягатися', 'sa.bi.je', 'v'],
  ['w_laver_se', 'se laver', 'митися', 'sə la.ve', 'v'],
  ['w_depecher', 'se dépêcher', 'поспішати', 'sə de.pɛ.ʃe', 'v'],
  ['w_reposer', 'se reposer', 'відпочивати', 'sə ʁə.po.ze', 'v'],
  ['w_promener', 'se promener', 'гуляти', 'sə pʁɔm.ne', 'v'],
  ['w_amuser', "s'amuser", 'розважатися', 'sa.my.ze', 'v'],
  ['w_ennuyer', "s'ennuyer", 'нудьгувати', 'sɑ̃.nɥi.je', 'v'],
  ['w_inquieter', "s'inquiéter", 'хвилюватися', 'sɛ̃.kje.te', 'v'],
  ['w_souvenir_v', 'se souvenir de', 'пам’ятати, згадувати', 'sə suv.niʁ də', 'v'],
  ['w_asseoir', "s'asseoir", 'сідати', 'sa.swaʁ', 'v'],
  ['w_lever_se', 'se lever', 'вставати', 'sə lə.ve', 'v'],
  ['w_tromper', 'se tromper', 'помилятися', 'sə tʁɔ̃.pe', 'v'],
  ['w_occuper', "s'occuper de", 'займатися чимось, дбати', 'sɔ.ky.pe də', 'v'],
  ['w_interesser', "s'intéresser à", 'цікавитися', 'sɛ̃.te.ʁɛ.se a', 'v'],
  ['w_habituer', "s'habituer à", 'звикати до', 'sa.bi.tɥe a', 'v'],
  ['w_marier', 'se marier', 'одружуватися', 'sə ma.ʁje', 'v'],
  ['w_appeler_se', "s'appeler", 'зватися', 'sa.p(ə)le', 'v'],
  ['w_esperer', 'espérer', 'сподіватися', 'ɛs.pe.ʁe', 'v'],
  ['w_souhaiter', 'souhaiter', 'бажати', 'swɛ.te', 'v'],
  ['w_preferer', 'préférer', 'віддавати перевагу', 'pʁe.fe.ʁe', 'v'],
  ['w_detester', 'détester', 'ненавидіти', 'de.tɛs.te', 'v'],
  ['w_adorer', 'adorer', 'обожнювати', 'a.dɔ.ʁe', 'v'],
  [
    'w_plaire',
    'plaire',
    'подобатися',
    'plɛʁ',
    'v',
    'Логіка зворотна до нашої: «Ça me plaît» — дослівно «це мені подобає».',
  ],
  [
    'w_manquer',
    'manquer',
    'бракувати; сумувати за',
    'mɑ̃.ke',
    'v',
    '⚠️ Перевертає підмет: «Tu me manques» — «Я сумую за тобою», дослівно «ти мені бракуєш».',
  ],
  ['w_suffire', 'suffire', 'бути достатнім', 'sy.fiʁ', 'v'],
  ['w_obtenir', 'obtenir', 'отримувати, здобувати', 'ɔp.tə.niʁ', 'v'],
  ['w_retrouver', 'retrouver', 'знаходити знову, зустрічатися', 'ʁə.tʁu.ve', 'v'],
  ['w_rejoindre', 'rejoindre', 'приєднуватися, наздоганяти', 'ʁə.ʒwɛ̃dʁ', 'v'],
  ['w_participer', 'participer', 'брати участь', 'paʁ.ti.si.pe', 'v'],
  ['w_organiser', 'organiser', 'організовувати', 'ɔʁ.ɡa.ni.ze', 'v'],
  ['w_diriger', 'diriger', 'керувати', 'di.ʁi.ʒe', 'v'],
  ['w_developper', 'développer', 'розвивати', 'dev.lɔ.pe', 'v'],
  ['w_ameliorer', 'améliorer', 'покращувати', 'a.me.ljɔ.ʁe', 'v'],
  ['w_augmenter', 'augmenter', 'збільшувати', 'oɡ.mɑ̃.te', 'v'],
  ['w_baisser', 'baisser', 'знижувати, опускати', 'bɛ.se', 'v'],
  ['w_calculer', 'calculer', 'обчислювати', 'kal.ky.le', 'v'],
  ['w_mesurer', 'mesurer', 'вимірювати', 'mə.zy.ʁe', 'v'],
  ['w_comparer', 'comparer', 'порівнювати', 'kɔ̃.pa.ʁe', 'v'],
  ['w_verifier', 'vérifier', 'перевіряти', 've.ʁi.fje', 'v'],
  ['w_corriger', 'corriger', 'виправляти', 'kɔ.ʁi.ʒe', 'v'],
  [
    'w_repeter',
    'répéter',
    'повторювати',
    'ʁe.pe.te',
    'v',
    'У розмові найкорисніше: «Vous pouvez répéter ?» — «Можете повторити?»',
  ],
  ['w_traduire', 'traduire', 'перекладати', 'tʁa.dɥiʁ', 'v'],
  ['w_signifier', 'signifier', 'означати', 'si.ɲi.fje', 'v'],
  ['w_telephoner', 'téléphoner', 'телефонувати', 'te.le.fɔ.ne', 'v'],
  ['w_discuter', 'discuter', 'обговорювати, розмовляти', 'dis.ky.te', 'v'],
  ['w_bavarder', 'bavarder', 'базікати', 'ba.vaʁ.de', 'v'],
  ['w_annoncer', 'annoncer', 'оголошувати', 'a.nɔ̃.se', 'v'],
  ['w_prevenir', 'prévenir', 'попереджати', 'pʁev.niʁ', 'v'],
  ['w_remercier', 'remercier', 'дякувати', 'ʁə.mɛʁ.sje', 'v'],
  ['w_excuser', "s'excuser", 'вибачатися', 'sɛks.ky.ze', 'v'],
  ['w_saluer', 'saluer', 'вітатися', 'sa.lɥe', 'v'],
  ['w_inviter', 'inviter', 'запрошувати', 'ɛ̃.vi.te', 'v'],
  ['w_recommander', 'recommander', 'радити, рекомендувати', 'ʁə.kɔ.mɑ̃.de', 'v'],
  ['w_conseiller', 'conseiller', 'радити', 'kɔ̃.sɛ.je', 'v'],
  ['w_promettre', 'promettre', 'обіцяти', 'pʁɔ.mɛtʁ', 'v'],
  ['w_mentir', 'mentir', 'брехати', 'mɑ̃.tiʁ', 'v'],
  ['w_reflechir', 'réfléchir', 'розмірковувати', 'ʁe.fle.ʃiʁ', 'v'],
  ['w_imaginer', 'imaginer', 'уявляти', 'i.ma.ʒi.ne', 'v'],
  ['w_rever', 'rêver', 'мріяти; бачити сон', 'ʁɛ.ve', 'v'],
  ['w_douter', 'douter', 'сумніватися', 'du.te', 'v'],
  ['w_craindre', 'craindre', 'боятися, побоюватися', 'kʁɛ̃dʁ', 'v'],
  ['w_risquer', 'risquer', 'ризикувати', 'ʁis.ke', 'v'],
  ['w_eviter', 'éviter', 'уникати', 'e.vi.te', 'v'],
  ['w_cacher', 'cacher', 'ховати', 'ka.ʃe', 'v'],
  ['w_decouvrir', 'découvrir', 'відкривати, виявляти', 'de.ku.vʁiʁ', 'v'],
  ['w_remplacer', 'remplacer', 'замінювати', 'ʁɑ̃.pla.se', 'v'],
  ['w_reparer', 'réparer', 'ремонтувати', 'ʁe.pa.ʁe', 'v'],
  ['w_dessiner', 'dessiner', 'малювати, креслити', 'de.si.ne', 'v'],
  ['w_peindre', 'peindre', 'фарбувати, малювати фарбами', 'pɛ̃dʁ', 'v'],
  ['w_conduire', 'conduire', 'керувати авто, вести', 'kɔ̃.dɥiʁ', 'v'],
  ['w_rouler', 'rouler', 'їхати (про транспорт)', 'ʁu.le', 'v'],
  [
    'w_voler',
    'voler',
    'літати; красти',
    'vɔ.le',
    'v',
    'Два значення в одному слові — розрізняє лише контекст.',
  ],
  ['w_nager', 'nager', 'плавати', 'na.ʒe', 'v'],
  ['w_sauter', 'sauter', 'стрибати', 'so.te', 'v'],
  ['w_frapper', 'frapper', 'бити; стукати', 'fʁa.pe', 'v'],
  ['w_battre', 'battre', 'бити; перемагати', 'batʁ', 'v'],
  ['w_defendre', 'défendre', 'захищати; забороняти', 'de.fɑ̃dʁ', 'v'],
  ['w_attaquer', 'attaquer', 'атакувати', 'a.ta.ke', 'v'],
  ['w_tuer', 'tuer', 'убивати', 'tɥe', 'v'],
  ['w_naitre', 'naître', 'народжуватися', 'nɛtʁ', 'v'],
  ['w_grandir', 'grandir', 'рости, дорослішати', 'ɡʁɑ̃.diʁ', 'v'],
  ['w_vieillir', 'vieillir', 'старіти', 'vjɛ.jiʁ', 'v'],
  ['w_soigner', 'soigner', 'лікувати, доглядати', 'swa.ɲe', 'v'],
  ['w_guerir', 'guérir', 'одужувати, зцілювати', 'ɡe.ʁiʁ', 'v'],
  ['w_souffrir', 'souffrir', 'страждати', 'su.fʁiʁ', 'v'],
  ['w_blesser', 'blesser', 'ранити', 'blɛ.se', 'v'],

  // --- робота й навчання ---
  ['w_entreprise', "l'entreprise", 'підприємство, компанія', 'lɑ̃.tʁə.pʁiz', 'nf'],
  ['w_societe', 'la société', 'компанія; суспільство', 'la sɔ.sje.te', 'nf'],
  ['w_emploi', "l'emploi", 'робота, посада', 'lɑ̃.plwa', 'nm'],
  ['w_metier', 'le métier', 'фах, професія', 'lə me.tje', 'nm'],
  ['w_salaire', 'le salaire', 'зарплата', 'lə sa.lɛʁ', 'nm'],
  ['w_reunion', 'la réunion', 'зустріч, нарада', 'la ʁe.y.njɔ̃', 'nf'],
  [
    'w_rendez_vous',
    'le rendez-vous',
    'зустріч, запис на прийом',
    'lə ʁɑ̃.de.vu',
    'nm',
    'Будь-яка призначена зустріч, не лише романтична: «rendez-vous chez le médecin».',
  ],
  ['w_document', 'le document', 'документ', 'lə dɔ.ky.mɑ̃', 'nm'],
  ['w_dossier', 'le dossier', 'справа, тека', 'lə dɔ.sje', 'nm'],
  ['w_contrat', 'le contrat', 'договір', 'lə kɔ̃.tʁa', 'nm'],
  ['w_experience', "l'expérience", 'досвід; дослід', 'lɛks.pe.ʁjɑ̃s', 'nf'],
  ['w_formation', 'la formation', 'навчання, підготовка', 'la fɔʁ.ma.sjɔ̃', 'nf'],
  ['w_etudes', 'les études', 'навчання (у виші)', 'le.z‿e.tyd', 'nf'],
  ['w_devoir_n', 'les devoirs', 'домашнє завдання', 'le də.vwaʁ', 'nm'],
  ['w_note', 'la note', 'оцінка; нотатка; рахунок', 'la nɔt', 'nf'],
  ['w_erreur', "l'erreur", 'помилка', 'lɛ.ʁœʁ', 'nf'],
  [
    'w_faute',
    'la faute',
    'помилка; провина',
    'la fot',
    'nf',
    '«C’est ma faute» — «Це моя провина».',
  ],
  ['w_exercice', "l'exercice", 'вправа', 'lɛɡ.zɛʁ.sis', 'nm'],
  ['w_regle', 'la règle', 'правило; лінійка', 'la ʁɛɡl', 'nf'],
  ['w_texte', 'le texte', 'текст', 'lə tɛkst', 'nm'],
  ['w_phrase', 'la phrase', 'речення, фраза', 'la fʁɑz', 'nf'],
  ['w_sens', 'le sens', 'значення; напрямок; відчуття', 'lə sɑ̃s', 'nm'],
  ['w_information', "l'information", 'інформація; новина', 'lɛ̃.fɔʁ.ma.sjɔ̃', 'nf'],
  ['w_nouvelle', 'la nouvelle', 'новина', 'la nu.vɛl', 'nf'],
  ['w_journal', 'le journal', 'газета; щоденник', 'lə ʒuʁ.nal', 'nm'],
  ['w_message', 'le message', 'повідомлення', 'lə me.saʒ', 'nm'],
  ['w_appel', "l'appel", 'дзвінок; заклик', 'la.pɛl', 'nm'],
  ['w_adresse', "l'adresse", 'адреса', 'la.dʁɛs', 'nf'],

  // --- почуття й стан ---
  ['w_sentiment', 'le sentiment', 'почуття', 'lə sɑ̃.ti.mɑ̃', 'nm'],
  ['w_joie', 'la joie', 'радість', 'la ʒwa', 'nf'],
  [
    'w_bonheur',
    'le bonheur',
    'щастя',
    'lə bɔ.nœʁ',
    'nm',
    '⚠️ Чоловічий рід, наше «щастя» — середній.',
  ],
  ['w_malheur', 'le malheur', 'нещастя, біда', 'lə ma.lœʁ', 'nm'],
  ['w_colere', 'la colère', 'гнів', 'la kɔ.lɛʁ', 'nf'],
  ['w_surprise', 'la surprise', 'несподіванка', 'la syʁ.pʁiz', 'nf'],
  ['w_espoir', "l'espoir", 'надія', 'lɛs.pwaʁ', 'nm', '⚠️ Чоловічий рід, наша «надія» — жіночий.'],
  [
    'w_courage',
    'le courage',
    'сміливість',
    'lə ku.ʁaʒ',
    'nm',
    '«Bon courage !» — побажання сил перед складним, дуже вживане.',
  ],
  [
    'w_chance',
    'la chance',
    'удача, щастя; шанс',
    'la ʃɑ̃s',
    'nf',
    '«Bonne chance !» — «Щасти!». «Avoir de la chance» — «щастити».',
  ],
  [
    'w_sante',
    'la santé',
    'здоров’я',
    'la sɑ̃.te',
    'nf',
    'Тост «À ta santé !» — «За твоє здоров’я!»',
  ],
  ['w_douleur', 'la douleur', 'біль', 'la du.lœʁ', 'nf', '⚠️ Жіночий рід, наш «біль» — чоловічий.'],
  ['w_maladie', 'la maladie', 'хвороба', 'la ma.la.di', 'nf'],
  [
    'w_medicament',
    'le médicament',
    'ліки',
    'lə me.di.ka.mɑ̃',
    'nm',
    'Однина, хоч наші «ліки» — множина.',
  ],
  ['w_fievre', 'la fièvre', 'температура, гарячка', 'la fjɛvʁ', 'nf'],
  ['w_sommeil', 'le sommeil', 'сон (стан)', 'lə sɔ.mɛj', 'nm'],
  ['w_reve', 'le rêve', 'мрія; сон', 'lə ʁɛv', 'nm'],
  ['w_repos', 'le repos', 'відпочинок', 'lə ʁə.po', 'nm'],
  ['w_effort', "l'effort", 'зусилля', 'le.fɔʁ', 'nm'],
  ['w_succes', 'le succès', 'успіх', 'lə syk.sɛ', 'nm'],
  ['w_echec', "l'échec", 'невдача; шахи (мн.)', 'le.ʃɛk', 'nm'],
  [
    'w_danger',
    'le danger',
    'небезпека',
    'lə dɑ̃.ʒe',
    'nm',
    '⚠️ Чоловічий рід, наша «небезпека» — жіночий.',
  ],
  ['w_securite', 'la sécurité', 'безпека', 'la se.ky.ʁi.te', 'nf'],
  ['w_aide', "l'aide", 'допомога', 'lɛd', 'nf'],
  ['w_conseil', 'le conseil', 'порада; рада (орган)', 'lə kɔ̃.sɛj', 'nm'],
  ['w_avis', "l'avis", 'думка, погляд', 'la.vi', 'nm', '«À mon avis» — «на мою думку».'],
  ['w_verite', 'la vérité', 'правда', 'la ve.ʁi.te', 'nf'],
  ['w_mensonge', 'le mensonge', 'брехня', 'lə mɑ̃.sɔ̃ʒ', 'nm'],
  ['w_secret', 'le secret', 'таємниця', 'lə sə.kʁɛ', 'nm'],
  ['w_souvenir_n', 'le souvenir', 'спогад; сувенір', 'lə suv.niʁ', 'nm'],
  ['w_habitude', "l'habitude", 'звичка', 'la.bi.tyd', 'nf', '«D’habitude» — «зазвичай».'],
  ['w_difference', 'la différence', 'різниця', 'la di.fe.ʁɑ̃s', 'nf'],
  ['w_qualite', 'la qualité', 'якість; чеснота', 'la ka.li.te', 'nf'],
  ['w_defaut', 'le défaut', 'недолік, вада', 'lə de.fo', 'nm'],
]
