import type { Row } from './expand'

/**
 * Завершення першої тисячі: суспільство, техніка, освіта, культура,
 * а також прикметники й звороти, без яких мова звучить «шкільною».
 */
export const BAND_5: Row[] = [
  // --- суспільство, держава ---
  ['w_gouvernement', 'le gouvernement', 'уряд', 'lə ɡu.vɛʁ.nə.mɑ̃', 'nm'],
  ['w_president', 'le président', 'президент', 'lə pʁe.zi.dɑ̃', 'nm'],
  ['w_loi', 'la loi', 'закон', 'la lwa', 'nf', '⚠️ Жіночий рід, наш «закон» — чоловічий.'],
  ['w_police', 'la police', 'поліція', 'la pɔ.lis', 'nf'],
  ['w_prison', 'la prison', 'в’язниця', 'la pʁi.zɔ̃', 'nf'],
  ['w_juge', 'le juge', 'суддя', 'lə ʒyʒ', 'nm'],
  ['w_crime', 'le crime', 'злочин', 'lə kʁim', 'nm'],
  ['w_impot', "l'impôt", 'податок', 'lɛ̃.po', 'nm'],
  ['w_citoyen', 'le citoyen', 'громадянин', 'lə si.twa.jɛ̃', 'nm'],
  ['w_population', 'la population', 'населення', 'la pɔ.py.la.sjɔ̃', 'nf'],
  ['w_liberte', 'la liberté', 'свобода', 'la li.bɛʁ.te', 'nf'],
  ['w_egalite', "l'égalité", 'рівність', 'le.ɡa.li.te', 'nf'],
  ['w_election', "l'élection", 'вибори', 'le.lɛk.sjɔ̃', 'nf'],
  ['w_parti', 'le parti', 'партія', 'lə paʁ.ti', 'nm'],
  ['w_armee', "l'armée", 'армія', 'laʁ.me', 'nf'],
  ['w_frontiere', 'la frontière', 'кордон', 'la fʁɔ̃.tjɛʁ', 'nf'],
  ['w_capitale', 'la capitale', 'столиця', 'la ka.pi.tal', 'nf'],
  ['w_village', 'le village', 'село', 'lə vi.laʒ', 'nm'],
  ['w_habitant', "l'habitant", 'мешканець', 'la.bi.tɑ̃', 'nm'],
  ['w_couple', 'le couple', 'пара', 'lə kupl', 'nm'],
  ['w_mariage', 'le mariage', 'шлюб, весілля', 'lə ma.ʁjaʒ', 'nm'],
  ['w_naissance', 'la naissance', 'народження', 'la nɛ.sɑ̃s', 'nf'],
  ['w_mort', 'la mort', 'смерть', 'la mɔʁ', 'nf'],
  ['w_anniversaire', "l'anniversaire", 'день народження; річниця', 'la.ni.vɛʁ.sɛʁ', 'nm'],

  // --- гроші й покупки ---
  ['w_boutique', 'la boutique', 'крамниця', 'la bu.tik', 'nf'],
  ['w_caisse', 'la caisse', 'каса', 'la kɛs', 'nf'],
  [
    'w_monnaie',
    'la monnaie',
    'решта; валюта',
    'la mɔ.nɛ',
    'nf',
    '«Gardez la monnaie» — «залиште решту».',
  ],
  ['w_carte_bancaire', 'la carte bancaire', 'банківська картка', 'la kaʁt bɑ̃.kɛʁ', 'nf'],
  ['w_compte', 'le compte', 'рахунок (банківський)', 'lə kɔ̃t', 'nm'],
  ['w_facture', 'la facture', 'рахунок (до сплати)', 'la fak.tyʁ', 'nf'],
  ['w_reduction', 'la réduction', 'знижка', 'la ʁe.dyk.sjɔ̃', 'nf'],
  ['w_soldes', 'les soldes', 'розпродаж', 'le sɔld', 'nm'],
  ['w_gratuit', 'gratuit / gratuite', 'безкоштовний', 'ɡʁa.tɥi / ɡʁa.tɥit', 'adj'],
  ['w_depense', 'la dépense', 'витрата', 'la de.pɑ̃s', 'nf'],
  ['w_economie', "l'économie", 'економіка; заощадження', 'le.kɔ.nɔ.mi', 'nf'],
  ['w_commerce', 'le commerce', 'торгівля', 'lə kɔ.mɛʁs', 'nm'],
  ['w_produit', 'le produit', 'продукт, товар', 'lə pʁɔ.dɥi', 'nm'],
  ['w_quantite', 'la quantité', 'кількість', 'la kɑ̃.ti.te', 'nf'],

  // --- техніка ---
  [
    'w_internet',
    'Internet',
    'інтернет',
    'ɛ̃.tɛʁ.nɛt',
    'nm',
    'Уживається без артикля: «sur Internet».',
  ],
  ['w_site', 'le site', 'сайт', 'lə sit', 'nm'],
  ['w_reseau', 'le réseau', 'мережа', 'lə ʁe.zo', 'nm'],
  ['w_fichier', 'le fichier', 'файл', 'lə fi.ʃje', 'nm'],
  ['w_logiciel', 'le logiciel', 'програмне забезпечення', 'lə lɔ.ʒi.sjɛl', 'nm'],
  ['w_clavier', 'le clavier', 'клавіатура', 'lə kla.vje', 'nm'],
  ['w_souris', 'la souris', 'миша (і тварина, і комп’ютерна)', 'la su.ʁi', 'nf'],
  ['w_mot_de_passe', 'le mot de passe', 'пароль', 'lə mo də pɑs', 'nm'],
  ['w_courriel', "l'e-mail", 'електронна пошта', 'le.mɛl', 'nm'],
  ['w_lien', 'le lien', 'посилання; зв’язок', 'lə ljɛ̃', 'nm'],
  ['w_technologie', 'la technologie', 'технологія', 'la tɛk.nɔ.lɔ.ʒi', 'nf'],
  ['w_electricite', "l'électricité", 'електрика', 'le.lɛk.tʁi.si.te', 'nf'],
  ['w_energie', "l'énergie", 'енергія', 'le.nɛʁ.ʒi', 'nf'],
  ['w_moteur', 'le moteur', 'двигун', 'lə mɔ.tœʁ', 'nm'],
  ['w_outil', "l'outil", 'інструмент', 'lu.ti', 'nm', 'Кінцеве l не читається: [уті].'],

  // --- наука й освіта ---
  ['w_science', 'la science', 'наука', 'la sjɑ̃s', 'nf'],
  ['w_recherche', 'la recherche', 'дослідження; пошук', 'la ʁə.ʃɛʁʃ', 'nf'],
  ['w_etude', "l'étude", 'дослідження, вивчення', 'le.tyd', 'nf'],
  ['w_theorie', 'la théorie', 'теорія', 'la te.ɔ.ʁi', 'nf'],
  [
    'w_mathematiques',
    'les mathématiques',
    'математика',
    'le ma.te.ma.tik',
    'nf',
    'Множина, хоч наша «математика» — однина. Скорочено: «les maths».',
  ],
  ['w_medecine', 'la médecine', 'медицина', 'la med.sin', 'nf'],
  ['w_nature', 'la nature', 'природа', 'la na.tyʁ', 'nf'],
  ['w_environnement', "l'environnement", 'довкілля', 'lɑ̃.vi.ʁɔn.mɑ̃', 'nm'],
  ['w_espace', "l'espace", 'простір; космос', 'lɛs.pas', 'nm'],
  ['w_matiere', 'la matière', 'матерія; предмет (шкільний)', 'la ma.tjɛʁ', 'nf'],
  ['w_preuve', 'la preuve', 'доказ', 'la pʁœv', 'nf'],
  [
    'w_cause',
    'la cause',
    'причина',
    'la koz',
    'nf',
    '«À cause de» — «через» (щось погане), «grâce à» — «завдяки» (чомусь доброму).',
  ],
  ['w_consequence', 'la conséquence', 'наслідок', 'la kɔ̃.se.kɑ̃s', 'nf'],
  ['w_but', 'le but', 'мета; гол', 'lə byt', 'nm', '⚠️ Чоловічий рід, а наша «мета» — жіночий.'],
  ['w_moyen', 'le moyen', 'засіб, спосіб', 'lə mwa.jɛ̃', 'nm'],
  ['w_condition', 'la condition', 'умова', 'la kɔ̃.di.sjɔ̃', 'nf'],
  ['w_situation', 'la situation', 'ситуація, становище', 'la si.tɥa.sjɔ̃', 'nf'],
  ['w_question_n', 'la question', 'питання', 'la kɛs.tjɔ̃', 'nf'],
  ['w_sujet', 'le sujet', 'тема; підмет', 'lə sy.ʒɛ', 'nm', '«Au sujet de» — «стосовно».'],
  ['w_titre', 'le titre', 'заголовок; титул', 'lə titʁ', 'nm'],

  // --- культура ---
  ['w_art', "l'art", 'мистецтво', 'laʁ', 'nm'],
  ['w_artiste', "l'artiste", 'митець, артист', 'laʁ.tist', 'nmf'],
  ['w_tableau', 'le tableau', 'картина; дошка', 'lə ta.blo', 'nm'],
  [
    'w_roman',
    'le roman',
    'роман (книга)',
    'lə ʁɔ.mɑ̃',
    'nm',
    '⚠️ Хибний друг: це книжка, а не чоловіче ім’я і не «романтика».',
  ],
  ['w_auteur', "l'auteur", 'автор', 'lo.tœʁ', 'nm'],
  ['w_ecrivain', "l'écrivain", 'письменник', 'le.kʁi.vɛ̃', 'nm'],
  ['w_poeme', 'le poème', 'вірш', 'lə pɔ.ɛm', 'nm'],
  ['w_scene', 'la scène', 'сцена', 'la sɛn', 'nf'],
  ['w_acteur', "l'acteur / l'actrice", 'актор / акторка', 'lak.tœʁ / lak.tʁis', 'nm'],
  ['w_spectacle', 'le spectacle', 'вистава, шоу', 'lə spɛk.takl', 'nm'],
  ['w_concert', 'le concert', 'концерт', 'lə kɔ̃.sɛʁ', 'nm'],
  ['w_danse', 'la danse', 'танець', 'la dɑ̃s', 'nf', '⚠️ Жіночий рід, наш «танець» — чоловічий.'],
  ['w_instrument', "l'instrument", 'інструмент (музичний)', 'lɛ̃s.tʁy.mɑ̃', 'nm'],
  ['w_culture', 'la culture', 'культура', 'la kyl.tyʁ', 'nf'],
  ['w_tradition', 'la tradition', 'традиція', 'la tʁa.di.sjɔ̃', 'nf'],
  ['w_religion', 'la religion', 'релігія', 'la ʁə.li.ʒjɔ̃', 'nf'],
  ['w_dieu', 'Dieu', 'Бог', 'djø', 'nm', '«Mon Dieu !» — вигук здивування, як наше «Боже мій!».'],

  // --- прикметники ---
  [
    'w_ancien',
    'ancien / ancienne',
    'давній; колишній',
    'ɑ̃.sjɛ̃ / ɑ̃.sjɛn',
    'adj',
    'Перед іменником — «колишній» (mon ancien travail), після — «старовинний».',
  ],
  ['w_moderne', 'moderne', 'сучасний', 'mɔ.dɛʁn', 'adj'],
  [
    'w_actuel',
    'actuel / actuelle',
    'нинішній, теперішній',
    'ak.tɥɛl',
    'adj',
    '⚠️ Хибний друг: означає «теперішній», а не «актуальний».',
  ],
  ['w_normal', 'normal / normale', 'звичайний, нормальний', 'nɔʁ.mal', 'adj'],
  ['w_special', 'spécial / spéciale', 'особливий', 'spe.sjal', 'adj'],
  ['w_principal', 'principal / principale', 'головний', 'pʁɛ̃.si.pal', 'adj'],
  ['w_necessaire', 'nécessaire', 'необхідний', 'ne.se.sɛʁ', 'adj'],
  ['w_utile', 'utile', 'корисний', 'y.til', 'adj'],
  ['w_inutile', 'inutile', 'марний, непотрібний', 'i.ny.til', 'adj'],
  ['w_interessant', 'intéressant / intéressante', 'цікавий', 'ɛ̃.te.ʁɛ.sɑ̃', 'adj'],
  ['w_ennuyeux', 'ennuyeux / ennuyeuse', 'нудний', 'ɑ̃.nɥi.jø / ɑ̃.nɥi.jøz', 'adj'],
  ['w_amusant', 'amusant / amusante', 'кумедний, веселий', 'a.my.zɑ̃', 'adj'],
  ['w_drole', 'drôle', 'смішний; дивний', 'dʁol', 'adj'],
  ['w_serieux', 'sérieux / sérieuse', 'серйозний', 'se.ʁjø / se.ʁjøz', 'adj'],
  ['w_celebre', 'célèbre', 'відомий, знаменитий', 'se.lɛbʁ', 'adj'],
  ['w_connu', 'connu / connue', 'відомий', 'kɔ.ny', 'adj'],
  ['w_etrange', 'étrange', 'дивний', 'e.tʁɑ̃ʒ', 'adj'],
  [
    'w_etranger',
    'étranger / étrangère',
    'іноземний; іноземець',
    'e.tʁɑ̃.ʒe / e.tʁɑ̃.ʒɛʁ',
    'adj',
    '«À l’étranger» — «за кордоном».',
  ],
  ['w_prive', 'privé / privée', 'приватний', 'pʁi.ve', 'adj'],
  ['w_ouvert', 'ouvert / ouverte', 'відкритий, відчинений', 'u.vɛʁ / u.vɛʁt', 'adj'],
  ['w_ferme_adj', 'fermé / fermée', 'зачинений', 'fɛʁ.me', 'adj'],
  [
    'w_lourd',
    'lourd / lourde',
    'важкий (за вагою)',
    'luʁ / luʁd',
    'adj',
    'Вага — lourd, складність — difficile. Наше «важкий» покриває обидва.',
  ],
  ['w_leger', 'léger / légère', 'легкий (за вагою)', 'le.ʒe / le.ʒɛʁ', 'adj'],
  ['w_dur', 'dur / dure', 'твердий; важкий', 'dyʁ', 'adj'],
  ['w_doux', 'doux / douce', 'м’який, ніжний; солодкий', 'du / dus', 'adj'],
  ['w_epais', 'épais / épaisse', 'товстий (про річ)', 'e.pɛ / e.pɛs', 'adj'],
  ['w_mince', 'mince', 'тонкий, худий', 'mɛ̃s', 'adj'],
  ['w_profond', 'profond / profonde', 'глибокий', 'pʁɔ.fɔ̃ / pʁɔ.fɔ̃d', 'adj'],
  ['w_rapide', 'rapide', 'швидкий', 'ʁa.pid', 'adj'],
  ['w_lent', 'lent / lente', 'повільний', 'lɑ̃ / lɑ̃t', 'adj'],
  ['w_proche', 'proche', 'близький', 'pʁɔʃ', 'adj'],
  ['w_loin', 'loin', 'далеко', 'lwɛ̃', 'adv'],
  ['w_haut_adj', 'haut / haute', 'високий', 'o / ot', 'adj'],
  ['w_bas_adj', 'bas / basse', 'низький', 'bɑ / bɑs', 'adj'],
  ['w_joli', 'joli / jolie', 'гарненький, миловидний', 'ʒɔ.li', 'adj'],
  ['w_laid', 'laid / laide', 'потворний', 'lɛ / lɛd', 'adj'],
  ['w_excellent', 'excellent / excellente', 'чудовий, відмінний', 'ɛk.se.lɑ̃', 'adj'],
  ['w_parfait', 'parfait / parfaite', 'ідеальний', 'paʁ.fɛ / paʁ.fɛt', 'adj'],
  ['w_terrible', 'terrible', 'жахливий; (розм.) неймовірний', 'tɛ.ʁibl', 'adj'],
  ['w_horrible', 'horrible', 'жахливий', 'ɔ.ʁibl', 'adj'],
  [
    'w_grave',
    'grave',
    'серйозний, тяжкий',
    'ɡʁav',
    'adj',
    '«C’est pas grave» — «Нічого страшного», чуєш щодня.',
  ],
  ['w_sur_adj', 'sûr / sûre', 'упевнений; безпечний', 'syʁ', 'adj', '«Bien sûr» — «звісно».'],
  ['w_capable', 'capable', 'здатний', 'ka.pabl', 'adj'],
  ['w_responsable', 'responsable', 'відповідальний', 'ʁɛs.pɔ̃.sabl', 'adj'],
  ['w_riche', 'riche', 'багатий', 'ʁiʃ', 'adj'],
  ['w_pauvre', 'pauvre', 'бідний; бідолашний', 'povʁ', 'adj'],
  ['w_nombreux', 'nombreux / nombreuse', 'численний', 'nɔ̃.bʁø / nɔ̃.bʁøz', 'adj'],
  ['w_entier', 'entier / entière', 'цілий', 'ɑ̃.tje / ɑ̃.tjɛʁ', 'adj'],
  ['w_complet', 'complet / complète', 'повний, укомплектований', 'kɔ̃.plɛ / kɔ̃.plɛt', 'adj'],
  ['w_frais', 'frais / fraîche', 'свіжий; прохолодний', 'fʁɛ / fʁɛʃ', 'adj'],
  ['w_sec', 'sec / sèche', 'сухий', 'sɛk / sɛʃ', 'adj'],
  ['w_mouille', 'mouillé / mouillée', 'мокрий', 'mu.je', 'adj'],
  ['w_sucre', 'sucré / sucrée', 'солодкий', 'sy.kʁe', 'adj'],
  ['w_sale_gout', 'salé / salée', 'солоний', 'sa.le', 'adj'],
  ['w_amer', 'amer / amère', 'гіркий', 'a.mɛʁ', 'adj'],

  // --- прислівники та звороти ---
  ['w_actuellement', 'actuellement', 'нині, зараз', 'ak.tɥɛl.mɑ̃', 'adv'],
  ['w_bientot', 'bientôt', 'скоро', 'bjɛ̃.to', 'adv'],
  ['w_tot', 'tôt', 'рано', 'to', 'adv'],
  ['w_tard', 'tard', 'пізно', 'taʁ', 'adv'],
  ['w_vite', 'vite', 'швидко', 'vit', 'adv'],
  ['w_lentement', 'lentement', 'повільно', 'lɑ̃t.mɑ̃', 'adv'],
  ['w_ensemble', 'ensemble', 'разом', 'ɑ̃.sɑ̃bl', 'adv'],
  ['w_seulement', 'seulement', 'лише, тільки', 'sœl.mɑ̃', 'adv'],
  ['w_environ', 'environ', 'приблизно', 'ɑ̃.vi.ʁɔ̃', 'adv'],
  ['w_exactement', 'exactement', 'точно', 'ɛɡ.zak.tə.mɑ̃', 'adv'],
  ['w_absolument', 'absolument', 'абсолютно', 'ap.sɔ.ly.mɑ̃', 'adv'],
  ['w_probablement', 'probablement', 'імовірно', 'pʁɔ.ba.blə.mɑ̃', 'adv'],
  ['w_heureusement', 'heureusement', 'на щастя', 'ø.ʁøz.mɑ̃', 'adv'],
  ['w_malheureusement', 'malheureusement', 'на жаль', 'ma.lø.ʁøz.mɑ̃', 'adv'],
  [
    'w_evidemment',
    'évidemment',
    'очевидно, звісно',
    'e.vi.da.mɑ̃',
    'adv',
    'Пишеться -emment, а читається [-амон].',
  ],
  ['w_naturellement', 'naturellement', 'природно, звісно', 'na.ty.ʁɛl.mɑ̃', 'adv'],
  ['w_facilement', 'facilement', 'легко', 'fa.sil.mɑ̃', 'adv'],
  ['w_directement', 'directement', 'напряму', 'di.ʁɛk.tə.mɑ̃', 'adv'],
  ['w_immediatement', 'immédiatement', 'негайно', 'i.me.dja.tə.mɑ̃', 'adv'],
  ['w_finalement', 'finalement', 'зрештою, врешті', 'fi.nal.mɑ̃', 'adv'],
  ['w_dabord', "d'abord", 'спочатку', 'da.bɔʁ', 'adv'],
  ['w_plutot', 'plutôt', 'радше, скоріше', 'ply.to', 'adv'],
  [
    'w_davantage',
    'davantage',
    'більше',
    'da.vɑ̃.taʒ',
    'adv',
    'Стоїть сам, без порівняння: «Il travaille davantage». Якщо далі йде «ніж» — потрібне plus… que.',
  ],
  [
    'w_quand_meme',
    'quand même',
    'усе одно, все ж таки',
    'kɑ̃ mɛm',
    'adv',
    'Дуже вживаний зворот, який українці рідко освоюють — а без нього мова звучить сухо.',
  ],
  ['w_bien_sur', 'bien sûr', 'звісно', 'bjɛ̃ syʁ', 'adv'],
  [
    'w_daccord',
    "d'accord",
    'згоден, домовились',
    'da.kɔʁ',
    'adv',
    '«Être d’accord» — «погоджуватися».',
  ],
  ['w_par_exemple', 'par exemple', 'наприклад', 'paʁ ɛɡ.zɑ̃pl', 'adv'],
  ['w_cest_a_dire', "c'est-à-dire", 'тобто', 'sɛ.ta.diʁ', 'adv'],
  ['w_en_effet', 'en effet', 'справді, дійсно', 'ɑ̃.n‿e.fɛ', 'adv'],
  ['w_par_contre', 'par contre', 'натомість, зате', 'paʁ kɔ̃tʁ', 'adv'],
  ['w_au_contraire', 'au contraire', 'навпаки', 'o kɔ̃.tʁɛʁ', 'adv'],
  ['w_en_general', 'en général', 'загалом', 'ɑ̃ ʒe.ne.ʁal', 'adv'],
  ['w_tout_de_suite', 'tout de suite', 'негайно, зараз же', 'tut sɥit', 'adv'],
  ['w_tout_a_coup', 'tout à coup', 'раптом', 'tu.t‿a ku', 'adv'],
  [
    'w_soudain',
    'soudain',
    'раптом, зненацька',
    'su.dɛ̃',
    'adv',
    'Маркер passé composé: після нього майже завжди йде подія, а не тло.',
  ],
  ['w_de_plus_en_plus', 'de plus en plus', 'дедалі більше', 'də ply.z‿ɑ̃ ply', 'adv'],
  ['w_au_moins', 'au moins', 'принаймні', 'o mwɛ̃', 'adv'],
  ['w_a_peu_pres', 'à peu près', 'приблизно', 'a pø pʁɛ', 'adv'],
  ['w_de_nouveau', 'de nouveau', 'знову', 'də nu.vo', 'adv'],
  ['w_par_hasard', 'par hasard', 'випадково', 'paʁ a.zaʁ', 'adv'],
  ['w_expres', 'exprès', 'навмисне', 'ɛks.pʁɛ', 'adv'],
  ['w_dailleurs', 'd’ailleurs', 'до речі, зрештою', 'da.jœʁ', 'adv'],

  // --- корисні фрази ---
  [
    'w_je_sais_pas',
    'Je ne sais pas.',
    'Я не знаю.',
    'ʒə nə sɛ pɑ',
    'phrase',
    'У розмові ne зникає: «J’sais pas» [шсе па].',
  ],
  [
    'w_comment_dit_on',
    'Comment dit-on… ?',
    'Як сказати…?',
    'kɔ.mɑ̃ di.t‿ɔ̃',
    'phrase',
    'Найкорисніша фраза для учня: «Comment dit-on “стіл” en français ?»',
  ],
  ['w_quest_ce_que_cest', "Qu'est-ce que c'est ?", 'Що це?', 'kɛs kə sɛ', 'phrase'],
  ['w_je_comprends_pas', 'Je ne comprends pas.', 'Я не розумію.', 'ʒə nə kɔ̃.pʁɑ̃ pɑ', 'phrase'],
  [
    'w_plus_lentement',
    'Plus lentement, s’il vous plaît.',
    'Повільніше, будь ласка.',
    'ply lɑ̃t.mɑ̃',
    'phrase',
  ],
  ['w_ca_depend', 'Ça dépend.', 'Залежить.', 'sa de.pɑ̃', 'phrase'],
  ['w_ca_marche', 'Ça marche.', 'Домовились; працює.', 'sa maʁʃ', 'phrase'],
  [
    'w_il_y_a2',
    'il y a',
    'є; тому назад (про час)',
    'i.lja',
    'phrase',
    'Ще й «тому»: «il y a deux ans» — «два роки тому».',
  ],
  ['w_ca_va_aller', 'Ça va aller.', 'Все буде добре.', 'sa va a.le', 'phrase'],
  ['w_je_voudrais2', 'Je voudrais…', 'Я хотів би…', 'ʒə vu.dʁɛ', 'phrase'],
  ['w_sil_te_plait', "s'il te plaît", 'будь ласка (до друга)', 'sil tə plɛ', 'phrase'],
  [
    'w_je_vous_en_prie',
    'Je vous en prie.',
    'Прошу; нема за що.',
    'ʒə vu.z‿ɑ̃ pʁi',
    'phrase',
    'Ввічливіше за «de rien».',
  ],
  ['w_bonne_journee', 'Bonne journée !', 'Гарного дня!', 'bɔn ʒuʁ.ne', 'phrase'],
  ['w_a_tout_a_lheure', 'À tout à l’heure !', 'До скорого! (сьогодні)', 'a tu.t‿a lœʁ', 'phrase'],
  ['w_felicitations', 'Félicitations !', 'Вітаю!', 'fe.li.si.ta.sjɔ̃', 'phrase'],
  ['w_bon_appetit', 'Bon appétit !', 'Смачного!', 'bɔ.n‿a.pe.ti', 'phrase'],
  ['w_sante_toast', 'Santé !', 'Будьмо!', 'sɑ̃.te', 'phrase'],
  ['w_attention', 'Attention !', 'Обережно! Увага!', 'a.tɑ̃.sjɔ̃', 'phrase'],
  ['w_au_secours', 'Au secours !', 'Рятуйте!', 'o sə.kuʁ', 'phrase'],
  ['w_ca_suffit', 'Ça suffit !', 'Досить!', 'sa sy.fi', 'phrase'],
  ['w_tant_pis', 'Tant pis.', 'Ну й нехай; шкода.', 'tɑ̃ pi', 'phrase'],
  ['w_tant_mieux', 'Tant mieux.', 'Тим краще.', 'tɑ̃ mjø', 'phrase'],
  ['w_n_importe_quoi', "n'importe quoi", 'будь-що; дурниці', 'nɛ̃.pɔʁt kwa', 'phrase'],
  ['w_a_mon_avis', 'à mon avis', 'на мою думку', 'a mɔ̃.n‿a.vi', 'phrase'],
  ['w_par_ici', 'par ici', 'сюди, тут поруч', 'paʁ i.si', 'phrase'],
]
