import type { Row } from './expand'

/**
 * Наступні ~200 — найчастіші іменники та прикметники.
 *
 * Тут починається справжня лексика: люди, час, місце, тіло, базові оцінки.
 * Рід подано разом зі словом, бо інакше його не вивчити.
 */
export const BAND_2: Row[] = [
  // --- люди ---
  [
    'w_homme',
    "l'homme",
    'чоловік; людина',
    'lɔm',
    'nm',
    'H не читається зовсім: [лём]. Означає і «чоловік», і «людина» взагалі.',
  ],
  [
    'w_gens',
    'les gens',
    'люди',
    'le ʒɑ̃',
    'n',
    'Тільки множина — однини не буває. Одна людина — «une personne».',
  ],
  [
    'w_personne',
    'la personne',
    'особа, людина; ніхто',
    'la pɛʁ.sɔn',
    'nf',
    'Жіночого роду навіть про чоловіка. А з ne означає «ніхто»: «Personne ne vient».',
  ],
  ['w_monsieur2', 'le monsieur', 'пан, чоловік', 'lə mə.sjø', 'nm'],
  [
    'w_gars',
    'le gars',
    'хлопець, чувак',
    'lə ɡɑ',
    'nm',
    'Розмовне. Читається [ґа] — ні r, ні s не звучать.',
  ],
  ['w_type', 'le type', 'тип, хлопець (розм.)', 'lə tip', 'nm'],
  ['w_copain', 'le copain / la copine', 'друг / подруга; хлопець / дівчина', 'lə kɔ.pɛ̃', 'nm'],
  ['w_voisin', 'le voisin / la voisine', 'сусід / сусідка', 'lə vwa.zɛ̃', 'nm'],
  ['w_collegue', 'le collègue', 'колега', 'lə kɔ.lɛɡ', 'nm'],
  ['w_patron', 'le patron', 'начальник, шеф', 'lə pa.tʁɔ̃', 'nm'],
  ['w_client', 'le client', 'клієнт, покупець', 'lə kli.jɑ̃', 'nm'],
  ['w_equipe', "l'équipe", 'команда', 'le.kip', 'nf'],
  [
    'w_groupe',
    'le groupe',
    'група',
    'lə ɡʁup',
    'nm',
    '⚠️ Чоловічий рід, а наша «група» — жіночий.',
  ],
  [
    'w_bebe',
    'le bébé',
    'немовля',
    'lə be.be',
    'nm',
    'Завжди чоловічого роду, навіть про дівчинку.',
  ],
  ['w_garcon', 'le garçon', 'хлопчик', 'lə ɡaʁ.sɔ̃', 'nm'],
  ['w_dame', 'la dame', 'пані, жінка', 'la dam', 'nf'],

  // --- час ---
  [
    'w_temps',
    'le temps',
    'час; погода',
    'lə tɑ̃',
    'nm',
    'Два значення в одному слові: «Je n’ai pas le temps» — нема часу; «Quel temps fait-il ?» — яка погода.',
  ],
  [
    'w_an',
    "l'an",
    'рік',
    'lɑ̃',
    'nm',
    'an — для рахунку («deux ans»), année — для тривалості («une bonne année»).',
  ],
  ['w_moment', 'le moment', 'мить, момент', 'lə mɔ.mɑ̃', 'nm'],
  [
    'w_fois',
    'la fois',
    'раз',
    'la fwa',
    'nf',
    'Не плутай з temps: «trois FOIS» — тричі, а не «trois temps».',
  ],
  ['w_matin2', 'le matin', 'ранок', 'lə ma.tɛ̃', 'nm'],
  ['w_nuit', 'la nuit', 'ніч', 'la nɥi', 'nf'],
  ['w_midi', 'midi', 'полудень, обід', 'mi.di', 'nm'],
  ['w_minuit', 'minuit', 'опівніч', 'mi.nɥi', 'nm'],
  ['w_siecle', 'le siècle', 'століття', 'lə sjɛkl', 'nm'],
  ['w_date', 'la date', 'дата', 'la dat', 'nf'],
  ['w_weekend', 'le week-end', 'вихідні', 'lə wi.kɛnd', 'nm'],
  [
    'w_vacances',
    'les vacances',
    'відпустка, канікули',
    'le va.kɑ̃s',
    'nf',
    'Завжди у множині й жіночого роду.',
  ],
  ['w_avenir', "l'avenir", 'майбутнє', 'lav.niʁ', 'nm'],
  ['w_passe_n', 'le passé', 'минуле', 'lə pɑ.se', 'nm'],
  ['w_debut', 'le début', 'початок', 'lə de.by', 'nm'],
  ['w_fin', 'la fin', 'кінець', 'la fɛ̃', 'nf', '⚠️ Жіночий рід, а наш «кінець» — чоловічий.'],
  [
    'w_heure2',
    "l'heure",
    'година; час',
    'lœʁ',
    'nf',
    'H німа, тому l’heure. «À l’heure» — вчасно.',
  ],

  // --- місце й простір ---
  ['w_lieu', 'le lieu', 'місце', 'lə ljø', 'nm'],
  ['w_endroit', "l'endroit", 'місце, місцина', 'lɑ̃.dʁwa', 'nm'],
  ['w_cote', 'le côté', 'бік, сторона', 'lə ko.te', 'nm'],
  ['w_part', 'la part', 'частина, частка', 'la paʁ', 'nf'],
  ['w_partie', 'la partie', 'частина; партія (гри)', 'la paʁ.ti', 'nf'],
  ['w_bout', 'le bout', 'кінчик, шматок', 'lə bu', 'nm'],
  ['w_milieu', 'le milieu', 'середина; середовище', 'lə mi.ljø', 'nm'],
  ['w_haut', 'le haut', 'верх; високий', 'lə o', 'nm'],
  ['w_bas', 'le bas', 'низ; низький', 'lə bɑ', 'nm'],
  ['w_route', 'la route', 'дорога, шлях', 'la ʁut', 'nf'],
  ['w_chemin', 'le chemin', 'стежка, шлях', 'lə ʃə.mɛ̃', 'nm'],
  ['w_pont', 'le pont', 'міст', 'lə pɔ̃', 'nm'],
  ['w_batiment', 'le bâtiment', 'будівля', 'lə bɑ.ti.mɑ̃', 'nm'],
  ['w_immeuble', "l'immeuble", 'багатоквартирний будинок', 'li.mœbl', 'nm'],
  [
    'w_etage',
    "l'étage",
    'поверх',
    'le.taʒ',
    'nm',
    'Французький «rez-de-chaussée» — це наш перший поверх, а «premier étage» — вже другий.',
  ],
  ['w_bureau', 'le bureau', 'офіс; письмовий стіл', 'lə by.ʁo', 'nm'],
  ['w_jardin', 'le jardin', 'сад, город', 'lə ʒaʁ.dɛ̃', 'nm'],
  ['w_campagne', 'la campagne', 'село, сільська місцевість', 'la kɑ̃.paɲ', 'nf'],
  ['w_region', 'la région', 'регіон, область', 'la ʁe.ʒjɔ̃', 'nf'],
  [
    'w_monde2',
    'le monde',
    'світ; люди',
    'lə mɔ̃d',
    'nm',
    '«Tout le monde» = «усі», а не «весь світ».',
  ],
  ['w_terre', 'la terre', 'земля', 'la tɛʁ', 'nf'],
  [
    'w_mer',
    'la mer',
    'море',
    'la mɛʁ',
    'nf',
    '⚠️ Жіночий рід, а наше «море» — середній. Звучить так само, як mère (мати).',
  ],
  ['w_ciel', 'le ciel', 'небо', 'lə sjɛl', 'nm', '⚠️ Чоловічий рід, а наше «небо» — середній.'],
  ['w_montagne', 'la montagne', 'гора', 'la mɔ̃.taɲ', 'nf'],
  ['w_riviere', 'la rivière', 'річка', 'la ʁi.vjɛʁ', 'nf'],
  ['w_arbre', "l'arbre", 'дерево', 'laʁbʁ', 'nm', '⚠️ Чоловічий рід, а наше «дерево» — середній.'],
  ['w_fleur', 'la fleur', 'квітка', 'la flœʁ', 'nf'],

  // --- абстрактне, побутове ---
  ['w_chose', 'la chose', 'річ, справа', 'la ʃoz', 'nf'],
  ['w_vie', 'la vie', 'життя', 'la vi', 'nf', '⚠️ Жіночий рід, а «життя» в нас середній.'],
  ['w_main', 'la main', 'рука (кисть)', 'la mɛ̃', 'nf'],
  [
    'w_oeil',
    "l'œil / les yeux",
    'око / очі',
    'lœj / le zjø',
    'nm',
    'Множина зовсім інша: œil → yeux. Треба просто запам’ятати.',
  ],
  ['w_tete', 'la tête', 'голова', 'la tɛt', 'nf'],
  ['w_coeur', 'le cœur', 'серце', 'lə kœʁ', 'nm', '⚠️ Чоловічий рід, наше «серце» — середній.'],
  ['w_corps', 'le corps', 'тіло', 'lə kɔʁ', 'nm', 'Кінцеві -ps німі: [кор].'],
  ['w_pied', 'le pied', 'нога (ступня)', 'lə pje', 'nm', '«À pied» — пішки.'],
  [
    'w_bras',
    'le bras',
    'рука (від плеча)',
    'lə bʁɑ',
    'nm',
    '⚠️ Чоловічий рід, а наша «рука» — жіночий.',
  ],
  ['w_jambe', 'la jambe', 'нога', 'la ʒɑ̃b', 'nf'],
  ['w_dos', 'le dos', 'спина', 'lə do', 'nm', '⚠️ Чоловічий рід, а наша «спина» — жіночий.'],
  ['w_bouche', 'la bouche', 'рот', 'la buʃ', 'nf', '⚠️ Жіночий рід, а наш «рот» — чоловічий.'],
  ['w_nez', 'le nez', 'ніс', 'lə ne', 'nm'],
  [
    'w_cheveux',
    'les cheveux',
    'волосся',
    'le ʃ(ə).vø',
    'nm',
    'Завжди множина: «J’ai les cheveux courts» — «У мене коротке волосся».',
  ],
  [
    'w_visage',
    'le visage',
    'обличчя',
    'lə vi.zaʒ',
    'nm',
    '⚠️ Чоловічий рід, а наше «обличчя» — середній.',
  ],
  ['w_voix', 'la voix', 'голос', 'la vwa', 'nf', '⚠️ Жіночий рід, а наш «голос» — чоловічий.'],
  [
    'w_nom',
    'le nom',
    'ім’я, прізвище; назва',
    'lə nɔ̃',
    'nm',
    '«Nom» — це радше прізвище, а ім’я — «prénom».',
  ],
  ['w_prenom', 'le prénom', 'ім’я', 'lə pʁe.nɔ̃', 'nm'],
  ['w_age', "l'âge", 'вік', 'lɑʒ', 'nm'],
  ['w_idee', "l'idée", 'ідея, думка', 'li.de', 'nf'],
  [
    'w_raison',
    'la raison',
    'причина; розум',
    'la ʁɛ.zɔ̃',
    'nf',
    '«Avoir raison» — «мати рацію», дослівно «мати причину».',
  ],
  [
    'w_probleme',
    'le problème',
    'проблема',
    'lə pʁɔ.blɛm',
    'nm',
    '⚠️ Чоловічий рід, а наша «проблема» — жіночий.',
  ],
  ['w_exemple', "l'exemple", 'приклад', 'lɛɡ.zɑ̃pl', 'nm'],
  ['w_maniere', 'la manière', 'спосіб, манера', 'la ma.njɛʁ', 'nf'],
  ['w_facon', 'la façon', 'спосіб', 'la fa.sɔ̃', 'nf'],
  ['w_effet', "l'effet", 'ефект, наслідок', 'le.fɛ', 'nm'],
  [
    'w_besoin',
    'le besoin',
    'потреба',
    'lə bə.zwɛ̃',
    'nm',
    '«Avoir besoin de» — «потребувати»: «J’ai besoin d’aide».',
  ],
  [
    'w_envie',
    "l'envie",
    'бажання',
    'lɑ̃.vi',
    'nf',
    '«Avoir envie de» — «хотіти»: «J’ai envie de dormir».',
  ],
  [
    'w_peur',
    'la peur',
    'страх',
    'la pœʁ',
    'nf',
    '«Avoir peur» — «боятися», дослівно «мати страх».',
  ],
  [
    'w_amour',
    "l'amour",
    'кохання, любов',
    'la.muʁ',
    'nm',
    '⚠️ Чоловічий рід, хоч наша «любов» жіночого.',
  ],
  ['w_ami2', "l'ami / l'amie", 'друг / подруга', 'la.mi', 'nm'],
  [
    'w_travail2',
    'le travail',
    'робота, праця',
    'lə tʁa.vaj',
    'nm',
    'Множина неправильна: travail → travaux.',
  ],
  [
    'w_argent',
    "l'argent",
    'гроші; срібло',
    'laʁ.ʒɑ̃',
    'nm',
    'Однина, хоч «гроші» в нас множина: «l’argent EST sur la table».',
  ],
  [
    'w_prix',
    'le prix',
    'ціна; премія',
    'lə pʁi',
    'nm',
    '⚠️ Чоловічий рід, а наша «ціна» — жіночий.',
  ],
  ['w_affaire', "l'affaire", 'справа; вигідна покупка', 'la.fɛʁ', 'nf'],
  ['w_histoire', "l'histoire", 'історія, розповідь', 'lis.twaʁ', 'nf'],
  ['w_guerre', 'la guerre', 'війна', 'la ɡɛʁ', 'nf'],
  ['w_paix', 'la paix', 'мир, спокій', 'la pɛ', 'nf', '⚠️ Жіночий рід, а наш «мир» — чоловічий.'],
  ['w_pouvoir_n', 'le pouvoir', 'влада, можливість', 'lə pu.vwaʁ', 'nm'],
  ['w_droit', 'le droit', 'право', 'lə dʁwa', 'nm'],
  ['w_force', 'la force', 'сила', 'la fɔʁs', 'nf'],
  ['w_service', 'le service', 'послуга, обслуговування', 'lə sɛʁ.vis', 'nm'],
  ['w_etat', "l'état", 'стан; держава', 'le.ta', 'nm'],
  ['w_cas', 'le cas', 'випадок', 'lə kɑ', 'nm'],
  ['w_point', 'le point', 'точка, пункт', 'lə pwɛ̃', 'nm'],
  ['w_place2', 'la place', 'місце; площа', 'la plas', 'nf'],
  ['w_ordre', "l'ordre", 'порядок; наказ', 'lɔʁdʁ', 'nm'],
  ['w_projet', 'le projet', 'проєкт, задум', 'lə pʁɔ.ʒɛ', 'nm'],
  ['w_resultat', 'le résultat', 'результат', 'lə ʁe.zyl.ta', 'nm'],
  ['w_reponse', 'la réponse', 'відповідь', 'la ʁe.pɔ̃s', 'nf'],
  ['w_solution', 'la solution', 'рішення, розв’язок', 'la sɔ.ly.sjɔ̃', 'nf'],
  ['w_choix', 'le choix', 'вибір', 'lə ʃwa', 'nm'],
  ['w_niveau', 'le niveau', 'рівень', 'lə ni.vo', 'nm'],
  ['w_nombre', 'le nombre', 'кількість, число', 'lə nɔ̃bʁ', 'nm'],
  ['w_numero', 'le numéro', 'номер', 'lə ny.me.ʁo', 'nm'],
  ['w_papier', 'le papier', 'папір; документ', 'lə pa.pje', 'nm'],
  [
    'w_lettre',
    'la lettre',
    'лист; літера',
    'la lɛtʁ',
    'nf',
    '⚠️ Жіночий рід, а наш «лист» — чоловічий.',
  ],
  ['w_page', 'la page', 'сторінка', 'la paʒ', 'nf'],
  ['w_photo', 'la photo', 'фото', 'la fɔ.to', 'nf', '⚠️ Жіночий рід, а наше «фото» — середній.'],
  ['w_film', 'le film', 'фільм', 'lə film', 'nm'],
  ['w_musique', 'la musique', 'музика', 'la my.zik', 'nf'],
  ['w_chanson', 'la chanson', 'пісня', 'la ʃɑ̃.sɔ̃', 'nf'],
  ['w_jeu', 'le jeu', 'гра', 'lə ʒø', 'nm', '⚠️ Чоловічий рід, а наша «гра» — жіночий.'],
  ['w_sport', 'le sport', 'спорт', 'lə spɔʁ', 'nm'],
  ['w_cours', 'le cours', 'урок, курс', 'lə kuʁ', 'nm'],
  ['w_classe', 'la classe', 'клас', 'la klɑs', 'nf'],
  ['w_universite', "l'université", 'університет', 'ly.ni.vɛʁ.si.te', 'nf'],
  ['w_examen', "l'examen", 'іспит', 'lɛɡ.za.mɛ̃', 'nm'],
  ['w_cadeau', 'le cadeau', 'подарунок', 'lə ka.do', 'nm'],
  ['w_fete', 'la fête', 'свято, вечірка', 'la fɛt', 'nf'],

  // --- прикметники ---
  [
    'w_bon',
    'bon / bonne',
    'добрий, хороший; смачний',
    'bɔ̃ / bɔn',
    'adj',
    'Порівняльна форма неправильна: bon → meilleur, а не «plus bon».',
  ],
  ['w_mauvais', 'mauvais / mauvaise', 'поганий', 'mo.vɛ / mo.vɛz', 'adj'],
  [
    'w_vieux',
    'vieux / vieille',
    'старий',
    'vjø / vjɛj',
    'adj',
    'Перед голосною чоловіча форма стає vieil: «un vieil homme».',
  ],
  ['w_jeune', 'jeune', 'молодий', 'ʒœn', 'adj'],
  ['w_gros', 'gros / grosse', 'товстий, великий', 'ɡʁo / ɡʁos', 'adj'],
  ['w_long', 'long / longue', 'довгий', 'lɔ̃ / lɔ̃ɡ', 'adj'],
  ['w_court', 'court / courte', 'короткий', 'kuʁ / kuʁt', 'adj'],
  ['w_large', 'large', 'широкий', 'laʁʒ', 'adj', '⚠️ Хибний друг: це «широкий», а не «великий».'],
  ['w_fort', 'fort / forte', 'сильний; гучний', 'fɔʁ / fɔʁt', 'adj'],
  ['w_faible', 'faible', 'слабкий', 'fɛbl', 'adj'],
  ['w_facile', 'facile', 'легкий (простий)', 'fa.sil', 'adj'],
  ['w_difficile', 'difficile', 'важкий (складний)', 'di.fi.sil', 'adj'],
  ['w_important', 'important / importante', 'важливий', 'ɛ̃.pɔʁ.tɑ̃', 'adj'],
  ['w_possible', 'possible', 'можливий', 'pɔ.sibl', 'adj'],
  ['w_vrai', 'vrai / vraie', 'справжній, правдивий', 'vʁɛ', 'adj'],
  ['w_faux', 'faux / fausse', 'хибний, фальшивий', 'fo / fos', 'adj'],
  ['w_seul', 'seul / seule', 'єдиний; самотній', 'sœl', 'adj'],
  [
    'w_propre',
    'propre',
    'чистий; власний',
    'pʁɔpʁ',
    'adj',
    'Перед іменником — «власний» (ma propre voiture), після — «чистий» (une voiture propre).',
  ],
  ['w_sale', 'sale', 'брудний', 'sal', 'adj'],
  ['w_plein', 'plein / pleine', 'повний', 'plɛ̃ / plɛn', 'adj'],
  ['w_vide', 'vide', 'порожній', 'vid', 'adj'],
  [
    'w_chaud',
    'chaud / chaude',
    'гарячий, теплий',
    'ʃo / ʃod',
    'adj',
    '«J’ai chaud» — «мені спекотно», через avoir.',
  ],
  ['w_froid', 'froid / froide', 'холодний', 'fʁwa / fʁwad', 'adj'],
  ['w_cher', 'cher / chère', 'дорогий (за ціною і за серцем)', 'ʃɛʁ', 'adj'],
  ['w_libre', 'libre', 'вільний', 'libʁ', 'adj'],
  ['w_pret', 'prêt / prête', 'готовий', 'pʁɛ / pʁɛt', 'adj'],
  ['w_content', 'content / contente', 'задоволений, радий', 'kɔ̃.tɑ̃', 'adj'],
  ['w_heureux', 'heureux / heureuse', 'щасливий', 'ø.ʁø / ø.ʁøz', 'adj'],
  ['w_triste', 'triste', 'сумний', 'tʁist', 'adj'],
  ['w_fatigue', 'fatigué / fatiguée', 'втомлений', 'fa.ti.ɡe', 'adj'],
  ['w_malade', 'malade', 'хворий', 'ma.lad', 'adj'],
  ['w_gentil', 'gentil / gentille', 'добрий, милий', 'ʒɑ̃.ti / ʒɑ̃.tij', 'adj'],
  ['w_mechant', 'méchant / méchante', 'злий, недобрий', 'me.ʃɑ̃', 'adj'],
  ['w_calme', 'calme', 'спокійний', 'kalm', 'adj'],
  ['w_dernier', 'dernier / dernière', 'останній, минулий', 'dɛʁ.nje / dɛʁ.njɛʁ', 'adj'],
  ['w_prochain', 'prochain / prochaine', 'наступний', 'pʁɔ.ʃɛ̃ / pʁɔ.ʃɛn', 'adj'],
  ['w_premier', 'premier / première', 'перший', 'pʁə.mje / pʁə.mjɛʁ', 'adj'],
  ['w_deuxieme', 'deuxième', 'другий', 'dø.zjɛm', 'adj'],
  ['w_meilleur', 'meilleur / meilleure', 'кращий, найкращий', 'mɛ.jœʁ', 'adj'],
  ['w_different', 'différent / différente', 'інший, різний', 'di.fe.ʁɑ̃', 'adj'],
  ['w_pareil', 'pareil / pareille', 'такий самий', 'pa.ʁɛj', 'adj'],
  ['w_certain', 'certain / certaine', 'певний, деякий; упевнений', 'sɛʁ.tɛ̃ / sɛʁ.tɛn', 'adj'],
  ['w_simple', 'simple', 'простий', 'sɛ̃pl', 'adj'],
  ['w_general', 'général / générale', 'загальний', 'ʒe.ne.ʁal', 'adj'],
  ['w_public', 'public / publique', 'публічний, громадський', 'py.blik', 'adj'],
  ['w_national', 'national / nationale', 'національний', 'na.sjɔ.nal', 'adj'],
  ['w_social', 'social / sociale', 'соціальний', 'sɔ.sjal', 'adj'],
  ['w_politique', 'politique', 'політичний; політика', 'pɔ.li.tik', 'adj'],
  ['w_economique', 'économique', 'економічний; ощадливий', 'e.kɔ.nɔ.mik', 'adj'],
]
