import type { Row } from './expand'

/**
 * Ранги 1–200 — службові слова та найчастіші дієслова.
 *
 * Ця сотня — половина будь-якого французького тексту. Тут майже немає
 * «цікавих» слів: артиклі, займенники, прийменники й десяток дієслів, які
 * тримають на собі всю мову.
 */
export const BAND_1: Row[] = [
  // --- артиклі, прийменники, займенники: кістяк речення ---
  [
    'w_le',
    'le / la / les',
    'означений артикль: той самий, відомий',
    'lə / la / le',
    'prep',
    'В українській артиклів немає взагалі — але у французькій іменник без артикля майже неможливий.',
  ],
  [
    'w_de',
    'de',
    'з, від, про; (родовий відмінок)',
    'də',
    'prep',
    'Замінює наш родовий відмінок: «книга Марі» → le livre DE Marie.',
  ],
  ['w_un_art', 'un / une / des', 'неозначений артикль: якийсь, один із', 'œ̃ / yn / de', 'prep'],
  ['w_et', 'et', 'і, та', 'e', 'conj'],
  [
    'w_a_prep',
    'à',
    'до, в, у; о (годині)',
    'a',
    'prep',
    'Разом з le дає au, з les — aux. Форми «à le» не існує.',
  ],
  [
    'w_ne',
    'ne',
    'не (перша частина заперечення)',
    'nə',
    'adv',
    'Саме по собі нічого не означає — працює в парі: ne… pas, ne… jamais.',
  ],
  ['w_que', 'que', 'що; ніж; якого', 'kə', 'conj'],
  [
    'w_se',
    'se',
    'себе (зворотна частка)',
    'sə',
    'pron',
    'Стоїть ПЕРЕД дієсловом, на відміну від українського «-ся» в кінці.',
  ],
  ['w_qui', 'qui', 'хто; який (підмет)', 'ki', 'pron'],
  [
    'w_ce',
    'ce / cette / ces',
    'цей, ця, ці',
    'sə / sɛt / se',
    'adj',
    'Перед голосною чоловіча форма стає cet: cet homme.',
  ],
  [
    'w_en_pron',
    'en',
    'цього, їх; у (країні)',
    'ɑ̃',
    'pron',
    'Замінює конструкції з de: «— Tu veux du pain ? — J’EN veux.»',
  ],
  ['w_pour', 'pour', 'для, щоб, за', 'puʁ', 'prep'],
  ['w_pas', 'pas', 'не (друга частина заперечення)', 'pɑ', 'adv'],
  ['w_par', 'par', 'через, за, по', 'paʁ', 'prep'],
  [
    'w_plus',
    'plus',
    'більше; більш',
    'ply / plys',
    'adv',
    'У запереченні «ne… plus» означає «більше не». Кінцеве s то читається, то ні — залежить від значення.',
  ],
  ['w_me', 'me', 'мене, мені', 'mə', 'pron'],
  [
    'w_on',
    'on',
    'ми; хтось; люди загалом',
    'ɔ̃',
    'pron',
    'У розмові майже завжди замінює nous: «On y va» = «Ходімо». Дієслово при цьому в 3-й особі однини.',
  ],
  ['w_lui', 'lui', 'йому, їй; він (наголошено)', 'lɥi', 'pron'],
  ['w_comme', 'comme', 'як, ніби; оскільки', 'kɔm', 'conj'],
  ['w_mais', 'mais', 'але', 'mɛ', 'conj'],
  ['w_avec', 'avec', 'з (разом із)', 'a.vɛk', 'prep'],
  ['w_tout', 'tout / toute / tous', 'весь, уся, всі; зовсім', 'tu / tut / tus', 'adj'],
  ['w_y', 'y', 'там, туди', 'i', 'pron', 'Замінює місце: «Je vais à Paris» → «J’Y vais».'],
  ['w_bien', 'bien', 'добре; дуже', 'bjɛ̃', 'adv'],
  ['w_sans', 'sans', 'без', 'sɑ̃', 'prep'],
  [
    'w_ou',
    'ou',
    'або',
    'u',
    'conj',
    'Без наголосу — «або». З наголосом où — «де». На слух не відрізнити.',
  ],
  ['w_leur', 'leur / leurs', 'їхній, їхні; їм', 'lœʁ', 'adj'],
  [
    'w_si',
    'si',
    'якщо; такий; та ні ж!',
    'si',
    'conj',
    'Si — це ще й «так» у відповідь на заперечне питання: «— Tu ne viens pas ? — Si !»',
  ],
  [
    'w_moi',
    'moi',
    'я (наголошена форма), мені',
    'mwa',
    'pron',
    'Уживається після прийменника й для наголосу: «avec moi», «Moi, je pense que…»',
  ],
  ['w_te', 'te', 'тебе, тобі', 'tə', 'pron'],
  ['w_celui', 'celui / celle', 'той, та (вказівний займенник)', 'sə.lɥi / sɛl', 'pron'],
  ['w_notre', 'notre / nos', 'наш, наші', 'nɔtʁ / no', 'adj'],
  ['w_la_adv', 'là', 'там, тут, ось', 'la', 'adv'],
  ['w_meme', 'même', 'той самий; навіть', 'mɛm', 'adj'],
  ['w_votre', 'votre / vos', 'ваш, ваші', 'vɔtʁ / vo', 'adj'],
  [
    'w_rien',
    'rien',
    'нічого',
    'ʁjɛ̃',
    'pron',
    'Теж парне заперечення: «Je ne vois rien» — я нічого не бачу.',
  ],
  ['w_encore', 'encore', 'ще, знову', 'ɑ̃.kɔʁ', 'adv'],
  ['w_aussi', 'aussi', 'також, теж', 'o.si', 'adv'],
  ['w_quelque', 'quelque / quelques', 'якийсь; кілька', 'kɛl.kə', 'adj'],
  ['w_dont', 'dont', 'чий, якого, про якого', 'dɔ̃', 'pron'],
  ['w_ca', 'ça', 'це, оце', 'sa', 'pron'],
  [
    'w_peu',
    'peu',
    'мало, небагато',
    'pø',
    'adv',
    'Увага: «un peu» = трохи (позитивно), а просто «peu» = мало (негативно).',
  ],
  ['w_alors', 'alors', 'тоді, отже, ну то', 'a.lɔʁ', 'adv'],
  ['w_ici', 'ici', 'тут, сюди', 'i.si', 'adv'],
  ['w_tres', 'très', 'дуже', 'tʁɛ', 'adv'],
  ['w_chaque', 'chaque', 'кожен, кожна', 'ʃak', 'adj'],
  ['w_entre_prep', 'entre', 'між', 'ɑ̃tʁ', 'prep'],
  ['w_apres', 'après', 'після, потім', 'a.pʁɛ', 'prep'],
  ['w_avant', 'avant', 'перед, до', 'a.vɑ̃', 'prep'],
  [
    'w_depuis',
    'depuis',
    'з, від (певного часу)',
    'də.pɥi',
    'prep',
    'Французи кажуть «depuis + теперішній час» там, де ми вживаємо минулий: «J’habite ici depuis deux ans» — «Я живу тут два роки».',
  ],
  ['w_pendant', 'pendant', 'протягом, під час', 'pɑ̃.dɑ̃', 'prep'],
  ['w_contre', 'contre', 'проти; біля', 'kɔ̃tʁ', 'prep'],
  ['w_vers', 'vers', 'до, у напрямку; близько (про час)', 'vɛʁ', 'prep'],
  [
    'w_chez',
    'chez',
    'у (когось), до (когось)',
    'ʃe',
    'prep',
    'Немає прямого відповідника: «chez moi» — «у мене вдома», «chez le médecin» — «у лікаря».',
  ],
  ['w_toujours', 'toujours', 'завжди; усе ще', 'tu.ʒuʁ', 'adv'],
  ['w_jamais', 'jamais', 'ніколи', 'ʒa.mɛ', 'adv'],
  ['w_deja', 'déjà', 'вже', 'de.ʒa', 'adv'],
  ['w_enfin', 'enfin', 'нарешті; зрештою', 'ɑ̃.fɛ̃', 'adv'],
  ['w_puis', 'puis', 'потім, далі', 'pɥi', 'adv'],
  ['w_ainsi', 'ainsi', 'так, таким чином', 'ɛ̃.si', 'adv'],
  ['w_donc', 'donc', 'отже, тож', 'dɔ̃k', 'conj'],
  ['w_car', 'car', 'бо, оскільки', 'kaʁ', 'conj'],
  ['w_parce_que2', 'parce que', 'тому що', 'paʁs kə', 'conj'],
  ['w_quoi', 'quoi', 'що (після прийменника)', 'kwa', 'pron'],
  ['w_combien', 'combien', 'скільки', 'kɔ̃.bjɛ̃', 'adv'],
  ['w_trop', 'trop', 'занадто, надто', 'tʁo', 'adv'],
  ['w_assez', 'assez', 'достатньо; доволі', 'a.se', 'adv'],
  ['w_presque', 'presque', 'майже', 'pʁɛsk', 'adv'],
  ['w_surtout', 'surtout', 'особливо, головно', 'syʁ.tu', 'adv'],
  ['w_peut_etre', 'peut-être', 'можливо', 'pø.t‿ɛtʁ', 'adv'],
  ['w_vraiment', 'vraiment', 'справді, дуже', 'vʁɛ.mɑ̃', 'adv'],
  ['w_ensuite', 'ensuite', 'потім, далі', 'ɑ̃.sɥit', 'adv'],
  ['w_cependant', 'cependant', 'проте, однак', 'sə.pɑ̃.dɑ̃', 'adv'],
  ['w_pourtant', 'pourtant', 'проте, і все ж', 'puʁ.tɑ̃', 'adv'],
  ['w_ailleurs', 'ailleurs', 'в іншому місці', 'a.jœʁ', 'adv'],
  ['w_partout', 'partout', 'скрізь, усюди', 'paʁ.tu', 'adv'],
  ['w_dehors', 'dehors', 'надворі, назовні', 'də.ɔʁ', 'adv'],
  ['w_dedans', 'dedans', 'усередині', 'də.dɑ̃', 'adv'],
  ['w_devant', 'devant', 'перед (у просторі)', 'də.vɑ̃', 'prep'],
  ['w_derriere', 'derrière', 'позаду, за', 'dɛ.ʁjɛʁ', 'prep'],
  ['w_selon', 'selon', 'згідно з, за словами', 'sə.lɔ̃', 'prep'],
  ['w_malgre', 'malgré', 'попри, незважаючи на', 'mal.ɡʁe', 'prep'],
  ['w_jusque', "jusqu'à", 'до (аж до)', 'ʒys.ka', 'prep'],

  // --- дієслова-опори ---
  [
    'w_dire',
    'dire',
    'казати, говорити',
    'diʁ',
    'v',
    'Дуже неправильне: je dis, tu dis, il dit, nous disons, vous DITES, ils disent.',
  ],
  ['w_voir', 'voir', 'бачити', 'vwaʁ', 'v'],
  [
    'w_devoir',
    'devoir',
    'бути повинним, мусити',
    'də.vwaʁ',
    'v',
    'Виражає обов’язок: «Je dois partir» — «Я мушу йти».',
  ],
  [
    'w_falloir',
    'falloir',
    'бути потрібним (треба)',
    'fa.lwaʁ',
    'v',
    'Тільки безособово: «Il faut travailler» — «Треба працювати». Іншої особи не буває.',
  ],
  ['w_trouver', 'trouver', 'знаходити; вважати', 'tʁu.ve', 'v'],
  ['w_donner', 'donner', 'давати', 'dɔ.ne', 'v'],
  ['w_mettre', 'mettre', 'класти, ставити; вдягати', 'mɛtʁ', 'v'],
  ['w_penser', 'penser', 'думати', 'pɑ̃.se', 'v'],
  ['w_croire', 'croire', 'вірити, вважати', 'kʁwaʁ', 'v'],
  ['w_sembler', 'sembler', 'здаватися', 'sɑ̃.ble', 'v'],
  ['w_laisser', 'laisser', 'залишати, дозволяти', 'lɛ.se', 'v'],
  [
    'w_rester',
    'rester',
    'залишатися',
    'ʁɛs.te',
    'v',
    'У минулому часі бере être: «je suis resté».',
  ],
  ['w_passer', 'passer', 'проходити; проводити (час)', 'pɑ.se', 'v'],
  [
    'w_entendre',
    'entendre',
    'чути',
    'ɑ̃.tɑ̃dʁ',
    'v',
    'Не плутай: entendre — чути (вухом), écouter — слухати (навмисно).',
  ],
  [
    'w_demander',
    'demander',
    'питати; просити',
    'də.mɑ̃.de',
    'v',
    '⚠️ Хибний друг: це не «вимагати», а «питати» або «просити».',
  ],
  [
    'w_attendre',
    'attendre',
    'чекати',
    'a.tɑ̃dʁ',
    'v',
    'Без прийменника: «j’attends le bus», а не «attends pour».',
  ],
  ['w_porter', 'porter', 'нести; носити (одяг)', 'pɔʁ.te', 'v'],
  ['w_appeler', 'appeler', 'кликати, дзвонити комусь', 'a.p(ə)le', 'v'],
  ['w_tenir', 'tenir', 'тримати', 'tə.niʁ', 'v'],
  [
    'w_connaitre',
    'connaître',
    'знати (когось/щось на досвід)',
    'kɔ.nɛtʁ',
    'v',
    'connaître — знати людину чи місто; savoir — знати факт або вміти. Плутанина типова.',
  ],
  ['w_sortir', 'sortir', 'виходити', 'sɔʁ.tiʁ', 'v'],
  ['w_partir', 'partir', 'вирушати, від’їжджати', 'paʁ.tiʁ', 'v'],
  ['w_arriver', 'arriver', 'прибувати; траплятися', 'a.ʁi.ve', 'v'],
  ['w_entrer', 'entrer', 'входити', 'ɑ̃.tʁe', 'v'],
  ['w_revenir', 'revenir', 'повертатися (сюди)', 'ʁə.v(ə)niʁ', 'v'],
  ['w_devenir', 'devenir', 'ставати', 'də.v(ə)niʁ', 'v'],
  ['w_suivre', 'suivre', 'слідувати, іти за', 'sɥivʁ', 'v'],
  ['w_vivre', 'vivre', 'жити', 'vivʁ', 'v'],
  ['w_mourir', 'mourir', 'помирати', 'mu.ʁiʁ', 'v'],
  ['w_ouvrir', 'ouvrir', 'відкривати', 'u.vʁiʁ', 'v'],
  ['w_fermer', 'fermer', 'закривати', 'fɛʁ.me', 'v'],
  ['w_commencer', 'commencer', 'починати', 'kɔ.mɑ̃.se', 'v'],
  ['w_finir', 'finir', 'закінчувати', 'fi.niʁ', 'v'],
  ['w_continuer', 'continuer', 'продовжувати', 'kɔ̃.ti.nɥe', 'v'],
  ['w_arreter', 'arrêter', 'зупиняти, припиняти', 'a.ʁɛ.te', 'v'],
  ['w_essayer', 'essayer', 'пробувати, приміряти', 'e.sɛ.je', 'v'],
  ['w_reussir', 'réussir', 'вдаватися, досягати успіху', 'ʁe.y.siʁ', 'v'],
  ['w_perdre', 'perdre', 'втрачати, губити; програвати', 'pɛʁdʁ', 'v'],
  ['w_gagner', 'gagner', 'вигравати; заробляти', 'ɡa.ɲe', 'v'],
  ['w_payer', 'payer', 'платити', 'pɛ.je', 'v'],
  ['w_acheter', 'acheter', 'купувати', 'aʃ.te', 'v'],
  ['w_vendre', 'vendre', 'продавати', 'vɑ̃dʁ', 'v'],
  ['w_couter', 'coûter', 'коштувати', 'ku.te', 'v'],
  ['w_compter', 'compter', 'рахувати; розраховувати', 'kɔ̃.te', 'v'],
  ['w_changer', 'changer', 'міняти, змінювати', 'ʃɑ̃.ʒe', 'v'],
  ['w_choisir', 'choisir', 'вибирати', 'ʃwa.ziʁ', 'v'],
  ['w_decider', 'décider', 'вирішувати', 'de.si.de', 'v'],
  ['w_expliquer', 'expliquer', 'пояснювати', 'ɛks.pli.ke', 'v'],
  ['w_apprendre', 'apprendre', 'вчити, вивчати; дізнаватися', 'a.pʁɑ̃dʁ', 'v'],
  ['w_montrer', 'montrer', 'показувати', 'mɔ̃.tʁe', 'v'],
  ['w_repondre', 'répondre', 'відповідати', 'ʁe.pɔ̃dʁ', 'v'],
  ['w_raconter', 'raconter', 'розповідати', 'ʁa.kɔ̃.te', 'v'],
  ['w_oublier', 'oublier', 'забувати', 'u.bli.je', 'v'],
  [
    'w_chercher',
    'chercher',
    'шукати',
    'ʃɛʁ.ʃe',
    'v',
    'Без прийменника: «je cherche mes clés», а не «cherche pour».',
  ],
  ['w_rencontrer', 'rencontrer', 'зустрічати', 'ʁɑ̃.kɔ̃.tʁe', 'v'],
  [
    'w_jouer',
    'jouer',
    'грати',
    'ʒwe',
    'v',
    'jouer À — у гру (au football), jouer DE — на інструменті (du piano).',
  ],
  ['w_etudier', 'étudier', 'вивчати, навчатися', 'e.ty.dje', 'v'],
  [
    'w_marcher',
    'marcher',
    'ходити пішки; працювати (про річ)',
    'maʁ.ʃe',
    'v',
    'Про техніку теж: «Ça ne marche pas» — «Це не працює».',
  ],
  ['w_courir', 'courir', 'бігти', 'ku.ʁiʁ', 'v'],
  ['w_monter', 'monter', 'підійматися; сідати (в транспорт)', 'mɔ̃.te', 'v'],
  ['w_descendre', 'descendre', 'спускатися; виходити (з транспорту)', 'de.sɑ̃dʁ', 'v'],
  ['w_tomber', 'tomber', 'падати', 'tɔ̃.be', 'v'],
  [
    'w_aider',
    'aider',
    'допомагати',
    'ɛ.de',
    'v',
    'Прямо, без прийменника: «je t’aide» — «я тобі допомагаю».',
  ],
  ['w_servir', 'servir', 'служити; подавати', 'sɛʁ.viʁ', 'v'],
  ['w_utiliser', 'utiliser', 'використовувати', 'y.ti.li.ze', 'v'],
  ['w_garder', 'garder', 'зберігати, залишати собі', 'ɡaʁ.de', 'v'],
  ['w_envoyer', 'envoyer', 'надсилати', 'ɑ̃.vwa.je', 'v'],
  ['w_recevoir', 'recevoir', 'отримувати; приймати гостей', 'ʁə.sə.vwaʁ', 'v'],
  ['w_offrir', 'offrir', 'дарувати, пропонувати', 'ɔ.fʁiʁ', 'v'],
  ['w_apporter', 'apporter', 'приносити', 'a.pɔʁ.te', 'v'],
  ['w_rendre', 'rendre', 'повертати (щось); робити (якимось)', 'ʁɑ̃dʁ', 'v'],
  ['w_sentir', 'sentir', 'відчувати; пахнути', 'sɑ̃.tiʁ', 'v'],
  ['w_toucher', 'toucher', 'торкатися', 'tu.ʃe', 'v'],
  [
    'w_tirer',
    'tirer',
    'тягнути; стріляти',
    'ti.ʁe',
    'v',
    'На дверях «TIREZ» — «на себе», «POUSSEZ» — «від себе».',
  ],
  ['w_pousser', 'pousser', 'штовхати; рости', 'pu.se', 'v'],
  ['w_couper', 'couper', 'різати', 'ku.pe', 'v'],
  ['w_casser', 'casser', 'ламати, бити', 'kɑ.se', 'v'],
  ['w_construire', 'construire', 'будувати', 'kɔ̃s.tʁɥiʁ', 'v'],
  ['w_creer', 'créer', 'створювати', 'kʁe.e', 'v'],
  ['w_permettre', 'permettre', 'дозволяти', 'pɛʁ.mɛtʁ', 'v'],
  ['w_accepter', 'accepter', 'приймати, погоджуватися', 'ak.sɛp.te', 'v'],
  ['w_refuser', 'refuser', 'відмовляти(ся)', 'ʁə.fy.ze', 'v'],
  ['w_proposer', 'proposer', 'пропонувати', 'pʁɔ.po.ze', 'v'],
  ['w_presenter', 'présenter', 'представляти, показувати', 'pʁe.zɑ̃.te', 'v'],
  ['w_remarquer', 'remarquer', 'помічати', 'ʁə.maʁ.ke', 'v'],
  ['w_reconnaitre', 'reconnaître', 'впізнавати; визнавати', 'ʁə.kɔ.nɛtʁ', 'v'],
  ['w_sourire_v', 'sourire', 'усміхатися; усмішка', 'su.ʁiʁ', 'v'],
  ['w_rire', 'rire', 'сміятися', 'ʁiʁ', 'v'],
  ['w_pleurer', 'pleurer', 'плакати', 'plœ.ʁe', 'v'],
  ['w_crier', 'crier', 'кричати', 'kʁi.je', 'v'],
  ['w_chanter', 'chanter', 'співати', 'ʃɑ̃.te', 'v'],
  ['w_danser', 'danser', 'танцювати', 'dɑ̃.se', 'v'],
  ['w_voyager', 'voyager', 'подорожувати', 'vwa.ja.ʒe', 'v'],
  [
    'w_visiter',
    'visiter',
    'відвідувати (місце)',
    'vi.zi.te',
    'v',
    '⚠️ Тільки про місця. Провідати людину — «rendre visite à quelqu’un».',
  ],
  ['w_rentrer', 'rentrer', 'повертатися додому', 'ʁɑ̃.tʁe', 'v'],
  ['w_quitter', 'quitter', 'покидати, залишати', 'ki.te', 'v'],
  ['w_oser', 'oser', 'наважуватися', 'o.ze', 'v'],
  ['w_valoir', 'valoir', 'коштувати, бути вартим', 'va.lwaʁ', 'v'],
]
