import type { Row } from './expand'

/**
 * Побутове ядро: дім, їжа, одяг, транспорт, погода, кольори, числа.
 * Це та лексика, без якої не прожити дня у Франції.
 */
export const BAND_3: Row[] = [
  // --- дім і речі ---
  ['w_piece', 'la pièce', 'кімната; деталь; монета', 'la pjɛs', 'nf'],
  ['w_salon', 'le salon', 'вітальня', 'lə sa.lɔ̃', 'nm'],
  ['w_toilettes', 'les toilettes', 'туалет', 'le twa.lɛt', 'nf', 'Завжди множина й жіночий рід.'],
  ['w_mur', 'le mur', 'стіна', 'lə myʁ', 'nm', '⚠️ Чоловічий рід, а наша «стіна» — жіночий.'],
  [
    'w_sol',
    'le sol',
    'підлога; ґрунт',
    'lə sɔl',
    'nm',
    '⚠️ Чоловічий рід, а наша «підлога» — жіночий.',
  ],
  ['w_toit', 'le toit', 'дах', 'lə twa', 'nm'],
  ['w_escalier', "l'escalier", 'сходи', 'lɛs.ka.lje', 'nm', 'Однина, хоч наші «сходи» — множина.'],
  ['w_ascenseur', "l'ascenseur", 'ліфт', 'la.sɑ̃.sœʁ', 'nm'],
  ['w_cle', 'la clé', 'ключ', 'la kle', 'nf', '⚠️ Жіночий рід, а наш «ключ» — чоловічий.'],
  ['w_meuble', 'le meuble', 'меблі (один предмет)', 'lə mœbl', 'nm'],
  ['w_armoire', "l'armoire", 'шафа', 'laʁ.mwaʁ', 'nf'],
  ['w_canape', 'le canapé', 'диван', 'lə ka.na.pe', 'nm'],
  [
    'w_miroir',
    'le miroir',
    'дзеркало',
    'lə mi.ʁwaʁ',
    'nm',
    '⚠️ Чоловічий рід, а наше «дзеркало» — середній.',
  ],
  ['w_lampe', 'la lampe', 'лампа', 'la lɑ̃p', 'nf'],
  ['w_assiette', "l'assiette", 'тарілка', 'la.sjɛt', 'nf'],
  [
    'w_verre',
    'le verre',
    'склянка; скло',
    'lə vɛʁ',
    'nm',
    '⚠️ Чоловічий рід, а наша «склянка» — жіночий.',
  ],
  ['w_tasse', 'la tasse', 'чашка', 'la tɑs', 'nf'],
  ['w_bouteille', 'la bouteille', 'пляшка', 'la bu.tɛj', 'nf'],
  ['w_couteau', 'le couteau', 'ніж', 'lə ku.to', 'nm'],
  ['w_fourchette', 'la fourchette', 'виделка', 'la fuʁ.ʃɛt', 'nf'],
  ['w_cuillere', 'la cuillère', 'ложка', 'la kɥi.jɛʁ', 'nf'],
  [
    'w_sac',
    'le sac',
    'сумка, пакет',
    'lə sak',
    'nm',
    '⚠️ Чоловічий рід, а наша «сумка» — жіночий.',
  ],
  ['w_boite', 'la boîte', 'коробка; клуб', 'la bwat', 'nf'],
  [
    'w_machine',
    'la machine',
    'машина (пристрій)',
    'la ma.ʃin',
    'nf',
    'Автомобіль — «la voiture», а «machine» — це механізм, пральна машина тощо.',
  ],
  ['w_appareil', "l'appareil", 'апарат, пристрій', 'la.pa.ʁɛj', 'nm'],
  ['w_ecran', "l'écran", 'екран', 'le.kʁɑ̃', 'nm'],
  ['w_portable', 'le portable', 'мобільний; ноутбук', 'lə pɔʁ.tabl', 'nm'],
  ['w_drap', 'le drap', 'простирадло', 'lə dʁa', 'nm'],
  ['w_serviette', 'la serviette', 'рушник; серветка; портфель', 'la sɛʁ.vjɛt', 'nf'],
  ['w_savon', 'le savon', 'мило', 'lə sa.vɔ̃', 'nm'],

  // --- їжа ---
  ['w_nourriture', 'la nourriture', 'їжа', 'la nu.ʁi.tyʁ', 'nf'],
  ['w_repas', 'le repas', 'прийом їжі, трапеза', 'lə ʁə.pɑ', 'nm'],
  ['w_plat', 'le plat', 'страва; тарілка', 'lə plɑ', 'nm'],
  [
    'w_oeuf',
    "l'œuf / les œufs",
    'яйце / яйця',
    'lœf / le zø',
    'nm',
    'Дивна множина на слух: œuf [єф] → œufs [є], f зникає.',
  ],
  [
    'w_beurre',
    'le beurre',
    'масло',
    'lə bœʁ',
    'nm',
    '⚠️ Чоловічий рід, а наше «масло» — середній.',
  ],
  ['w_huile', "l'huile", 'олія', 'lɥil', 'nf'],
  ['w_sel', 'le sel', 'сіль', 'lə sɛl', 'nm', '⚠️ Чоловічий рід, а наша «сіль» — жіночий.'],
  ['w_poivre', 'le poivre', 'перець', 'lə pwavʁ', 'nm'],
  ['w_riz', 'le riz', 'рис', 'lə ʁi', 'nm'],
  ['w_pates', 'les pâtes', 'макарони', 'le pɑt', 'nf'],
  ['w_soupe', 'la soupe', 'суп', 'la sup', 'nf', '⚠️ Жіночий рід, наш «суп» — чоловічий.'],
  ['w_salade', 'la salade', 'салат', 'la sa.lad', 'nf'],
  ['w_fruit', 'le fruit', 'фрукт', 'lə fʁɥi', 'nm'],
  ['w_orange', "l'orange", 'апельсин; помаранчевий', 'lɔ.ʁɑ̃ʒ', 'nf'],
  ['w_banane', 'la banane', 'банан', 'la ba.nan', 'nf'],
  ['w_fraise', 'la fraise', 'полуниця', 'la fʁɛz', 'nf'],
  [
    'w_tomate',
    'la tomate',
    'помідор',
    'la tɔ.mat',
    'nf',
    '⚠️ Жіночий рід, наш «помідор» — чоловічий.',
  ],
  [
    'w_pomme_terre',
    'la pomme de terre',
    'картопля',
    'la pɔm də tɛʁ',
    'nf',
    'Дослівно «земляне яблуко».',
  ],
  ['w_carotte', 'la carotte', 'морква', 'la ka.ʁɔt', 'nf'],
  ['w_oignon', "l'oignon", 'цибуля', 'lɔ.ɲɔ̃', 'nm', 'Пишеться з i, але читається [оньйон].'],
  ['w_boeuf', 'le bœuf', 'яловичина; бик', 'lə bœf', 'nm'],
  ['w_porc', 'le porc', 'свинина', 'lə pɔʁ', 'nm'],
  ['w_jambon', 'le jambon', 'шинка', 'lə ʒɑ̃.bɔ̃', 'nm'],
  ['w_gateau', 'le gâteau', 'торт, тістечко', 'lə ɡɑ.to', 'nm'],
  [
    'w_glace',
    'la glace',
    'морозиво; лід; дзеркало',
    'la ɡlas',
    'nf',
    '⚠️ Жіночий рід, а наше «морозиво» — середній.',
  ],
  ['w_chocolat', 'le chocolat', 'шоколад', 'lə ʃɔ.kɔ.la', 'nm'],
  ['w_biere', 'la bière', 'пиво', 'la bjɛʁ', 'nf', '⚠️ Жіночий рід, наше «пиво» — середній.'],
  ['w_jus', 'le jus', 'сік', 'lə ʒy', 'nm'],
  ['w_boisson', 'la boisson', 'напій', 'la bwa.sɔ̃', 'nf'],
  ['w_croissant', 'le croissant', 'круасан', 'lə kʁwa.sɑ̃', 'nm'],
  ['w_baguette', 'la baguette', 'багет', 'la ba.ɡɛt', 'nf'],
  [
    'w_menu',
    'le menu',
    'комплексне меню',
    'lə mə.ny',
    'nm',
    'Увага: список страв — «la carte», а «le menu» — це набір за фіксованою ціною.',
  ],
  ['w_serveur', 'le serveur / la serveuse', 'офіціант / офіціантка', 'lə sɛʁ.vœʁ', 'nm'],
  ['w_pourboire', 'le pourboire', 'чайові', 'lə puʁ.bwaʁ', 'nm'],
  ['w_faim', 'la faim', 'голод', 'la fɛ̃', 'nf', '⚠️ Жіночий рід, а наш «голод» — чоловічий.'],
  ['w_soif', 'la soif', 'спрага', 'la swaf', 'nf'],
  ['w_gout', 'le goût', 'смак', 'lə ɡu', 'nm'],

  // --- одяг ---
  ['w_vetement', 'le vêtement', 'одяг (річ)', 'lə vɛt.mɑ̃', 'nm'],
  ['w_chemise', 'la chemise', 'сорочка', 'la ʃə.miz', 'nf'],
  [
    'w_pantalon',
    'le pantalon',
    'штани',
    'lə pɑ̃.ta.lɔ̃',
    'nm',
    'Однина, хоч наші «штани» — множина: «un pantalon».',
  ],
  ['w_robe', 'la robe', 'сукня', 'la ʁɔb', 'nf'],
  ['w_jupe', 'la jupe', 'спідниця', 'la ʒyp', 'nf'],
  ['w_veste', 'la veste', 'піджак, куртка', 'la vɛst', 'nf'],
  [
    'w_manteau',
    'le manteau',
    'пальто',
    'lə mɑ̃.to',
    'nm',
    '⚠️ Чоловічий рід, а наше «пальто» — середній.',
  ],
  ['w_pull', 'le pull', 'светр', 'lə pyl', 'nm'],
  ['w_chaussure', 'la chaussure', 'взуття (пара — les chaussures)', 'la ʃo.syʁ', 'nf'],
  ['w_chapeau', 'le chapeau', 'капелюх', 'lə ʃa.po', 'nm'],
  ['w_lunettes', 'les lunettes', 'окуляри', 'le ly.nɛt', 'nf'],
  [
    'w_montre',
    'la montre',
    'наручний годинник',
    'la mɔ̃tʁ',
    'nf',
    'Наручний — «montre», настінний — «horloge», а «heure» — це час.',
  ],
  ['w_taille', 'la taille', 'розмір; талія; зріст', 'la tɑj', 'nf'],
  ['w_poche', 'la poche', 'кишеня', 'la pɔʃ', 'nf'],

  // --- транспорт і місто ---
  ['w_avion', "l'avion", 'літак', 'la.vjɔ̃', 'nm'],
  ['w_bateau', 'le bateau', 'човен, корабель', 'lə ba.to', 'nm'],
  ['w_velo', 'le vélo', 'велосипед', 'lə ve.lo', 'nm'],
  [
    'w_moto',
    'la moto',
    'мотоцикл',
    'la mɔ.to',
    'nf',
    '⚠️ Жіночий рід, а наш «мотоцикл» — чоловічий.',
  ],
  ['w_taxi', 'le taxi', 'таксі', 'lə tak.si', 'nm'],
  ['w_station', 'la station', 'станція (метро)', 'la sta.sjɔ̃', 'nf'],
  ['w_arret', "l'arrêt", 'зупинка', 'la.ʁɛ', 'nm'],
  ['w_billet', 'le billet', 'квиток; купюра', 'lə bi.jɛ', 'nm'],
  ['w_voyage', 'le voyage', 'подорож', 'lə vwa.jaʒ', 'nm'],
  ['w_valise', 'la valise', 'валіза', 'la va.liz', 'nf'],
  ['w_aeroport', "l'aéroport", 'аеропорт', 'la.e.ʁɔ.pɔʁ', 'nm'],
  ['w_hotel', "l'hôtel", 'готель', 'lo.tɛl', 'nm'],
  ['w_chambre2', 'la chambre', 'кімната, номер', 'la ʃɑ̃bʁ', 'nf'],
  ['w_marche', 'le marché', 'ринок', 'lə maʁ.ʃe', 'nm'],
  ['w_supermarche', 'le supermarché', 'супермаркет', 'lə sy.pɛʁ.maʁ.ʃe', 'nm'],
  ['w_banque', 'la banque', 'банк', 'la bɑ̃k', 'nf', '⚠️ Жіночий рід, наш «банк» — чоловічий.'],
  ['w_poste', 'la poste', 'пошта', 'la pɔst', 'nf'],
  ['w_eglise', "l'église", 'церква', 'le.ɡliz', 'nf'],
  ['w_theatre', 'le théâtre', 'театр', 'lə te.ɑtʁ', 'nm'],
  ['w_cinema', 'le cinéma', 'кінотеатр, кіно', 'lə si.ne.ma', 'nm'],
  ['w_bibliotheque', 'la bibliothèque', 'бібліотека', 'la bi.bli.jɔ.tɛk', 'nf'],
  ['w_quartier', 'le quartier', 'район, квартал', 'lə kaʁ.tje', 'nm'],
  ['w_centre', 'le centre', 'центр', 'lə sɑ̃tʁ', 'nm'],
  ['w_coin', 'le coin', 'кут, куточок', 'lə kwɛ̃', 'nm'],
  ['w_feu', 'le feu', 'вогонь; світлофор', 'lə fø', 'nm'],
  ['w_carrefour', 'le carrefour', 'перехрестя', 'lə kaʁ.fuʁ', 'nm'],
  ['w_plan', 'le plan', 'план, карта міста', 'lə plɑ̃', 'nm'],
  ['w_carte2', 'la carte', 'карта; картка; меню', 'la kaʁt', 'nf'],

  // --- погода й природа ---
  ['w_meteo', 'la météo', 'прогноз погоди', 'la me.te.o', 'nf'],
  [
    'w_soleil',
    'le soleil',
    'сонце',
    'lə sɔ.lɛj',
    'nm',
    '⚠️ Чоловічий рід, наше «сонце» — середній. «Il fait soleil» — сонячно.',
  ],
  ['w_pluie', 'la pluie', 'дощ', 'la plɥi', 'nf', '⚠️ Жіночий рід, наш «дощ» — чоловічий.'],
  ['w_neige', 'la neige', 'сніг', 'la nɛʒ', 'nf'],
  ['w_vent', 'le vent', 'вітер', 'lə vɑ̃', 'nm'],
  ['w_nuage', 'le nuage', 'хмара', 'lə nɥaʒ', 'nm', '⚠️ Чоловічий рід, наша «хмара» — жіночий.'],
  ['w_orage', "l'orage", 'гроза', 'lɔ.ʁaʒ', 'nm'],
  ['w_saison', 'la saison', 'пора року, сезон', 'la sɛ.zɔ̃', 'nf'],
  [
    'w_printemps',
    'le printemps',
    'весна',
    'lə pʁɛ̃.tɑ̃',
    'nm',
    '⚠️ Чоловічий рід, наша «весна» — жіночий. І прийменник інший: «AU printemps», але «EN été».',
  ],
  ['w_ete', "l'été", 'літо', 'le.te', 'nm'],
  ['w_automne', "l'automne", 'осінь', 'lo.tɔn', 'nm', 'Читається [отон] — m не звучить.'],
  ['w_hiver', "l'hiver", 'зима', 'li.vɛʁ', 'nm', '⚠️ Чоловічий рід, наша «зима» — жіночий.'],
  ['w_animal', "l'animal / les animaux", 'тварина / тварини', 'la.ni.mal / le za.ni.mo', 'nm'],
  ['w_oiseau', "l'oiseau", 'птах', 'lwa.zo', 'nm'],
  ['w_cheval', 'le cheval / les chevaux', 'кінь / коні', 'lə ʃ(ə).val', 'nm'],

  // --- кольори ---
  [
    'w_couleur',
    'la couleur',
    'колір',
    'la ku.lœʁ',
    'nf',
    '⚠️ Жіночий рід, наш «колір» — чоловічий.',
  ],
  ['w_blanc', 'blanc / blanche', 'білий', 'blɑ̃ / blɑ̃ʃ', 'adj'],
  ['w_noir', 'noir / noire', 'чорний', 'nwaʁ', 'adj'],
  ['w_rouge', 'rouge', 'червоний', 'ʁuʒ', 'adj'],
  ['w_bleu', 'bleu / bleue', 'синій, блакитний', 'blø', 'adj'],
  ['w_vert', 'vert / verte', 'зелений', 'vɛʁ / vɛʁt', 'adj'],
  ['w_jaune', 'jaune', 'жовтий', 'ʒon', 'adj'],
  ['w_gris', 'gris / grise', 'сірий', 'ɡʁi / ɡʁiz', 'adj'],
  [
    'w_marron',
    'marron',
    'коричневий',
    'ma.ʁɔ̃',
    'adj',
    'Не змінюється за родом і числом: «des chaussures marron».',
  ],
  ['w_rose', 'rose', 'рожевий; троянда', 'ʁoz', 'adj'],
  ['w_violet', 'violet / violette', 'фіолетовий', 'vjɔ.lɛ / vjɔ.lɛt', 'adj'],
  ['w_clair', 'clair / claire', 'світлий; ясний', 'klɛʁ', 'adj'],
  ['w_fonce', 'foncé / foncée', 'темний (про колір)', 'fɔ̃.se', 'adj'],
  ['w_sombre', 'sombre', 'темний, похмурий', 'sɔ̃bʁ', 'adj'],

  // --- числа й кількість ---
  ['w_demi', 'demi / demie', 'половина, пів', 'də.mi', 'adj'],
  ['w_million', 'le million', 'мільйон', 'lə mi.ljɔ̃', 'nm'],
  ['w_moitie', 'la moitié', 'половина', 'la mwa.tje', 'nf'],
  ['w_plusieurs', 'plusieurs', 'кілька, декілька', 'ply.zjœʁ', 'adj'],
  [
    'w_beaucoup2',
    'beaucoup de',
    'багато (чогось)',
    'bo.ku də',
    'adv',
    'Після кількості завжди просто de, без артикля: «beaucoup DE gens».',
  ],
  ['w_quelques', 'quelques', 'кілька', 'kɛl.kə', 'adj'],
  ['w_autre', 'autre', 'інший', 'otʁ', 'adj'],
  ['w_certains', 'certains', 'деякі', 'sɛʁ.tɛ̃', 'adj'],
  ['w_aucun', 'aucun / aucune', 'жоден', 'o.kœ̃ / o.kyn', 'adj'],
  ['w_tel', 'tel / telle', 'такий', 'tɛl', 'adj'],
  ['w_kilo', 'le kilo', 'кілограм', 'lə ki.lo', 'nm'],
  ['w_litre', 'le litre', 'літр', 'lə litʁ', 'nm'],
  ['w_metre', 'le mètre', 'метр', 'lə mɛtʁ', 'nm'],
  ['w_kilometre', 'le kilomètre', 'кілометр', 'lə ki.lɔ.mɛtʁ', 'nm'],
  ['w_euro', "l'euro", 'євро', 'lø.ʁo', 'nm'],
  ['w_pourcent', 'le pour cent', 'відсоток', 'lə puʁ sɑ̃', 'nm'],
]
