import type { Row } from './expand'

/**
 * Остання сотня першої тисячі: місяці, професії, порядкові числівники,
 * родина ширшого кола та побутові дрібниці, без яких список був би неповний.
 */
export const BAND_6: Row[] = [
  // --- місяці ---
  [
    'w_janvier',
    'janvier',
    'січень',
    'ʒɑ̃.vje',
    'nm',
    'Місяці пишуться з малої літери й уживаються без артикля: «en janvier».',
  ],
  ['w_fevrier', 'février', 'лютий', 'fev.ʁje', 'nm'],
  ['w_mars', 'mars', 'березень', 'maʁs', 'nm', 'Кінцеве s тут читається — виняток.'],
  ['w_avril', 'avril', 'квітень', 'a.vʁil', 'nm'],
  ['w_mai', 'mai', 'травень', 'mɛ', 'nm'],
  ['w_juin', 'juin', 'червень', 'ʒɥɛ̃', 'nm'],
  ['w_juillet', 'juillet', 'липень', 'ʒɥi.jɛ', 'nm'],
  ['w_aout', 'août', 'серпень', 'ut', 'nm', 'Читається просто [ут] — жодного «а-о-у».'],
  ['w_septembre', 'septembre', 'вересень', 'sɛp.tɑ̃bʁ', 'nm'],
  ['w_octobre', 'octobre', 'жовтень', 'ɔk.tɔbʁ', 'nm'],
  ['w_novembre', 'novembre', 'листопад', 'nɔ.vɑ̃bʁ', 'nm'],
  ['w_decembre', 'décembre', 'грудень', 'de.sɑ̃bʁ', 'nm'],

  // --- порядкові числівники ---
  [
    'w_troisieme',
    'troisième',
    'третій',
    'tʁwa.zjɛm',
    'adj',
    'Усі порядкові, крім «premier», утворюються однаково: число + -ième.',
  ],
  ['w_quatrieme', 'quatrième', 'четвертий', 'ka.tʁi.jɛm', 'adj'],
  ['w_cinquieme', 'cinquième', 'п’ятий', 'sɛ̃.kjɛm', 'adj'],
  ['w_sixieme', 'sixième', 'шостий', 'si.zjɛm', 'adj'],

  // --- родина ширше ---
  ['w_oncle', "l'oncle", 'дядько', 'lɔ̃kl', 'nm'],
  ['w_tante', 'la tante', 'тітка', 'la tɑ̃t', 'nf'],
  ['w_cousin', 'le cousin / la cousine', 'двоюрідний брат / сестра', 'lə ku.zɛ̃', 'nm'],
  ['w_neveu', 'le neveu', 'племінник', 'lə nə.vø', 'nm'],
  ['w_petit_fils', 'le petit-fils', 'онук', 'lə p(ə)ti fis', 'nm'],
  ['w_beau_pere', 'le beau-père', 'тесть, свекор; вітчим', 'lə bo pɛʁ', 'nm'],
  ['w_belle_mere', 'la belle-mère', 'теща, свекруха; мачуха', 'la bɛl mɛʁ', 'nf'],
  ['w_frere_soeur', 'les frères et sœurs', 'брати й сестри', 'le fʁɛʁ e sœʁ', 'nm'],

  // --- професії ---
  ['w_infirmier', "l'infirmier / l'infirmière", 'медбрат / медсестра', 'lɛ̃.fiʁ.mje', 'nm'],
  [
    'w_avocat',
    "l'avocat",
    'адвокат; авокадо',
    'la.vɔ.ka',
    'nm',
    'Так, це й «адвокат», і «авокадо» — одне слово.',
  ],
  ['w_vendeur', 'le vendeur / la vendeuse', 'продавець / продавчиня', 'lə vɑ̃.dœʁ', 'nm'],
  ['w_boulanger', 'le boulanger', 'пекар', 'lə bu.lɑ̃.ʒe', 'nm'],
  ['w_cuisinier', 'le cuisinier', 'кухар', 'lə kɥi.zi.nje', 'nm'],
  ['w_chauffeur', 'le chauffeur', 'водій', 'lə ʃo.fœʁ', 'nm'],
  ['w_facteur', 'le facteur', 'листоноша; чинник', 'lə fak.tœʁ', 'nm'],
  ['w_pompier', 'le pompier', 'пожежник', 'lə pɔ̃.pje', 'nm'],
  ['w_policier', 'le policier', 'поліцейський', 'lə pɔ.li.sje', 'nm'],
  ['w_secretaire', 'le / la secrétaire', 'секретар / секретарка', 'lə sə.kʁe.tɛʁ', 'nmf'],
  ['w_directeur', 'le directeur / la directrice', 'директор / директорка', 'lə di.ʁɛk.tœʁ', 'nm'],
  ['w_agriculteur', "l'agriculteur", 'фермер, аграрій', 'la.ɡʁi.kyl.tœʁ', 'nm'],
  ['w_ouvrier', "l'ouvrier", 'робітник', 'lu.vʁi.je', 'nm'],
  ['w_journaliste', 'le / la journaliste', 'журналіст / журналістка', 'lə ʒuʁ.na.list', 'nmf'],
  ['w_chercheur', 'le chercheur', 'науковець, дослідник', 'lə ʃɛʁ.ʃœʁ', 'nm'],

  // --- школа й предмети ---
  [
    'w_eleve',
    "l'élève",
    'учень / учениця',
    'le.lɛv',
    'nmf',
    'Однакове для обох статей — рід показує артикль: l’élève.',
  ],
  ['w_maitre', 'le maître / la maîtresse', 'учитель молодших класів', 'lə mɛtʁ', 'nm'],
  [
    'w_lycee',
    'le lycée',
    'ліцей (старша школа)',
    'lə li.se',
    'nm',
    'Виняток: закінчується на -ée, але чоловічого роду.',
  ],
  [
    'w_college',
    'le collège',
    'колеж (середня школа)',
    'lə kɔ.lɛʒ',
    'nm',
    '⚠️ Хибний друг: це не університет, а середня школа.',
  ],
  ['w_cahier', 'le cahier', 'зошит', 'lə ka.je', 'nm'],
  ['w_crayon', 'le crayon', 'олівець', 'lə kʁɛ.jɔ̃', 'nm'],
  ['w_gomme', 'la gomme', 'гумка', 'la ɡɔm', 'nf'],
  ['w_dictionnaire', 'le dictionnaire', 'словник', 'lə dik.sjɔ.nɛʁ', 'nm'],
  ['w_grammaire', 'la grammaire', 'граматика', 'la ɡʁa.mɛʁ', 'nf'],
  ['w_vocabulaire', 'le vocabulaire', 'словниковий запас', 'lə vɔ.ka.by.lɛʁ', 'nm'],
  ['w_prononciation', 'la prononciation', 'вимова', 'la pʁɔ.nɔ̃.sja.sjɔ̃', 'nf'],
  ['w_geographie', 'la géographie', 'географія', 'la ʒe.ɔ.ɡʁa.fi', 'nf'],
  ['w_informatique', "l'informatique", 'інформатика', 'lɛ̃.fɔʁ.ma.tik', 'nf'],

  // --- побут ---
  [
    'w_menage',
    'le ménage',
    'прибирання; домогосподарство',
    'lə me.naʒ',
    'nm',
    '«Faire le ménage» — прибирати вдома.',
  ],
  ['w_vaisselle', 'la vaisselle', 'посуд', 'la vɛ.sɛl', 'nf', '«Faire la vaisselle» — мити посуд.'],
  ['w_linge', 'le linge', 'білизна, речі для прання', 'lə lɛ̃ʒ', 'nm'],
  ['w_poubelle', 'la poubelle', 'смітник', 'la pu.bɛl', 'nf'],
  ['w_frigo', 'le frigo', 'холодильник', 'lə fʁi.ɡo', 'nm'],
  ['w_four', 'le four', 'духовка', 'lə fuʁ', 'nm'],
  ['w_douche', 'la douche', 'душ', 'la duʃ', 'nf', '⚠️ Жіночий рід, наш «душ» — чоловічий.'],
  ['w_robinet', 'le robinet', 'кран', 'lə ʁɔ.bi.nɛ', 'nm'],
  ['w_bruit', 'le bruit', 'шум', 'lə bʁɥi', 'nm'],
  ['w_odeur', "l'odeur", 'запах', 'lɔ.dœʁ', 'nf', '⚠️ Жіночий рід, наш «запах» — чоловічий.'],
  [
    'w_lumiere',
    'la lumière',
    'світло',
    'la ly.mjɛʁ',
    'nf',
    '⚠️ Жіночий рід, наше «світло» — середній.',
  ],
  ['w_air', "l'air", 'повітря; вигляд', 'lɛʁ', 'nm', '«Avoir l’air» — «мати вигляд, здаватися».'],
  ['w_bois', 'le bois', 'дерево (матеріал); ліс', 'lə bwa', 'nm'],
  ['w_pierre', 'la pierre', 'камінь', 'la pjɛʁ', 'nf', '⚠️ Жіночий рід, наш «камінь» — чоловічий.'],
  ['w_fer', 'le fer', 'залізо; праска', 'lə fɛʁ', 'nm'],
  ['w_plastique', 'le plastique', 'пластик', 'lə plas.tik', 'nm'],
  ['w_tissu', 'le tissu', 'тканина', 'lə ti.sy', 'nm'],

  // --- ще дієслова ---
  ['w_avoir_besoin', 'avoir besoin de', 'потребувати', 'a.vwaʁ bə.zwɛ̃ də', 'v'],
  ['w_allumer', 'allumer', 'вмикати; запалювати', 'a.ly.me', 'v'],
  ['w_eteindre', 'éteindre', 'вимикати; гасити', 'e.tɛ̃dʁ', 'v'],
  ['w_appuyer', 'appuyer', 'натискати; спиратися', 'a.pɥi.je', 'v'],
  ['w_tenter', 'tenter', 'намагатися; спокушати', 'tɑ̃.te', 'v'],
  [
    'w_emporter',
    'emporter',
    'забирати з собою',
    'ɑ̃.pɔʁ.te',
    'v',
    '«À emporter» — «з собою» (про їжу навинос).',
  ],
  [
    'w_preter',
    'prêter',
    'позичати (комусь)',
    'pʁɛ.te',
    'v',
    'prêter — дати в борг, emprunter — узяти в борг. Наше «позичати» покриває обидва.',
  ],
  ['w_emprunter', 'emprunter', 'позичати (у когось)', 'ɑ̃.pʁœ̃.te', 'v'],
  ['w_rembourser', 'rembourser', 'повертати гроші', 'ʁɑ̃.buʁ.se', 'v'],
  ['w_reserver', 'réserver', 'бронювати', 'ʁe.zɛʁ.ve', 'v'],
  ['w_annuler', 'annuler', 'скасовувати', 'a.ny.le', 'v'],
  ['w_signer', 'signer', 'підписувати', 'si.ɲe', 'v'],
  ['w_imprimer', 'imprimer', 'друкувати', 'ɛ̃.pʁi.me', 'v'],
  ['w_enregistrer', 'enregistrer', 'записувати, зберігати', 'ɑ̃.ʁə.ʒis.tʁe', 'v'],
  ['w_effacer', 'effacer', 'стирати, видаляти', 'e.fa.se', 'v'],
  ['w_trier', 'trier', 'сортувати', 'tʁi.je', 'v'],
  ['w_partager', 'partager', 'ділитися, розділяти', 'paʁ.ta.ʒe', 'v'],
  ['w_echanger', 'échanger', 'обмінювати', 'e.ʃɑ̃.ʒe', 'v'],
  ['w_ressembler', 'ressembler à', 'бути схожим на', 'ʁə.sɑ̃.ble a', 'v'],
  ['w_dependre', 'dépendre de', 'залежати від', 'de.pɑ̃dʁ də', 'v'],
  ['w_contenir', 'contenir', 'містити', 'kɔ̃.tə.niʁ', 'v'],
  ['w_exister', 'exister', 'існувати', 'ɛɡ.zis.te', 'v'],
  [
    'w_se_passer',
    'se passer',
    'відбуватися, траплятися',
    'sə pɑ.se',
    'v',
    '«Qu’est-ce qui se passe ?» — «Що відбувається?»',
  ],
  ['w_durer', 'durer', 'тривати', 'dy.ʁe', 'v'],
  ['w_faire_attention', 'faire attention', 'бути уважним, стерегтися', 'fɛʁ a.tɑ̃.sjɔ̃', 'v'],
  ['w_fonctionner', 'fonctionner', 'функціонувати, працювати', 'fɔ̃k.sjɔ.ne', 'v'],
  ['w_servir_a', 'servir à', 'слугувати для', 'sɛʁ.viʁ a', 'v'],
  ['w_valoir_la_peine', 'valoir la peine', 'бути вартим зусиль', 'va.lwaʁ la pɛn', 'v'],

  // --- дрібні, але часті ---
  ['w_chacun', 'chacun / chacune', 'кожен, кожна (окремо)', 'ʃa.kœ̃ / ʃa.kyn', 'pron'],
  ['w_personne_pron', 'personne', 'ніхто', 'pɛʁ.sɔn', 'pron'],
  ['w_quelquun', "quelqu'un", 'хтось', 'kɛl.kœ̃', 'pron'],
  ['w_quelque_chose', 'quelque chose', 'щось', 'kɛl.kə ʃoz', 'pron'],
  ['w_nimporte', "n'importe quel", 'будь-який', 'nɛ̃.pɔʁt kɛl', 'adj'],
  ['w_meme_pron', 'soi-même', 'сам себе', 'swa mɛm', 'pron'],
  ['w_ensemble_n', "l'ensemble", 'сукупність, ансамбль', 'lɑ̃.sɑ̃bl', 'nm'],
  [
    'w_tour',
    'le tour',
    'черга; прогулянка; оберт',
    'lə tuʁ',
    'nm',
    '«C’est ton tour» — «Твоя черга». А «la tour» (жін.) — це вежа.',
  ],
  ['w_plupart', 'la plupart', 'більшість', 'la ply.paʁ', 'nf'],
  ['w_reste', 'le reste', 'решта, залишок', 'lə ʁɛst', 'nm'],
  ['w_suite', 'la suite', 'продовження', 'la sɥit', 'nf', '«Tout de suite» — «негайно».'],
  [
    'w_train_de',
    'être en train de',
    'бути в процесі (робити щось)',
    'ɛtʁ ɑ̃ tʁɛ̃ də',
    'phrase',
    'Так виражають тривалу дію: «Je suis en train de manger» — «Я саме їм».',
  ],
  [
    'w_venir_de',
    'venir de',
    'щойно зробити',
    'və.niʁ də',
    'phrase',
    '«Je viens de manger» — «Я щойно поїв». Найближче минуле.',
  ],
  ['w_aller_futur', 'aller + інфінітив', 'найближче майбутнє', 'a.le', 'phrase'],
  ['w_avoir_ans', 'avoir … ans', 'мати … років', 'a.vwaʁ ɑ̃', 'phrase'],
  [
    'w_faire_beau',
    'il fait beau',
    'гарна погода',
    'il fɛ bo',
    'phrase',
    'Погода завжди через безособове «il fait»: il fait chaud / froid / beau.',
  ],
  ['w_y_avoir', 'il y a … que', 'уже … як', 'i.lja kə', 'phrase'],
]
