import type { Exam } from './types'

/**
 * Level exams. Graded strictly (near-miss answers are not forgiven here —
 * see `gradeAnswer`'s `strict` option), timed, and mixed across all four
 * skills so the score means something.
 */

export const examA0A1: Exam = {
  id: 'exam-a0a1',
  title: 'Іспит на рівень A1',
  passScore: 70,
  minutes: 30,
  sections: [
    {
      title: 'Аудіювання',
      description: 'Послухай і обери правильну відповідь. Можна прослухати кілька разів.',
      exercises: [
        {
          id: 'ex1a1',
          kind: 'listen',
          prompt: 'Що ти чуєш?',
          audioText: 'Bonsoir, comment allez-vous ?',
          options: [
            'Добрий вечір, як ви?',
            'Добрий день, як тебе звати?',
            'На добраніч, до завтра',
          ],
          answer: 0,
        },
        {
          id: 'ex1a2',
          kind: 'listen',
          prompt: 'Яке число?',
          audioText: 'quatre-vingt-seize',
          options: ['76', '86', '96'],
          answer: 2,
        },
        {
          id: 'ex1a3',
          kind: 'listen',
          prompt: 'Котра година?',
          audioText: 'Il est huit heures et quart.',
          options: ['8:15', '8:30', '7:45'],
          answer: 0,
        },
        {
          id: 'ex1a4',
          kind: 'listen',
          prompt: 'Куди він іде?',
          audioText: 'Je vais à la boulangerie.',
          options: ['В аптеку', 'У пекарню', 'На вокзал'],
          answer: 1,
        },
        {
          id: 'ex1a5',
          kind: 'listen',
          prompt: '«є» чи «мають»?',
          audioText: 'Ils ont deux enfants.',
          options: ['Вони мають двох дітей', 'Вони — двоє дітей'],
          answer: 0,
        },
      ],
    },
    {
      title: 'Лексика',
      description: 'Перевіряємо активний словниковий запас.',
      exercises: [
        {
          id: 'ex1v1',
          kind: 'type',
          prompt: 'Напиши з артиклем: «книга»',
          question: 'книга (з артиклем)',
          answer: ['le livre'],
          accents: true,
        },
        {
          id: 'ex1v2',
          kind: 'type',
          prompt: 'Напиши з артиклем: «стіл»',
          question: 'стіл (з артиклем)',
          answer: ['la table'],
          accents: true,
        },
        {
          id: 'ex1v3',
          kind: 'match',
          prompt: 'З’єднай пари',
          pairs: [
            { fr: 'la gare', uk: 'вокзал' },
            { fr: 'le pain', uk: 'хліб' },
            { fr: 'la sœur', uk: 'сестра' },
            { fr: 'le jeudi', uk: 'четвер' },
          ],
        },
        {
          id: 'ex1v4',
          kind: 'mcq',
          prompt: 'Що означає «tout droit»?',
          question: 'tout droit',
          options: ['праворуч', 'прямо', 'ліворуч'],
          answer: 1,
        },
        {
          id: 'ex1v5',
          kind: 'type',
          prompt: 'Напиши французькою: «рахунок, будь ласка»',
          question: 'рахунок, будь ласка',
          answer: ["l'addition, s'il vous plaît", "l'addition s'il vous plaît"],
          accents: true,
        },
      ],
    },
    {
      title: 'Граматика',
      description: 'Артиклі, дієслова, заперечення.',
      exercises: [
        {
          id: 'ex1g1',
          kind: 'cloze',
          prompt: 'Встав форму être',
          sentence: 'Vous ___ ukrainiens ?',
          answer: ['êtes'],
          translation: 'Ви українці?',
          options: ['es', 'êtes', 'sont', 'sommes'],
        },
        {
          id: 'ex1g2',
          kind: 'cloze',
          prompt: 'Встав артикль',
          sentence: '___ fenêtre est ouverte.',
          answer: ['la'],
          translation: 'Вікно відчинене.',
          options: ['le', 'la', "l'", 'les'],
        },
        {
          id: 'ex1g3',
          kind: 'cloze',
          prompt: 'Заперечення',
          sentence: "Je n'ai pas ___ voiture.",
          answer: ['de'],
          translation: 'У мене немає машини.',
          options: ['une', 'de', 'la', 'des'],
        },
        {
          id: 'ex1g4',
          kind: 'cloze',
          prompt: 'Частковий артикль',
          sentence: 'Je bois ___ ___ eau.',
          answer: ["de l'"],
          translation: 'Я п’ю воду.',
          options: ['du', 'de la', "de l'", 'des'],
        },
        {
          id: 'ex1g5',
          kind: 'cloze',
          prompt: 'Злиття артикля',
          sentence: 'Nous allons ___ musée.',
          answer: ['au'],
          translation: 'Ми йдемо в музей.',
          options: ['à le', 'au', 'à la', 'aux'],
        },
        {
          id: 'ex1g6',
          kind: 'cloze',
          prompt: 'Дієслово на -er',
          sentence: 'Ils ___ la musique. (écouter)',
          answer: ['écoutent', 'ecoutent'],
          translation: 'Вони слухають музику.',
          options: ['écoute', 'écoutes', 'écoutez', 'écoutent'],
        },
        {
          id: 'ex1g7',
          kind: 'cloze',
          prompt: 'Присвійний',
          sentence: '___ amie habite à Nice.',
          answer: ['mon'],
          translation: 'Моя подруга живе в Ніцці.',
          options: ['mon', 'ma', 'mes'],
        },
        {
          id: 'ex1g8',
          kind: 'mcq',
          prompt: 'Знайди помилку',
          question: 'Je suis vingt ans.',
          options: ['Помилки немає', "Треба J'ai vingt ans", 'Треба Je suis vingt'],
          answer: 1,
        },
      ],
    },
    {
      title: 'Продукування',
      description: 'Переклади з української. Тут перевіряється активне володіння.',
      exercises: [
        {
          id: 'ex1p1',
          kind: 'translate',
          prompt: 'Переклади французькою',
          question: 'Мене звати Марина, я з України.',
          answer: [
            "je m'appelle olena, je viens d'ukraine",
            "je m'appelle olena je viens d'ukraine",
          ],
        },
        {
          id: 'ex1p2',
          kind: 'translate',
          prompt: 'Переклади французькою',
          question: 'Я не говорю англійською.',
          answer: ['je ne parle pas anglais'],
        },
        {
          id: 'ex1p3',
          kind: 'translate',
          prompt: 'Переклади французькою',
          question: 'Мені двадцять п’ять років.',
          answer: ["j'ai vingt-cinq ans", "j'ai vingt cinq ans"],
        },
        {
          id: 'ex1p4',
          kind: 'wordbank',
          prompt: 'Збери речення',
          question: 'У мене є брат і сестра.',
          answer: "J'ai un frère et une sœur.",
          distractors: ['suis', 'une', 'un'],
        },
        {
          id: 'ex1p5',
          kind: 'translate',
          prompt: 'Переклади французькою',
          question: 'Перепрошую, де вокзал?',
          answer: ['excusez-moi, où est la gare', 'excusez-moi où est la gare'],
        },
      ],
    },
    {
      title: 'Диктант',
      description: 'Найчесніша перевірка: німі закінчення чути неможливо, їх треба знати.',
      exercises: [
        {
          id: 'ex1d1',
          kind: 'dictation',
          prompt: 'Запиши почуте',
          text: 'Je suis étudiante à Paris.',
          translation: 'Я студентка в Парижі.',
        },
        {
          id: 'ex1d2',
          kind: 'dictation',
          prompt: 'Запиши почуте',
          text: 'Ils travaillent le samedi.',
          translation: 'Вони працюють у суботу.',
        },
        {
          id: 'ex1d3',
          kind: 'dictation',
          prompt: 'Запиши почуте',
          text: "Il n'y a pas de problème.",
          translation: 'Немає проблеми.',
        },
      ],
    },
  ],
}

export const examA1A2: Exam = {
  id: 'exam-a1a2',
  title: 'Іспит на рівень A2',
  passScore: 70,
  minutes: 30,
  sections: [
    {
      title: 'Аудіювання',
      description: 'Послухай і обери правильну відповідь.',
      exercises: [
        {
          id: 'ex2a1',
          kind: 'listen',
          prompt: 'Що сталося?',
          audioText: 'Hier, je suis allée au cinéma avec ma sœur.',
          options: [
            'Вчора я ходила в кіно з сестрою',
            'Завтра я піду в кіно з сестрою',
            'Вчора я була вдома з сестрою',
          ],
          answer: 0,
        },
        {
          id: 'ex2a2',
          kind: 'listen',
          prompt: 'Про що йдеться?',
          audioText: "J'ai mal à la tête depuis ce matin.",
          options: ['Болить голова з ранку', 'Болить живіт з учора', 'Болить горло увечері'],
          answer: 0,
        },
        {
          id: 'ex2a3',
          kind: 'listen',
          prompt: 'Яка ціна?',
          audioText: 'Cela fait soixante-douze euros.',
          options: ['62 євро', '72 євро', '82 євро'],
          answer: 1,
        },
        {
          id: 'ex2a4',
          kind: 'listen',
          prompt: 'Що порівнюють?',
          audioText: "Le train est moins cher que l'avion.",
          options: [
            'Потяг дешевший за літак',
            'Потяг дорожчий за літак',
            'Потяг такий самий, як літак',
          ],
          answer: 0,
        },
      ],
    },
    {
      title: 'Граматика: минулий час',
      description: 'passé composé — головна тема рівня A2.',
      exercises: [
        {
          id: 'ex2g1',
          kind: 'cloze',
          prompt: 'Допоміжне дієслово',
          sentence: 'Elle ___ allée à Lyon.',
          answer: ['est'],
          translation: 'Вона поїхала в Ліон.',
          options: ['a', 'est', 'ai'],
        },
        {
          id: 'ex2g2',
          kind: 'cloze',
          prompt: 'Допоміжне дієслово',
          sentence: "J'___ mangé une pomme.",
          answer: ['ai'],
          translation: 'Я з’їв яблуко.',
          options: ['ai', 'suis', 'est'],
        },
        {
          id: 'ex2g3',
          kind: 'type',
          prompt: 'Дієприкметник від «prendre»',
          question: 'prendre →',
          answer: ['pris'],
        },
        {
          id: 'ex2g4',
          kind: 'type',
          prompt: 'Дієприкметник від «faire»',
          question: 'faire →',
          answer: ['fait'],
        },
        {
          id: 'ex2g5',
          kind: 'mcq',
          prompt: 'Говорить жінка',
          question: 'Je suis…',
          options: ['parti', 'partie', 'partis'],
          answer: 1,
          optionsAreFrench: true,
        },
        {
          id: 'ex2g6',
          kind: 'cloze',
          prompt: 'Зворотне дієслово в минулому',
          sentence: 'Elle ___ levée tôt.',
          answer: ["s'est", 'sest'],
          translation: 'Вона встала рано.',
        },
      ],
    },
    {
      title: 'Граматика: решта',
      description: 'Прикметники, порівняння, вказівні, en.',
      exercises: [
        {
          id: 'ex2r1',
          kind: 'cloze',
          prompt: 'Узгодь прикметник',
          sentence: 'Une ___ voiture. (nouveau)',
          answer: ['nouvelle'],
          translation: 'Нова машина.',
          options: ['nouveau', 'nouvelle', 'nouveaux'],
        },
        {
          id: 'ex2r2',
          kind: 'mcq',
          prompt: 'Як сказати «кращий»?',
          question: '«кращий ресторан»',
          options: ['le plus bon restaurant', 'le meilleur restaurant'],
          answer: 1,
          optionsAreFrench: true,
        },
        {
          id: 'ex2r3',
          kind: 'cloze',
          prompt: 'Вказівний',
          sentence: '___ hôtel est cher.',
          answer: ['cet'],
          translation: 'Цей готель дорогий.',
          options: ['ce', 'cet', 'cette'],
        },
        {
          id: 'ex2r4',
          kind: 'cloze',
          prompt: 'Займенник',
          sentence: '— Tu veux du thé ? — Oui, j’___ veux.',
          answer: ['en'],
          translation: '— Хочеш чаю? — Так, хочу.',
        },
        {
          id: 'ex2r5',
          kind: 'cloze',
          prompt: 'Біль',
          sentence: "J'ai mal ___ dos.",
          answer: ['au'],
          translation: 'У мене болить спина.',
          options: ['à le', 'au', 'à la', 'aux'],
        },
      ],
    },
    {
      title: 'Продукування та диктант',
      description: 'Активне володіння та орфографія.',
      exercises: [
        {
          id: 'ex2p1',
          kind: 'translate',
          prompt: 'Переклади французькою',
          question: 'Вчора ми поїли в ресторані.',
          answer: ['hier, nous avons mangé au restaurant', 'hier nous avons mangé au restaurant'],
        },
        {
          id: 'ex2p2',
          kind: 'translate',
          prompt: 'Переклади французькою',
          question: 'Париж більший за Ліон.',
          answer: ['paris est plus grand que lyon'],
        },
        {
          id: 'ex2p3',
          kind: 'translate',
          prompt: 'Переклади французькою',
          question: 'У мене болить голова.',
          answer: ["j'ai mal à la tête"],
        },
        {
          id: 'ex2p4',
          kind: 'dictation',
          prompt: 'Запиши почуте',
          text: 'Nous sommes allés au musée hier.',
          translation: 'Вчора ми ходили в музей.',
        },
        {
          id: 'ex2p5',
          kind: 'dictation',
          prompt: 'Запиши почуте',
          text: "Elle s'est levée à six heures.",
          translation: 'Вона встала о шостій.',
        },
      ],
    },
  ],
}

export const examA2B1: Exam = {
  id: 'exam-a2b1',
  title: 'Іспит на рівень B1',
  passScore: 70,
  minutes: 40,
  sections: [
    {
      title: 'Аудіювання',
      description: 'Довші висловлювання, зокрема з новин.',
      exercises: [
        {
          id: 'ex3a1',
          kind: 'listen',
          prompt: 'Що сталося?',
          audioText: 'Je lisais tranquillement quand mon frère est arrivé.',
          options: [
            'Я читав, коли прийшов брат',
            'Я прочитав книгу з братом',
            'Мій брат читав, коли я прийшов',
          ],
          answer: 0,
        },
        {
          id: 'ex3a2',
          kind: 'listen',
          prompt: 'Про що йдеться?',
          audioText: 'Une grève a été annoncée dans les transports pour jeudi.',
          options: [
            'Оголошено страйк на транспорті',
            'Транспорт подорожчав',
            'Розслідування закрито',
          ],
          answer: 0,
        },
        {
          id: 'ex3a3',
          kind: 'listen',
          prompt: 'Яка умова?',
          audioText: "Si j'avais plus de temps, je voyagerais davantage.",
          options: [
            'Він подорожує багато',
            'Якби мав більше часу, подорожував би більше',
            'Він подорожуватиме наступного року',
          ],
          answer: 1,
        },
        {
          id: 'ex3a4',
          kind: 'listen',
          prompt: 'Що переказують?',
          audioText: 'Elle a répondu qu’elle ne savait pas.',
          options: [
            'Вона відповіла, що не знає',
            'Вона питає, чи ти знаєш',
            'Вона знала відповідь',
          ],
          answer: 0,
        },
        {
          id: 'ex3a5',
          kind: 'listen',
          prompt: 'Одночасні дії?',
          audioText: 'Il travaille en écoutant de la musique.',
          options: [
            'Він працює, слухаючи музику',
            'Він слухає музику після роботи',
            'Він не може працювати з музикою',
          ],
          answer: 0,
        },
      ],
    },
    {
      title: 'Минулі часи',
      description: 'Imparfait, passé composé та plus-que-parfait у контексті.',
      exercises: [
        {
          id: 'ex3p1',
          kind: 'cloze',
          prompt: 'Тло чи подія?',
          sentence: 'Il ___ quand le téléphone a sonné. (dormir)',
          answer: ['dormait'],
          translation: 'Він спав, коли задзвонив телефон.',
          options: ['dormait', 'a dormi'],
        },
        {
          id: 'ex3p2',
          kind: 'cloze',
          prompt: 'Постав час',
          sentence: 'Hier, nous ___ un excellent film. (voir)',
          answer: ['avons vu'],
          translation: 'Учора ми подивилися чудовий фільм.',
          options: ['avons vu', 'voyions'],
        },
        {
          id: 'ex3p3',
          kind: 'cloze',
          prompt: 'Plus-que-parfait',
          sentence: 'Quand je suis arrivé, il ___ déjà parti.',
          answer: ['était', 'etait'],
          translation: 'Коли я прийшов, він уже пішов.',
          options: ['était', 'avait', 'est'],
        },
        {
          id: 'ex3p4',
          kind: 'type',
          prompt: 'Imparfait від faire для «nous»',
          question: 'nous (faire) → imparfait',
          answer: ['faisions'],
        },
        {
          id: 'ex3p5',
          kind: 'mcq',
          prompt: 'Що це означає?',
          question: "J'ai su la vérité.",
          options: ['Я знав правду', 'Я дізнався правду'],
          answer: 1,
        },
      ],
    },
    {
      title: 'Займенники та підрядні',
      description: 'COD/COI, y, en, відносні займенники.',
      exercises: [
        {
          id: 'ex3r1',
          kind: 'cloze',
          prompt: 'Займенник',
          sentence: 'J’écris à mes parents → Je ___ écris.',
          answer: ['leur'],
          translation: 'Я їм пишу.',
          options: ['les', 'leur', 'lui'],
        },
        {
          id: 'ex3r2',
          kind: 'cloze',
          prompt: 'y чи en?',
          sentence: '— Tu as des frères ? — Oui, j’___ ai deux.',
          answer: ['en'],
          translation: '— У тебе є брати? — Так, двоє.',
          options: ['y', 'en'],
        },
        {
          id: 'ex3r3',
          kind: 'cloze',
          prompt: 'qui чи que?',
          sentence: "C'est le livre ___ j'ai acheté.",
          answer: ['que'],
          translation: 'Це книга, яку я купив.',
          options: ['qui', 'que'],
        },
        {
          id: 'ex3r4',
          kind: 'cloze',
          prompt: 'Відносний займенник',
          sentence: "C'est le sujet ___ nous avons parlé.",
          answer: ['dont'],
          translation: 'Це тема, про яку ми говорили.',
          options: ['que', 'dont', 'où'],
        },
        {
          id: 'ex3r5',
          kind: 'mcq',
          prompt: 'Порядок',
          question: '«Я йому це сказав»',
          options: ['Je lui le ai dit.', 'Je le lui ai dit.'],
          answer: 1,
          optionsAreFrench: true,
        },
      ],
    },
    {
      title: 'Умова, майбутнє, subjonctif',
      description: 'Найпоширеніші джерела помилок на цьому рівні.',
      exercises: [
        {
          id: 'ex3s1',
          kind: 'mcq',
          prompt: 'Знайди помилку',
          question: "Si j'aurais le temps, je viendrais.",
          options: ['Помилки немає', "Треба «Si j'avais le temps»"],
          answer: 1,
        },
        {
          id: 'ex3s2',
          kind: 'cloze',
          prompt: 'Тип 1',
          sentence: "Si j'ai le temps, je ___. (venir)",
          answer: ['viendrai'],
          translation: 'Якщо матиму час, прийду.',
          options: ['viendrai', 'viendrais', 'viens'],
        },
        {
          id: 'ex3s3',
          kind: 'cloze',
          prompt: 'Subjonctif',
          sentence: 'Il faut que tu ___ patient. (être)',
          answer: ['sois'],
          translation: 'Треба, щоб ти був терплячий.',
          options: ['sois', 'es', 'seras'],
        },
        {
          id: 'ex3s4',
          kind: 'mcq',
          prompt: 'Який спосіб?',
          question: 'Je ne pense pas qu’il ___ raison.',
          options: ['a', 'ait'],
          answer: 1,
          optionsAreFrench: true,
        },
        {
          id: 'ex3s5',
          kind: 'cloze',
          prompt: 'Conditionnel',
          sentence: 'Tu ___ te reposer. (devoir)',
          answer: ['devrais'],
          translation: 'Тобі варто відпочити.',
          options: ['devrais', 'devras', 'dois'],
        },
        {
          id: 'ex3s6',
          kind: 'type',
          prompt: 'Futur simple від aller для «je»',
          question: 'je (aller) → futur simple',
          answer: ['irai'],
        },
      ],
    },
    {
      title: 'Продукування та диктант',
      description: 'Активне володіння структурами рівня B1.',
      exercises: [
        {
          id: 'ex3w1',
          kind: 'translate',
          prompt: 'Переклади французькою',
          question: 'Я читав, коли вона подзвонила.',
          answer: ['je lisais quand elle a téléphoné', 'je lisais quand elle a appelé'],
        },
        {
          id: 'ex3w2',
          kind: 'translate',
          prompt: 'Переклади французькою',
          question: 'Якби я був багатий, я б купив дім.',
          answer: [
            "si j'étais riche, j'achèterais une maison",
            "si j'etais riche, j'acheterais une maison",
          ],
        },
        {
          id: 'ex3w3',
          kind: 'translate',
          prompt: 'Переклади французькою',
          question: 'Я хочу, щоб ти прийшов.',
          answer: ['je veux que tu viennes'],
        },
        {
          id: 'ex3w4',
          kind: 'translate',
          prompt: 'Переклади французькою',
          question: 'Це книга, про яку я говорив.',
          answer: ["c'est le livre dont j'ai parlé", "c'est le livre dont je parlais"],
        },
        {
          id: 'ex3w5',
          kind: 'dictation',
          prompt: 'Запиши почуте',
          text: 'Il pleuvait quand je suis sorti.',
          translation: 'Йшов дощ, коли я вийшов.',
        },
        {
          id: 'ex3w6',
          kind: 'dictation',
          prompt: 'Запиши почуте',
          text: 'Bien qu’il soit tard, je continue.',
          translation: 'Хоча пізно, я продовжую.',
        },
        {
          id: 'ex3w7',
          kind: 'dictation',
          prompt: 'Запиши почуте',
          text: 'Les résultats seront publiés demain.',
          translation: 'Результати опублікують завтра.',
        },
      ],
    },
  ],
}

export const examB1B2: Exam = {
  id: 'exam-b1b2',
  title: 'Іспит на рівень B2',
  passScore: 70,
  minutes: 50,
  sections: [
    {
      title: 'Аудіювання',
      description: 'Жива мова: скорочення, медіа, розмовний регістр.',
      exercises: [
        {
          id: 'ex4a1',
          kind: 'listen',
          prompt: 'Що сказано?',
          audioText: 'Je ne sais pas ce qu’il veut dire.',
          options: [
            'Я не знаю, що він хоче сказати',
            'Він не знає, що я кажу',
            'Я знаю, що він каже',
          ],
          answer: 0,
        },
        {
          id: 'ex4a2',
          kind: 'listen',
          prompt: 'Новини',
          audioText: 'Selon des sources proches, un accord serait envisagé.',
          options: ['Угода начебто розглядається', 'Угоду підписано', 'Перемовин не буде'],
          answer: 0,
        },
        {
          id: 'ex4a3',
          kind: 'listen',
          prompt: 'Поступка',
          audioText: 'J’ai beau relire, je ne comprends pas.',
          options: [
            'Хоч скільки перечитую, не розумію',
            'Я гарно перечитав і зрозумів',
            'Я не хочу перечитувати',
          ],
          answer: 0,
        },
        {
          id: 'ex4a4',
          kind: 'listen',
          prompt: 'Докір',
          audioText: 'Tu aurais pu me prévenir.',
          options: ['Ти міг би мене попередити', 'Ти мене попередив', 'Ти мене попередиш'],
          answer: 0,
        },
        {
          id: 'ex4a5',
          kind: 'listen',
          prompt: 'Розмовний регістр',
          audioText: 'Du coup, on se voit demain vers midi.',
          options: ['Отже, побачимось завтра близько полудня', 'Ми бачилися вчора ввечері'],
          answer: 0,
        },
      ],
    },
    {
      title: 'Регістр і жива мова',
      description: 'Уміння обрати доречний рівень мови.',
      exercises: [
        {
          id: 'ex4r1',
          kind: 'mcq',
          prompt: 'Регістр',
          question: 'Який варіант доречний на співбесіді?',
          options: ['J’ai un truc à vous dire.', 'Je souhaiterais aborder un point avec vous.'],
          answer: 1,
          optionsAreFrench: true,
        },
        {
          id: 'ex4r2',
          kind: 'type',
          prompt: 'Повна форма',
          question: 'T’as compris ? → (повна форма)',
          answer: ['tu as compris'],
        },
        {
          id: 'ex4r3',
          kind: 'mcq',
          prompt: 'Значення',
          question: 'Ce n’est pas terrible.',
          options: ['Це чудово', 'Так собі'],
          answer: 1,
        },
        {
          id: 'ex4r4',
          kind: 'mcq',
          prompt: 'Розмовне слово',
          question: '«Bosser» нейтрально —',
          options: ['travailler', 'voyager'],
          answer: 0,
          optionsAreFrench: true,
        },
        {
          id: 'ex4r5',
          kind: 'cloze',
          prompt: 'Підсилення',
          sentence: 'C’est long, ___ épuisant.',
          answer: ['voire'],
          translation: 'Це довго, ба навіть виснажливо.',
          options: ['voire', 'voir', 'vers'],
        },
      ],
    },
    {
      title: 'Складні структури',
      description: 'Відносні займенники, поступка, узгодження часів.',
      exercises: [
        {
          id: 'ex4g1',
          kind: 'cloze',
          prompt: 'Форма lequel',
          sentence: 'Le projet sur ___ je travaille est terminé.',
          answer: ['lequel'],
          translation: 'Проєкт, над яким я працюю, завершено.',
          options: ['lequel', 'laquelle', 'dont'],
        },
        {
          id: 'ex4g2',
          kind: 'cloze',
          prompt: 'Злиття',
          sentence: 'Le problème ___ nous faisons face est complexe.',
          answer: ['auquel'],
          translation: 'Проблема, з якою ми стикаємося, складна.',
          options: ['auquel', 'à lequel', 'dont'],
        },
        {
          id: 'ex4g3',
          kind: 'cloze',
          prompt: 'ce qui чи ce que?',
          sentence: 'Dis-moi ___ ___ se passe.',
          answer: ['ce qui'],
          translation: 'Скажи мені, що відбувається.',
        },
        {
          id: 'ex4g4',
          kind: 'cloze',
          prompt: 'Subjonctif passé',
          sentence: 'Je suis ravi qu’il ___ réussi.',
          answer: ['ait'],
          translation: 'Я радий, що йому вдалося.',
          options: ['ait', 'soit', 'a'],
        },
        {
          id: 'ex4g5',
          kind: 'mcq',
          prompt: 'Знайди помилку',
          question: 'Malgré qu’il soit tard, je continue.',
          options: ['Помилки немає', 'Треба «Bien qu’il soit tard»'],
          answer: 1,
        },
        {
          id: 'ex4g6',
          kind: 'cloze',
          prompt: 'Поступка',
          sentence: 'Il ___ ___ essayer, rien ne change.',
          answer: ['a beau'],
          translation: 'Хоч скільки він намагається, нічого не змінюється.',
        },
        {
          id: 'ex4g7',
          kind: 'cloze',
          prompt: 'Жаль',
          sentence: 'J’___ ___ partir plus tôt.',
          answer: ['aurais dû', 'aurais du'],
          translation: 'Мені слід було піти раніше.',
        },
      ],
    },
    {
      title: 'Лексика та хибні друзі',
      description: 'Ідіоми, номіналізація, підступні слова.',
      exercises: [
        {
          id: 'ex4v1',
          kind: 'mcq',
          prompt: 'Хибний друг',
          question: 'J’ignore son adresse.',
          options: ['Я ігнорую його адресу', 'Я не знаю його адреси'],
          answer: 1,
        },
        {
          id: 'ex4v2',
          kind: 'mcq',
          prompt: 'Хибний друг',
          question: 'Où acheter un livre ?',
          options: ['à la bibliothèque', 'à la librairie'],
          answer: 1,
          optionsAreFrench: true,
        },
        {
          id: 'ex4v3',
          kind: 'mcq',
          prompt: 'Ідіома',
          question: 'Il m’a posé un lapin.',
          options: ['Він не прийшов на зустріч', 'Він подарував кролика'],
          answer: 0,
        },
        {
          id: 'ex4v4',
          kind: 'mcq',
          prompt: 'Пастка',
          question: 'J’ai mal au cœur.',
          options: ['Болить серце', 'Нудить'],
          answer: 1,
        },
        {
          id: 'ex4v5',
          kind: 'type',
          prompt: 'Номіналізуй',
          question: 'augmenter → (іменник з артиклем)',
          answer: ["l'augmentation", 'laugmentation'],
        },
        {
          id: 'ex4v6',
          kind: 'cloze',
          prompt: 'Ідіома',
          sentence: 'Le voyage est long, mais ça ___ ___ ___.',
          answer: ['vaut le coup'],
          translation: 'Дорога довга, але воно того варте.',
        },
      ],
    },
    {
      title: 'Письмо та продукування',
      description: 'Ділові формули, есе, точний переклад.',
      exercises: [
        {
          id: 'ex4w1',
          kind: 'mcq',
          prompt: 'Email',
          question: 'Кінцівка ділового email',
          options: ['Bises,', 'Cordialement,'],
          answer: 1,
          optionsAreFrench: true,
        },
        {
          id: 'ex4w2',
          kind: 'cloze',
          prompt: 'Вкладення',
          sentence: 'Veuillez trouver ___ le document.',
          answer: ['ci-joint', 'ci joint'],
          translation: 'Додаю документ.',
        },
        {
          id: 'ex4w3',
          kind: 'translate',
          prompt: 'Переклади французькою',
          question: 'Пишу вам щодо вашого оголошення.',
          answer: ['je vous écris au sujet de votre annonce'],
        },
        {
          id: 'ex4w4',
          kind: 'translate',
          prompt: 'Переклади французькою',
          question: 'Хоч скільки я намагаюся, не працює.',
          answer: ["j'ai beau essayer, ça ne marche pas", "j'ai beau essayer ça ne marche pas"],
        },
        {
          id: 'ex4w5',
          kind: 'translate',
          prompt: 'Переклади французькою',
          question: 'Якби я знав, я б залишився.',
          answer: ["si j'avais su, je serais resté", "si j'avais su je serais resté"],
        },
        {
          id: 'ex4w6',
          kind: 'translate',
          prompt: 'Переклади французькою',
          question: 'Це саме те, що мені потрібно.',
          answer: ["c'est exactement ce dont j'ai besoin", "c'est ce dont j'ai besoin"],
        },
        {
          id: 'ex4w7',
          kind: 'dictation',
          prompt: 'Запиши почуте',
          text: 'Quelle que soit ta décision, je te soutiens.',
          translation: 'Хоч би яким було твоє рішення, я тебе підтримую.',
        },
        {
          id: 'ex4w8',
          kind: 'dictation',
          prompt: 'Запиши почуте',
          text: 'Certes, c’est difficile ; néanmoins, c’est possible.',
          translation: 'Звісно, це складно; проте можливо.',
        },
      ],
    },
  ],
}
