import { CORE_WORDS } from './core'
import type { CEFR, Word } from './types'

type Seed = Omit<Word, 'level' | 'tags'> & { level?: CEFR; tags?: string[] }

function pack(level: CEFR, tag: string, seeds: Seed[]): Word[] {
  return seeds.map((s) => ({ ...s, level: s.level ?? level, tags: [tag, ...(s.tags ?? [])] }))
}

/* ------------------------------------------------------------------ *
 * 1. Привітання та перші фрази
 * ------------------------------------------------------------------ */
const greetings = pack('A0', 'greetings', [
  {
    id: 'bonjour',
    fr: 'bonjour',
    uk: 'добрий день, привіт',
    ipa: 'bɔ̃.ʒuʁ',
    pos: 'interj',
    example: { fr: 'Bonjour, madame !', uk: 'Добрий день, пані!' },
    note: 'Універсальне вітання до вечора. Складається з bon (добрий) + jour (день).',
  },
  {
    id: 'bonsoir',
    fr: 'bonsoir',
    uk: 'добрий вечір',
    ipa: 'bɔ̃.swaʁ',
    pos: 'interj',
    example: { fr: 'Bonsoir, tout le monde !', uk: 'Добрий вечір усім!' },
  },
  {
    id: 'salut',
    fr: 'salut',
    uk: 'привіт, бувай',
    ipa: 'sa.ly',
    pos: 'interj',
    example: { fr: 'Salut, ça va ?', uk: 'Привіт, як справи?' },
    note: 'Тільки з друзями та ровесниками. Незнайомій людині — bonjour.',
  },
  {
    id: 'au_revoir',
    fr: 'au revoir',
    uk: 'до побачення',
    ipa: 'o ʁə.vwaʁ',
    pos: 'phrase',
    example: { fr: 'Au revoir et bonne journée !', uk: 'До побачення і гарного дня!' },
  },
  {
    id: 'a_bientot',
    fr: 'à bientôt',
    uk: 'до зустрічі, до скорого',
    ipa: 'a bjɛ̃.to',
    pos: 'phrase',
  },
  {
    id: 'a_demain',
    fr: 'à demain',
    uk: 'до завтра',
    ipa: 'a də.mɛ̃',
    pos: 'phrase',
  },
  {
    id: 'bonne_nuit',
    fr: 'bonne nuit',
    uk: 'на добраніч',
    ipa: 'bɔn nɥi',
    pos: 'phrase',
    note: 'Кажуть лише перед сном, не як прощання ввечері — для цього bonsoir.',
  },
  {
    id: 'merci',
    fr: 'merci',
    uk: 'дякую',
    ipa: 'mɛʁ.si',
    pos: 'interj',
    example: { fr: 'Merci beaucoup !', uk: 'Дуже дякую!' },
  },
  {
    id: 'de_rien',
    fr: 'de rien',
    uk: 'нема за що, будь ласка (у відповідь)',
    ipa: 'də ʁjɛ̃',
    pos: 'phrase',
  },
  {
    id: 'sil_vous_plait',
    fr: "s'il vous plaît",
    uk: 'будь ласка (ввічливо)',
    ipa: 'sil vu plɛ',
    pos: 'phrase',
    note: 'Дослівно «якщо вам це подобається». До друга — s’il te plaît.',
  },
  {
    id: 'pardon',
    fr: 'pardon',
    uk: 'перепрошую, вибачте',
    ipa: 'paʁ.dɔ̃',
    pos: 'interj',
  },
  {
    id: 'excusez_moi',
    fr: 'excusez-moi',
    uk: 'вибачте (щоб звернутися)',
    ipa: 'ɛks.ky.ze mwa',
    pos: 'phrase',
  },
  {
    id: 'oui',
    fr: 'oui',
    uk: 'так',
    ipa: 'wi',
    pos: 'adv',
  },
  {
    id: 'non',
    fr: 'non',
    uk: 'ні',
    ipa: 'nɔ̃',
    pos: 'adv',
  },
  {
    id: 'ca_va',
    fr: 'ça va',
    uk: 'все добре; як справи?',
    ipa: 'sa va',
    pos: 'phrase',
    note: 'Одна з найкорисніших фраз: працює і як питання, і як відповідь.',
  },
  {
    id: 'comment_ca_va',
    fr: 'Comment ça va ?',
    uk: 'Як справи?',
    ipa: 'kɔ.mɑ̃ sa va',
    pos: 'phrase',
  },
  {
    id: 'tres_bien',
    fr: 'très bien',
    uk: 'дуже добре',
    ipa: 'tʁɛ bjɛ̃',
    pos: 'phrase',
  },
  {
    id: 'comme_ci_comme_ca',
    fr: 'comme ci, comme ça',
    uk: 'так собі',
    ipa: 'kɔm si kɔm sa',
    pos: 'phrase',
  },
  {
    id: 'et_toi',
    fr: 'et toi ?',
    uk: 'а ти?',
    ipa: 'e twa',
    pos: 'phrase',
  },
  {
    id: 'je_mappelle',
    fr: "je m'appelle",
    uk: 'мене звати',
    ipa: 'ʒə ma.pɛl',
    pos: 'phrase',
    example: { fr: "Je m'appelle Maryna.", uk: 'Мене звати Марина.' },
    note: 'Дослівно «я себе називаю» — зворотне дієслово s’appeler.',
  },
  {
    id: 'enchante',
    fr: 'enchanté / enchantée',
    uk: 'дуже приємно (при знайомстві)',
    ipa: 'ɑ̃.ʃɑ̃.te',
    pos: 'adj',
    note: 'Жінка додає -e на письмі: enchantée. Вимова та сама.',
  },
  {
    id: 'madame',
    fr: 'madame',
    uk: 'пані',
    ipa: 'ma.dam',
    pos: 'n',
    gender: 'f',
  },
  {
    id: 'monsieur',
    fr: 'monsieur',
    uk: 'пан',
    ipa: 'mə.sjø',
    pos: 'n',
    gender: 'm',
    note: 'Вимовляється [мьосьє] — літери «n» не чути зовсім.',
  },
  {
    id: 'mademoiselle',
    fr: 'mademoiselle',
    uk: 'панночка',
    ipa: 'mad.mwa.zɛl',
    pos: 'n',
    gender: 'f',
  },
])

/* ------------------------------------------------------------------ *
 * 2. Хто я: країни, мови, професії
 * ------------------------------------------------------------------ */
const identity = pack('A1', 'identity', [
  {
    id: 'je',
    fr: 'je',
    uk: 'я',
    ipa: 'ʒə',
    pos: 'pron',
    note: 'У французькій підмет обов’язковий! «Йду» → Je vais, не просто Vais.',
  },
  { id: 'tu', fr: 'tu', uk: 'ти', ipa: 'ty', pos: 'pron' },
  { id: 'il', fr: 'il', uk: 'він', ipa: 'il', pos: 'pron' },
  { id: 'elle', fr: 'elle', uk: 'вона', ipa: 'ɛl', pos: 'pron' },
  { id: 'nous', fr: 'nous', uk: 'ми', ipa: 'nu', pos: 'pron' },
  {
    id: 'vous',
    fr: 'vous',
    uk: 'ви (ввічливо або множина)',
    ipa: 'vu',
    pos: 'pron',
    note: 'Так само як українське «Ви» — і ввічлива форма, і множина.',
  },
  { id: 'ils', fr: 'ils', uk: 'вони (ч. р. або змішано)', ipa: 'il', pos: 'pron' },
  { id: 'elles', fr: 'elles', uk: 'вони (усі жінки)', ipa: 'ɛl', pos: 'pron' },
  {
    id: 'etre',
    fr: 'être',
    uk: 'бути',
    ipa: 'ɛtʁ',
    pos: 'v',
    example: { fr: 'Je suis ukrainienne.', uk: 'Я українка.' },
    note: 'Не можна пропускати, як в українській: «Він лікар» → Il EST médecin.',
  },
  {
    id: 'avoir',
    fr: 'avoir',
    uk: 'мати',
    ipa: 'a.vwaʁ',
    pos: 'v',
    example: { fr: "J'ai deux frères.", uk: 'Я маю двох братів.' },
    note: 'Вік теж через avoir: J’ai 25 ans — дослівно «я маю 25 років».',
  },
  {
    id: 'sappeler',
    fr: "s'appeler",
    uk: 'зватися',
    ipa: 'sa.p(ə).le',
    pos: 'v',
  },
  {
    id: 'habiter',
    fr: 'habiter',
    uk: 'жити, мешкати',
    ipa: 'a.bi.te',
    pos: 'v',
    example: { fr: "J'habite à Kyiv.", uk: 'Я живу в Києві.' },
    note: 'H на початку не вимовляється: j’habite (а не je habite).',
  },
  {
    id: 'venir',
    fr: 'venir',
    uk: 'приходити, походити',
    ipa: 'və.niʁ',
    pos: 'v',
    example: { fr: "Je viens d'Ukraine.", uk: 'Я з України.' },
  },
  {
    id: 'parler',
    fr: 'parler',
    uk: 'говорити, розмовляти',
    ipa: 'paʁ.le',
    pos: 'v',
    example: { fr: 'Je parle un peu français.', uk: 'Я трохи говорю французькою.' },
  },
  {
    id: 'la_france',
    fr: 'la France',
    uk: 'Франція',
    ipa: 'la fʁɑ̃s',
    pos: 'n',
    gender: 'f',
    note: 'Назви країн мають артикль: la France, l’Ukraine, le Canada.',
  },
  { id: 'lukraine', fr: "l'Ukraine", uk: 'Україна', ipa: 'ly.kʁɛn', pos: 'n', gender: 'f' },
  { id: 'la_pologne', fr: 'la Pologne', uk: 'Польща', ipa: 'la pɔ.lɔɲ', pos: 'n', gender: 'f' },
  { id: 'lallemagne', fr: "l'Allemagne", uk: 'Німеччина', ipa: 'lal.maɲ', pos: 'n', gender: 'f' },
  { id: 'le_canada', fr: 'le Canada', uk: 'Канада', ipa: 'lə ka.na.da', pos: 'n', gender: 'm' },
  { id: 'lespagne', fr: "l'Espagne", uk: 'Іспанія', ipa: 'lɛs.paɲ', pos: 'n', gender: 'f' },
  { id: 'litalie', fr: "l'Italie", uk: 'Італія', ipa: 'li.ta.li', pos: 'n', gender: 'f' },
  {
    id: 'ukrainien',
    fr: 'ukrainien / ukrainienne',
    uk: 'українець / українка; українська мова',
    ipa: 'y.kʁɛ.njɛ̃ / y.kʁɛ.njɛn',
    pos: 'adj',
    note: 'Національності з малої літери: je suis ukrainien.',
  },
  {
    id: 'francais_adj',
    fr: 'français / française',
    uk: 'французький; француз / француженка',
    ipa: 'fʁɑ̃.sɛ / fʁɑ̃.sɛz',
    pos: 'adj',
  },
  {
    id: 'le_francais',
    fr: 'le français',
    uk: 'французька мова',
    ipa: 'lə fʁɑ̃.sɛ',
    pos: 'n',
    gender: 'm',
  },
  {
    id: 'langlais',
    fr: "l'anglais",
    uk: 'англійська мова',
    ipa: 'lɑ̃.ɡlɛ',
    pos: 'n',
    gender: 'm',
  },
  {
    id: 'le_travail',
    fr: 'le travail',
    uk: 'робота',
    ipa: 'lə tʁa.vaj',
    pos: 'n',
    gender: 'm',
  },
  {
    id: 'travailler',
    fr: 'travailler',
    uk: 'працювати',
    ipa: 'tʁa.va.je',
    pos: 'v',
    example: { fr: 'Je travaille dans un bureau.', uk: 'Я працюю в офісі.' },
  },
  {
    id: 'etudiant',
    fr: 'un étudiant / une étudiante',
    uk: 'студент / студентка',
    ipa: 'œ̃.n‿e.ty.djɑ̃',
    pos: 'n',
    gender: 'mf',
  },
  {
    id: 'professeur',
    fr: 'un professeur',
    uk: 'учитель, викладач',
    ipa: 'œ̃ pʁɔ.fɛ.sœʁ',
    pos: 'n',
    gender: 'm',
  },
  {
    id: 'medecin',
    fr: 'un médecin',
    uk: 'лікар',
    ipa: 'œ̃ med.sɛ̃',
    pos: 'n',
    gender: 'm',
    note: 'Завжди чоловічого роду, навіть про жінку: elle est médecin.',
  },
  {
    id: 'ingenieur',
    fr: 'un ingénieur',
    uk: 'інженер',
    ipa: 'œ̃.n‿ɛ̃.ʒe.njœʁ',
    pos: 'n',
    gender: 'm',
  },
  {
    id: 'un_ami',
    fr: 'un ami / une amie',
    uk: 'друг / подруга',
    ipa: 'œ̃.n‿a.mi',
    pos: 'n',
    gender: 'mf',
  },
])

/* ------------------------------------------------------------------ *
 * 3. Числа, час, дати
 * ------------------------------------------------------------------ */
const numbers = pack('A0', 'numbers', [
  { id: 'zero', fr: 'zéro', uk: 'нуль', ipa: 'ze.ʁo', pos: 'num' },
  { id: 'un_num', fr: 'un', uk: 'один', ipa: 'œ̃', pos: 'num' },
  { id: 'deux', fr: 'deux', uk: 'два', ipa: 'dø', pos: 'num' },
  { id: 'trois', fr: 'trois', uk: 'три', ipa: 'tʁwɑ', pos: 'num' },
  { id: 'quatre', fr: 'quatre', uk: 'чотири', ipa: 'katʁ', pos: 'num' },
  { id: 'cinq', fr: 'cinq', uk: "п'ять", ipa: 'sɛ̃k', pos: 'num' },
  { id: 'six', fr: 'six', uk: 'шість', ipa: 'sis', pos: 'num' },
  { id: 'sept', fr: 'sept', uk: 'сім', ipa: 'sɛt', pos: 'num', note: 'P не вимовляється.' },
  { id: 'huit', fr: 'huit', uk: 'вісім', ipa: 'ɥit', pos: 'num' },
  { id: 'neuf', fr: 'neuf', uk: "дев'ять", ipa: 'nœf', pos: 'num' },
  { id: 'dix', fr: 'dix', uk: 'десять', ipa: 'dis', pos: 'num' },
  { id: 'onze', fr: 'onze', uk: 'одинадцять', ipa: 'ɔ̃z', pos: 'num' },
  { id: 'douze', fr: 'douze', uk: 'дванадцять', ipa: 'duz', pos: 'num' },
  { id: 'treize', fr: 'treize', uk: 'тринадцять', ipa: 'tʁɛz', pos: 'num' },
  { id: 'quatorze', fr: 'quatorze', uk: 'чотирнадцять', ipa: 'ka.tɔʁz', pos: 'num' },
  { id: 'quinze', fr: 'quinze', uk: "п'ятнадцять", ipa: 'kɛ̃z', pos: 'num' },
  { id: 'seize', fr: 'seize', uk: 'шістнадцять', ipa: 'sɛz', pos: 'num' },
  { id: 'dix_sept', fr: 'dix-sept', uk: 'сімнадцять', ipa: 'di.sɛt', pos: 'num' },
  { id: 'dix_huit', fr: 'dix-huit', uk: 'вісімнадцять', ipa: 'di.zɥit', pos: 'num' },
  { id: 'dix_neuf', fr: 'dix-neuf', uk: "дев'ятнадцять", ipa: 'diz.nœf', pos: 'num' },
  { id: 'vingt', fr: 'vingt', uk: 'двадцять', ipa: 'vɛ̃', pos: 'num' },
  { id: 'trente', fr: 'trente', uk: 'тридцять', ipa: 'tʁɑ̃t', pos: 'num' },
  { id: 'quarante', fr: 'quarante', uk: 'сорок', ipa: 'ka.ʁɑ̃t', pos: 'num' },
  { id: 'cinquante', fr: 'cinquante', uk: "п'ятдесят", ipa: 'sɛ̃.kɑ̃t', pos: 'num' },
  { id: 'soixante', fr: 'soixante', uk: 'шістдесят', ipa: 'swa.sɑ̃t', pos: 'num' },
  {
    id: 'soixante_dix',
    fr: 'soixante-dix',
    uk: 'сімдесят',
    ipa: 'swa.sɑ̃t.dis',
    pos: 'num',
    note: 'Дослівно «шістдесят-десять». Французи рахують двадцятками!',
  },
  {
    id: 'quatre_vingts',
    fr: 'quatre-vingts',
    uk: 'вісімдесят',
    ipa: 'ka.tʁə.vɛ̃',
    pos: 'num',
    note: 'Дослівно «чотири по двадцять» = 4 × 20.',
  },
  {
    id: 'quatre_vingt_dix',
    fr: 'quatre-vingt-dix',
    uk: "дев'яносто",
    ipa: 'ka.tʁə.vɛ̃.dis',
    pos: 'num',
    note: '4 × 20 + 10. У Бельгії та Швейцарії простіше: nonante.',
  },
  { id: 'cent', fr: 'cent', uk: 'сто', ipa: 'sɑ̃', pos: 'num' },
  { id: 'mille', fr: 'mille', uk: 'тисяча', ipa: 'mil', pos: 'num' },
  {
    id: 'lheure',
    fr: "l'heure",
    uk: 'година; час',
    ipa: 'lœʁ',
    gender: 'f',
    pos: 'n',
    example: { fr: 'Quelle heure est-il ?', uk: 'Котра година?' },
  },
  { id: 'la_minute', fr: 'la minute', uk: 'хвилина', ipa: 'la mi.nyt', gender: 'f', pos: 'n' },
  {
    id: 'le_jour',
    fr: 'le jour',
    uk: 'день',
    ipa: 'lə ʒuʁ',
    gender: 'm',
    pos: 'n',
    note: 'Увага: «день» у нас чол. рід і le jour теж — але la journée (доба, цілий день) жіночий.',
  },
  { id: 'la_semaine', fr: 'la semaine', uk: 'тиждень', ipa: 'la sə.mɛn', gender: 'f', pos: 'n' },
  {
    id: 'le_mois',
    fr: 'le mois',
    uk: 'місяць (календарний)',
    ipa: 'lə mwa',
    gender: 'm',
    pos: 'n',
  },
  { id: 'lannee', fr: "l'année", uk: 'рік', ipa: 'la.ne', gender: 'f', pos: 'n' },
  {
    id: 'aujourdhui',
    fr: "aujourd'hui",
    uk: 'сьогодні',
    ipa: 'o.ʒuʁ.dɥi',
    pos: 'adv',
  },
  { id: 'demain', fr: 'demain', uk: 'завтра', ipa: 'də.mɛ̃', pos: 'adv' },
  { id: 'hier', fr: 'hier', uk: 'вчора', ipa: 'jɛʁ', pos: 'adv' },
  { id: 'maintenant', fr: 'maintenant', uk: 'зараз', ipa: 'mɛ̃t.nɑ̃', pos: 'adv' },
  { id: 'lundi', fr: 'lundi', uk: 'понеділок', ipa: 'lœ̃.di', pos: 'n', gender: 'm' },
  { id: 'mardi', fr: 'mardi', uk: 'вівторок', ipa: 'maʁ.di', pos: 'n', gender: 'm' },
  { id: 'mercredi', fr: 'mercredi', uk: 'середа', ipa: 'mɛʁ.kʁə.di', pos: 'n', gender: 'm' },
  { id: 'jeudi', fr: 'jeudi', uk: 'четвер', ipa: 'ʒø.di', pos: 'n', gender: 'm' },
  { id: 'vendredi', fr: 'vendredi', uk: "п'ятниця", ipa: 'vɑ̃.dʁə.di', pos: 'n', gender: 'm' },
  {
    id: 'samedi',
    fr: 'samedi',
    uk: 'субота',
    ipa: 'sam.di',
    pos: 'n',
    gender: 'm',
    note: 'Усі дні тижня — чоловічого роду, навіть «субота» і «середа».',
  },
  { id: 'dimanche', fr: 'dimanche', uk: 'неділя', ipa: 'di.mɑ̃ʃ', pos: 'n', gender: 'm' },
])

/* ------------------------------------------------------------------ *
 * 4. Артиклі та рід — базові іменники
 * ------------------------------------------------------------------ */
const genderNouns = pack('A1', 'gender', [
  {
    id: 'le_livre',
    fr: 'le livre',
    uk: 'книга',
    ipa: 'lə livʁ',
    gender: 'm',
    pos: 'n',
    note: '⚠️ У французькій ЧОЛОВІЧИЙ, а українська «книга» — жіночий. Вчи разом з артиклем!',
  },
  {
    id: 'la_table',
    fr: 'la table',
    uk: 'стіл',
    ipa: 'la tabl',
    gender: 'f',
    pos: 'n',
    note: '⚠️ ЖІНОЧИЙ рід, тоді як український «стіл» — чоловічий.',
  },
  {
    id: 'la_chaise',
    fr: 'la chaise',
    uk: 'стілець',
    ipa: 'la ʃɛz',
    gender: 'f',
    pos: 'n',
    note: '⚠️ Теж жіночий, на відміну від українського «стілець».',
  },
  {
    id: 'le_stylo',
    fr: 'le stylo',
    uk: 'ручка',
    ipa: 'lə sti.lo',
    gender: 'm',
    pos: 'n',
    note: '⚠️ Чоловічий, а наша «ручка» — жіночий.',
  },
  { id: 'la_porte', fr: 'la porte', uk: 'двері', ipa: 'la pɔʁt', gender: 'f', pos: 'n' },
  {
    id: 'la_fenetre',
    fr: 'la fenêtre',
    uk: 'вікно',
    ipa: 'la fə.nɛtʁ',
    gender: 'f',
    pos: 'n',
    note: '⚠️ Жіночий, тоді як «вікно» в нас середнього роду — а середнього у французькій немає взагалі.',
  },
  {
    id: 'le_telephone',
    fr: 'le téléphone',
    uk: 'телефон',
    ipa: 'lə te.le.fɔn',
    gender: 'm',
    pos: 'n',
  },
  {
    id: 'lordinateur',
    fr: "l'ordinateur",
    uk: "комп'ютер",
    ipa: 'lɔʁ.di.na.tœʁ',
    gender: 'm',
    pos: 'n',
  },
  {
    id: 'la_voiture',
    fr: 'la voiture',
    uk: 'машина, автомобіль',
    ipa: 'la vwa.tyʁ',
    gender: 'f',
    pos: 'n',
  },
  { id: 'la_maison', fr: 'la maison', uk: 'дім, будинок', ipa: 'la mɛ.zɔ̃', gender: 'f', pos: 'n' },
  {
    id: 'leau',
    fr: "l'eau",
    uk: 'вода',
    ipa: 'lo',
    gender: 'f',
    pos: 'n',
    note: 'Жіночий, але артикль скорочується перед голосною, тож рід «не видно»: l’eau.',
  },
  { id: 'le_chat', fr: 'le chat', uk: 'кіт', ipa: 'lə ʃa', gender: 'm', pos: 'n' },
  { id: 'le_chien', fr: 'le chien', uk: 'пес, собака', ipa: 'lə ʃjɛ̃', gender: 'm', pos: 'n' },
  {
    id: 'la_ville',
    fr: 'la ville',
    uk: 'місто',
    ipa: 'la vil',
    gender: 'f',
    pos: 'n',
    note: 'Ll тут читається як звичайне [l], а не [j].',
  },
  { id: 'le_pays', fr: 'le pays', uk: 'країна', ipa: 'lə pe.i', gender: 'm', pos: 'n' },
  { id: 'la_rue', fr: 'la rue', uk: 'вулиця', ipa: 'la ʁy', gender: 'f', pos: 'n' },
  { id: 'lecole', fr: "l'école", uk: 'школа', ipa: 'le.kɔl', gender: 'f', pos: 'n' },
  { id: 'le_mot', fr: 'le mot', uk: 'слово', ipa: 'lə mo', gender: 'm', pos: 'n' },
  { id: 'la_langue', fr: 'la langue', uk: 'мова; язик', ipa: 'la lɑ̃ɡ', gender: 'f', pos: 'n' },
  { id: 'la_question', fr: 'la question', uk: 'питання', ipa: 'la kɛs.tjɔ̃', gender: 'f', pos: 'n' },
])

/* ------------------------------------------------------------------ *
 * 5. Родина і дім
 * ------------------------------------------------------------------ */
const family = pack('A1', 'family', [
  {
    id: 'la_famille',
    fr: 'la famille',
    uk: 'родина, сім’я',
    ipa: 'la fa.mij',
    gender: 'f',
    pos: 'n',
  },
  { id: 'la_mere', fr: 'la mère', uk: 'мати', ipa: 'la mɛʁ', gender: 'f', pos: 'n' },
  { id: 'le_pere', fr: 'le père', uk: 'батько', ipa: 'lə pɛʁ', gender: 'm', pos: 'n' },
  { id: 'les_parents', fr: 'les parents', uk: 'батьки', ipa: 'le pa.ʁɑ̃', pos: 'n' },
  { id: 'le_frere', fr: 'le frère', uk: 'брат', ipa: 'lə fʁɛʁ', gender: 'm', pos: 'n' },
  { id: 'la_soeur', fr: 'la sœur', uk: 'сестра', ipa: 'la sœʁ', gender: 'f', pos: 'n' },
  {
    id: 'le_fils',
    fr: 'le fils',
    uk: 'син',
    ipa: 'lə fis',
    gender: 'm',
    pos: 'n',
    note: 'Читається [фіс], L німе.',
  },
  { id: 'la_fille', fr: 'la fille', uk: 'дочка; дівчина', ipa: 'la fij', gender: 'f', pos: 'n' },
  { id: 'le_mari', fr: 'le mari', uk: 'чоловік (у шлюбі)', ipa: 'lə ma.ʁi', gender: 'm', pos: 'n' },
  {
    id: 'la_femme',
    fr: 'la femme',
    uk: 'жінка; дружина',
    ipa: 'la fam',
    gender: 'f',
    pos: 'n',
    note: 'Виняток: femme читається [фам], а не [фем].',
  },
  {
    id: 'lenfant',
    fr: "l'enfant",
    uk: 'дитина',
    ipa: 'lɑ̃.fɑ̃',
    pos: 'n',
    gender: 'mf',
    note: 'Спільного роду: un enfant (хлопчик) і une enfant (дівчинка).',
  },
  {
    id: 'la_grand_mere',
    fr: 'la grand-mère',
    uk: 'бабуся',
    ipa: 'la ɡʁɑ̃.mɛʁ',
    gender: 'f',
    pos: 'n',
  },
  {
    id: 'le_grand_pere',
    fr: 'le grand-père',
    uk: 'дідусь',
    ipa: 'lə ɡʁɑ̃.pɛʁ',
    gender: 'm',
    pos: 'n',
  },
  {
    id: 'mon',
    fr: 'mon / ma / mes',
    uk: 'мій / моя / мої',
    ipa: 'mɔ̃ / ma / me',
    pos: 'adj',
    note: 'Рід залежить від ПРЕДМЕТА, не від власника: ma sœur, mon frère.',
  },
  { id: 'ton', fr: 'ton / ta / tes', uk: 'твій / твоя / твої', ipa: 'tɔ̃ / ta / te', pos: 'adj' },
  {
    id: 'son',
    fr: 'son / sa / ses',
    uk: 'його / її',
    ipa: 'sɔ̃ / sa / se',
    pos: 'adj',
    note: '⚠️ son livre = і «його книга», і «її книга». Стать власника не видно!',
  },
  {
    id: 'lappartement',
    fr: "l'appartement",
    uk: 'квартира',
    ipa: 'la.paʁ.tə.mɑ̃',
    gender: 'm',
    pos: 'n',
  },
  {
    id: 'la_chambre',
    fr: 'la chambre',
    uk: 'кімната, спальня',
    ipa: 'la ʃɑ̃bʁ',
    gender: 'f',
    pos: 'n',
  },
  {
    id: 'la_cuisine',
    fr: 'la cuisine',
    uk: 'кухня; кулінарія',
    ipa: 'la kɥi.zin',
    gender: 'f',
    pos: 'n',
  },
  {
    id: 'la_salle_de_bains',
    fr: 'la salle de bains',
    uk: 'ванна кімната',
    ipa: 'la sal də bɛ̃',
    gender: 'f',
    pos: 'n',
  },
  { id: 'le_lit', fr: 'le lit', uk: 'ліжко', ipa: 'lə li', gender: 'm', pos: 'n' },
  {
    id: 'il_y_a',
    fr: 'il y a',
    uk: 'є, існує (там є)',
    ipa: 'i.lja',
    pos: 'phrase',
    note: 'Незмінна конструкція: il y a un chat / il y a des chats.',
  },
  { id: 'grand', fr: 'grand / grande', uk: 'великий, високий', ipa: 'ɡʁɑ̃ / ɡʁɑ̃d', pos: 'adj' },
  { id: 'petit', fr: 'petit / petite', uk: 'маленький', ipa: 'p(ə)ti / p(ə)tit', pos: 'adj' },
  { id: 'beau', fr: 'beau / belle', uk: 'гарний, красивий', ipa: 'bo / bɛl', pos: 'adj' },
  { id: 'nouveau', fr: 'nouveau / nouvelle', uk: 'новий', ipa: 'nu.vo / nu.vɛl', pos: 'adj' },
])

/* ------------------------------------------------------------------ *
 * 6. Щоденні справи — дієслова
 * ------------------------------------------------------------------ */
const daily = pack('A1', 'daily', [
  {
    id: 'aimer',
    fr: 'aimer',
    uk: 'любити, подобатися',
    ipa: 'e.me',
    pos: 'v',
    example: { fr: "J'aime le café.", uk: 'Я люблю каву.' },
  },
  { id: 'regarder', fr: 'regarder', uk: 'дивитися', ipa: 'ʁə.ɡaʁ.de', pos: 'v' },
  { id: 'ecouter', fr: 'écouter', uk: 'слухати', ipa: 'e.ku.te', pos: 'v' },
  { id: 'manger', fr: 'manger', uk: 'їсти', ipa: 'mɑ̃.ʒe', pos: 'v' },
  { id: 'boire', fr: 'boire', uk: 'пити', ipa: 'bwaʁ', pos: 'v' },
  {
    id: 'faire',
    fr: 'faire',
    uk: 'робити',
    ipa: 'fɛʁ',
    pos: 'v',
    note: 'Найуніверсальніше дієслово: faire du sport, faire la cuisine.',
  },
  { id: 'aller', fr: 'aller', uk: 'йти, їхати', ipa: 'a.le', pos: 'v' },
  { id: 'lire', fr: 'lire', uk: 'читати', ipa: 'liʁ', pos: 'v' },
  { id: 'ecrire', fr: 'écrire', uk: 'писати', ipa: 'e.kʁiʁ', pos: 'v' },
  { id: 'comprendre', fr: 'comprendre', uk: 'розуміти', ipa: 'kɔ̃.pʁɑ̃dʁ', pos: 'v' },
  { id: 'vouloir', fr: 'vouloir', uk: 'хотіти', ipa: 'vu.lwaʁ', pos: 'v' },
  { id: 'pouvoir', fr: 'pouvoir', uk: 'могти', ipa: 'pu.vwaʁ', pos: 'v' },
  { id: 'savoir', fr: 'savoir', uk: 'знати (факт, уміти)', ipa: 'sa.vwaʁ', pos: 'v' },
  { id: 'se_lever', fr: 'se lever', uk: 'вставати, підійматися', ipa: 'sə lə.ve', pos: 'v' },
  { id: 'dormir', fr: 'dormir', uk: 'спати', ipa: 'dɔʁ.miʁ', pos: 'v' },
  { id: 'le_matin', fr: 'le matin', uk: 'ранок; вранці', ipa: 'lə ma.tɛ̃', gender: 'm', pos: 'n' },
  {
    id: 'lapres_midi',
    fr: "l'après-midi",
    uk: 'після обіду',
    ipa: 'la.pʁɛ.mi.di',
    gender: 'm',
    pos: 'n',
  },
  { id: 'le_soir', fr: 'le soir', uk: 'вечір; ввечері', ipa: 'lə swaʁ', gender: 'm', pos: 'n' },
  { id: 'toujours', fr: 'toujours', uk: 'завжди', ipa: 'tu.ʒuʁ', pos: 'adv' },
  { id: 'souvent', fr: 'souvent', uk: 'часто', ipa: 'su.vɑ̃', pos: 'adv' },
  {
    id: 'jamais',
    fr: 'ne… jamais',
    uk: 'ніколи',
    ipa: 'nə… ʒa.mɛ',
    pos: 'adv',
    note: 'Як і ne…pas, обіймає дієслово з двох боків: Je ne fume jamais.',
  },
  { id: 'un_peu', fr: 'un peu', uk: 'трохи', ipa: 'œ̃ pø', pos: 'adv' },
  { id: 'beaucoup', fr: 'beaucoup', uk: 'багато, дуже', ipa: 'bo.ku', pos: 'adv' },
  { id: 'pourquoi', fr: 'pourquoi', uk: 'чому', ipa: 'puʁ.kwa', pos: 'adv' },
  { id: 'parce_que', fr: 'parce que', uk: 'тому що', ipa: 'paʁs kə', pos: 'conj' },
  {
    id: 'est_ce_que',
    fr: 'est-ce que',
    uk: '(частка для питання)',
    ipa: 'ɛs kə',
    pos: 'phrase',
    note: 'Ставиш на початок — і твердження стає питанням. Українською не перекладається.',
  },
  { id: 'quand', fr: 'quand', uk: 'коли', ipa: 'kɑ̃', pos: 'adv' },
  {
    id: 'ou',
    fr: 'où',
    uk: 'де, куди',
    ipa: 'u',
    pos: 'adv',
    note: 'où (де) з наголосом ≠ ou (або) без нього.',
  },
  { id: 'comment', fr: 'comment', uk: 'як', ipa: 'kɔ.mɑ̃', pos: 'adv' },
])

/* ------------------------------------------------------------------ *
 * 7. Їжа та кафе
 * ------------------------------------------------------------------ */
const food = pack('A1', 'food', [
  { id: 'le_pain', fr: 'le pain', uk: 'хліб', ipa: 'lə pɛ̃', gender: 'm', pos: 'n' },
  { id: 'le_fromage', fr: 'le fromage', uk: 'сир', ipa: 'lə fʁɔ.maʒ', gender: 'm', pos: 'n' },
  { id: 'le_cafe', fr: 'le café', uk: 'кава; кафе', ipa: 'lə ka.fe', gender: 'm', pos: 'n' },
  { id: 'le_the', fr: 'le thé', uk: 'чай', ipa: 'lə te', gender: 'm', pos: 'n' },
  { id: 'le_vin', fr: 'le vin', uk: 'вино', ipa: 'lə vɛ̃', gender: 'm', pos: 'n' },
  {
    id: 'la_pomme',
    fr: 'la pomme',
    uk: 'яблуко',
    ipa: 'la pɔm',
    gender: 'f',
    pos: 'n',
    note: '⚠️ Жіночий рід, хоча «яблуко» в нас середній.',
  },
  { id: 'le_poulet', fr: 'le poulet', uk: 'курка (м’ясо)', ipa: 'lə pu.lɛ', gender: 'm', pos: 'n' },
  {
    id: 'le_poisson',
    fr: 'le poisson',
    uk: 'риба',
    ipa: 'lə pwa.sɔ̃',
    gender: 'm',
    pos: 'n',
    note: '⚠️ Чоловічий, а «риба» в нас жіночий. Не плутай з le poison — отрута!',
  },
  { id: 'la_viande', fr: 'la viande', uk: "м'ясо", ipa: 'la vjɑ̃d', gender: 'f', pos: 'n' },
  { id: 'les_legumes', fr: 'les légumes', uk: 'овочі', ipa: 'le le.ɡym', pos: 'n' },
  { id: 'le_sucre', fr: 'le sucre', uk: 'цукор', ipa: 'lə sykʁ', gender: 'm', pos: 'n' },
  { id: 'le_lait', fr: 'le lait', uk: 'молоко', ipa: 'lə lɛ', gender: 'm', pos: 'n' },
  {
    id: 'le_petit_dejeuner',
    fr: 'le petit-déjeuner',
    uk: 'сніданок',
    ipa: 'lə p(ə)ti de.ʒø.ne',
    gender: 'm',
    pos: 'n',
  },
  { id: 'le_dejeuner', fr: 'le déjeuner', uk: 'обід', ipa: 'lə de.ʒø.ne', gender: 'm', pos: 'n' },
  { id: 'le_diner', fr: 'le dîner', uk: 'вечеря', ipa: 'lə di.ne', gender: 'm', pos: 'n' },
  {
    id: 'le_restaurant',
    fr: 'le restaurant',
    uk: 'ресторан',
    ipa: 'lə ʁɛs.tɔ.ʁɑ̃',
    gender: 'm',
    pos: 'n',
  },
  {
    id: 'laddition',
    fr: "l'addition",
    uk: 'рахунок (у кафе)',
    ipa: 'la.di.sjɔ̃',
    gender: 'f',
    pos: 'n',
    example: { fr: "L'addition, s'il vous plaît !", uk: 'Рахунок, будь ласка!' },
  },
  {
    id: 'je_voudrais',
    fr: 'je voudrais',
    uk: 'я хотів би, мені б хотілося',
    ipa: 'ʒə vu.dʁɛ',
    pos: 'phrase',
    note: 'Ввічлива форма замість je veux («я хочу» звучить надто прямо).',
  },
  { id: 'la_carte', fr: 'la carte', uk: 'меню; картка', ipa: 'la kaʁt', gender: 'f', pos: 'n' },
  {
    id: 'du',
    fr: 'du / de la / des',
    uk: '(частковий артикль — «трохи, якась кількість»)',
    ipa: 'dy / də la / de',
    pos: 'prep',
    note: 'В українській відповідника немає: «Я їм хліб» → Je mange DU pain.',
  },
  { id: 'delicieux', fr: 'délicieux / délicieuse', uk: 'смачний', ipa: 'de.li.sjø', pos: 'adj' },
  {
    id: 'avoir_faim',
    fr: 'avoir faim',
    uk: 'бути голодним',
    ipa: 'a.vwaʁ fɛ̃',
    pos: 'phrase',
    note: 'Дослівно «мати голод»: J’ai faim, а не «Je suis faim».',
  },
  { id: 'avoir_soif', fr: 'avoir soif', uk: 'хотіти пити', ipa: 'a.vwaʁ swaf', pos: 'phrase' },
])

/* ------------------------------------------------------------------ *
 * 8. Місто й напрямки
 * ------------------------------------------------------------------ */
const city = pack('A1', 'city', [
  { id: 'la_gare', fr: 'la gare', uk: 'вокзал', ipa: 'la ɡaʁ', gender: 'f', pos: 'n' },
  {
    id: 'la_boulangerie',
    fr: 'la boulangerie',
    uk: 'пекарня, булочна',
    ipa: 'la bu.lɑ̃ʒ.ʁi',
    gender: 'f',
    pos: 'n',
  },
  { id: 'le_magasin', fr: 'le magasin', uk: 'магазин', ipa: 'lə ma.ɡa.zɛ̃', gender: 'm', pos: 'n' },
  {
    id: 'la_pharmacie',
    fr: 'la pharmacie',
    uk: 'аптека',
    ipa: 'la faʁ.ma.si',
    gender: 'f',
    pos: 'n',
  },
  { id: 'lhopital', fr: "l'hôpital", uk: 'лікарня', ipa: 'lɔ.pi.tal', gender: 'm', pos: 'n' },
  {
    id: 'le_musee',
    fr: 'le musée',
    uk: 'музей',
    ipa: 'lə my.ze',
    gender: 'm',
    pos: 'n',
    note: 'Виняток: закінчується на -ée, але чоловічого роду.',
  },
  { id: 'le_parc', fr: 'le parc', uk: 'парк', ipa: 'lə paʁk', gender: 'm', pos: 'n' },
  { id: 'la_place', fr: 'la place', uk: 'площа; місце', ipa: 'la plas', gender: 'f', pos: 'n' },
  { id: 'le_metro', fr: 'le métro', uk: 'метро', ipa: 'lə me.tʁo', gender: 'm', pos: 'n' },
  { id: 'le_bus', fr: 'le bus', uk: 'автобус', ipa: 'lə bys', gender: 'm', pos: 'n' },
  { id: 'le_train', fr: 'le train', uk: 'потяг', ipa: 'lə tʁɛ̃', gender: 'm', pos: 'n' },
  { id: 'a_gauche', fr: 'à gauche', uk: 'ліворуч', ipa: 'a ɡoʃ', pos: 'phrase' },
  { id: 'a_droite', fr: 'à droite', uk: 'праворуч', ipa: 'a dʁwat', pos: 'phrase' },
  {
    id: 'tout_droit',
    fr: 'tout droit',
    uk: 'прямо',
    ipa: 'tu dʁwa',
    pos: 'phrase',
    note: '⚠️ Не плутай: à droite = праворуч, tout droit = прямо.',
  },
  { id: 'a_cote_de', fr: 'à côté de', uk: 'поруч з, біля', ipa: 'a ko.te də', pos: 'prep' },
  { id: 'en_face_de', fr: 'en face de', uk: 'навпроти', ipa: 'ɑ̃ fas də', pos: 'prep' },
  { id: 'pres_de', fr: 'près de', uk: 'близько до', ipa: 'pʁɛ də', pos: 'prep' },
  { id: 'loin_de', fr: 'loin de', uk: 'далеко від', ipa: 'lwɛ̃ də', pos: 'prep' },
  { id: 'dans', fr: 'dans', uk: 'у, всередині', ipa: 'dɑ̃', pos: 'prep' },
  { id: 'sur', fr: 'sur', uk: 'на', ipa: 'syʁ', pos: 'prep' },
  { id: 'sous', fr: 'sous', uk: 'під', ipa: 'su', pos: 'prep' },
  { id: 'entre', fr: 'entre', uk: 'між', ipa: 'ɑ̃tʁ', pos: 'prep' },
  {
    id: 'prendre',
    fr: 'prendre',
    uk: 'брати; їхати (транспортом)',
    ipa: 'pʁɑ̃dʁ',
    pos: 'v',
    example: { fr: 'Je prends le métro.', uk: 'Я їду метро.' },
  },
  { id: 'tourner', fr: 'tourner', uk: 'повертати', ipa: 'tuʁ.ne', pos: 'v' },
  {
    id: 'au',
    fr: 'au / à la / aux',
    uk: 'до, в (напрямок)',
    ipa: 'o / a la / o',
    pos: 'prep',
    note: 'à + le = au (не «à le»!), à + les = aux.',
  },
  { id: 'ou_est', fr: 'Où est… ?', uk: 'Де знаходиться…?', ipa: 'u ɛ', pos: 'phrase' },
])

/* ------------------------------------------------------------------ *
 * 9. Думка та аргументація (A2→B1)
 * ------------------------------------------------------------------ */
const opinion = pack('B1', 'opinion', [
  {
    id: 'paraitre',
    fr: 'paraître',
    uk: 'здаватися, виглядати',
    ipa: 'pa.ʁɛtʁ',
    pos: 'v',
    note: '«Il paraît que…» — «кажуть, що…», дуже вживаний зворот.',
  },
  {
    id: 'sagir',
    fr: "il s'agit de",
    uk: 'ідеться про',
    ipa: 'il sa.ʒi də',
    pos: 'phrase',
    note: 'Тільки безособово. «De quoi s’agit-il ?» — «Про що йдеться?»',
  },
  {
    id: 'avoir_impression',
    fr: "avoir l'impression que",
    uk: 'мати враження, що',
    ipa: 'a.vwaʁ lɛ̃.pʁe.sjɔ̃ kə',
    pos: 'phrase',
  },
  {
    id: 'se_rendre_compte',
    fr: 'se rendre compte de',
    uk: 'усвідомлювати',
    ipa: 'sə ʁɑ̃dʁ kɔ̃t də',
    pos: 'v',
  },
  { id: 'supposer', fr: 'supposer', uk: 'припускати', ipa: 'sy.po.ze', pos: 'v' },
  { id: 'prevoir', fr: 'prévoir', uk: 'передбачати, планувати', ipa: 'pʁe.vwaʁ', pos: 'v' },
  { id: 'affirmer', fr: 'affirmer', uk: 'стверджувати', ipa: 'a.fiʁ.me', pos: 'v' },
  { id: 'declarer', fr: 'déclarer', uk: 'заявляти', ipa: 'de.kla.ʁe', pos: 'v' },
  { id: 'preciser', fr: 'préciser', uk: 'уточнювати', ipa: 'pʁe.si.ze', pos: 'v' },
  { id: 'souligner', fr: 'souligner', uk: 'підкреслювати', ipa: 'su.li.ɲe', pos: 'v' },
  { id: 'insister', fr: 'insister', uk: 'наполягати', ipa: 'ɛ̃.sis.te', pos: 'v' },
  { id: 'admettre', fr: 'admettre', uk: 'визнавати, допускати', ipa: 'ad.mɛtʁ', pos: 'v' },
  { id: 'nier', fr: 'nier', uk: 'заперечувати', ipa: 'nje', pos: 'v' },
  { id: 'convaincre', fr: 'convaincre', uk: 'переконувати', ipa: 'kɔ̃.vɛ̃kʁ', pos: 'v' },
  { id: 'juger', fr: 'juger', uk: 'судити, оцінювати', ipa: 'ʒy.ʒe', pos: 'v' },
  { id: 'critiquer', fr: 'critiquer', uk: 'критикувати', ipa: 'kʁi.ti.ke', pos: 'v' },
  { id: 'soutenir', fr: 'soutenir', uk: 'підтримувати', ipa: 'sut.niʁ', pos: 'v' },
  {
    id: 'sopposer',
    fr: "s'opposer à",
    uk: 'заперечувати проти, бути проти',
    ipa: 'sɔ.po.ze a',
    pos: 'v',
  },
  {
    id: 'avoir_tort',
    fr: 'avoir tort',
    uk: 'помилятися, бути неправим',
    ipa: 'a.vwaʁ tɔʁ',
    pos: 'phrase',
    note: 'Пара до «avoir raison». Обидва через avoir, а не être.',
  },
  { id: 'dapres', fr: "d'après", uk: 'за словами, згідно з', ipa: 'da.pʁɛ', pos: 'prep' },
  {
    id: 'grace_a',
    fr: 'grâce à',
    uk: 'завдяки',
    ipa: 'ɡʁɑs a',
    pos: 'prep',
    note: '⚠️ grâce à — про хороше, à cause de — про погане. Українське «через» покриває обидва.',
  },
  { id: 'a_cause_de', fr: 'à cause de', uk: 'через (щось погане)', ipa: 'a koz də', pos: 'prep' },
  { id: 'afin_de', fr: 'afin de', uk: 'щоб, задля', ipa: 'a.fɛ̃ də', pos: 'conj' },
  {
    id: 'pour_que',
    fr: 'pour que',
    uk: 'щоб (з новим підметом)',
    ipa: 'puʁ kə',
    pos: 'conj',
    note: 'Тягне за собою subjonctif: «pour que tu comprennes».',
  },
  {
    id: 'bien_que',
    fr: 'bien que',
    uk: 'хоча',
    ipa: 'bjɛ̃ kə',
    pos: 'conj',
    note: 'Теж вимагає subjonctif: «bien qu’il soit tard».',
  },
  {
    id: 'meme_si',
    fr: 'même si',
    uk: 'навіть якщо',
    ipa: 'mɛm si',
    pos: 'conj',
    note: 'На відміну від bien que, після «même si» subjonctif НЕ вживається.',
  },
  { id: 'tandis_que', fr: 'tandis que', uk: 'тоді як, у той час як', ipa: 'tɑ̃.di kə', pos: 'conj' },
  {
    id: 'alors_que',
    fr: 'alors que',
    uk: 'тоді як (протиставлення)',
    ipa: 'a.lɔʁ kə',
    pos: 'conj',
  },
  { id: 'sinon', fr: 'sinon', uk: 'інакше, а то', ipa: 'si.nɔ̃', pos: 'conj' },
  { id: 'en_revanche', fr: 'en revanche', uk: 'натомість, зате', ipa: 'ɑ̃ ʁə.vɑ̃ʃ', pos: 'adv' },
  {
    id: 'dune_part',
    fr: "d'une part… d'autre part",
    uk: 'з одного боку… з іншого',
    ipa: 'dyn paʁ… dotʁ paʁ',
    pos: 'phrase',
  },
  {
    id: 'en_conclusion',
    fr: 'en conclusion',
    uk: 'на завершення',
    ipa: 'ɑ̃ kɔ̃.kly.zjɔ̃',
    pos: 'adv',
  },
  { id: 'bref', fr: 'bref', uk: 'коротше кажучи', ipa: 'bʁɛf', pos: 'adv' },
  { id: 'lopinion', fr: "l'opinion", uk: 'думка, погляд', ipa: 'lɔ.pi.njɔ̃', pos: 'n', gender: 'f' },
  {
    id: 'largument',
    fr: "l'argument",
    uk: 'аргумент, доказ',
    ipa: 'laʁ.ɡy.mɑ̃',
    pos: 'n',
    gender: 'm',
  },
  {
    id: 'le_debat',
    fr: 'le débat',
    uk: 'дискусія, дебати',
    ipa: 'lə de.ba',
    pos: 'n',
    gender: 'm',
  },
  {
    id: 'le_point_de_vue',
    fr: 'le point de vue',
    uk: 'точка зору',
    ipa: 'lə pwɛ̃ də vy',
    pos: 'n',
    gender: 'm',
  },
  {
    id: 'regretter',
    fr: 'regretter',
    uk: 'шкодувати, жалкувати',
    ipa: 'ʁə.ɡʁe.te',
    pos: 'v',
    note: 'Після «je regrette que» — subjonctif: «Je regrette qu’il soit parti».',
    example: {
      fr: 'Je regrette de ne pas vous avoir écrit plus tôt.',
      uk: 'Шкодую, що не написав вам раніше.',
    },
  },
  {
    id: 's_etonner',
    fr: "s'étonner",
    uk: 'дивуватися',
    ipa: 'se.tɔ.ne',
    pos: 'v',
    note: 'Емоція → subjonctif: «Je m’étonne qu’il ne soit pas là».',
  },
])

/* ------------------------------------------------------------------ *
 * 10. Новини та суспільство (A2→B1)
 * ------------------------------------------------------------------ */
const news = pack('B1', 'news', [
  { id: 'la_presse', fr: 'la presse', uk: 'преса', ipa: 'la pʁɛs', pos: 'n', gender: 'f' },
  {
    id: 'lactualite',
    fr: "l'actualité",
    uk: 'новини, поточні події',
    ipa: 'lak.tɥa.li.te',
    pos: 'n',
    gender: 'f',
  },
  {
    id: 'larticle',
    fr: "l'article",
    uk: 'стаття; артикль',
    ipa: 'laʁ.tikl',
    pos: 'n',
    gender: 'm',
    note: 'Те саме слово, що й граматичний «артикль» — розрізняє контекст.',
  },
  {
    id: 'lemission',
    fr: "l'émission",
    uk: 'передача (теле-, радіо-)',
    ipa: 'le.mi.sjɔ̃',
    pos: 'n',
    gender: 'f',
  },
  { id: 'la_chaine', fr: 'la chaîne', uk: 'канал; ланцюг', ipa: 'la ʃɛn', pos: 'n', gender: 'f' },
  {
    id: 'le_reportage',
    fr: 'le reportage',
    uk: 'репортаж',
    ipa: 'lə ʁə.pɔʁ.taʒ',
    pos: 'n',
    gender: 'm',
  },
  {
    id: 'lenquete',
    fr: "l'enquête",
    uk: 'розслідування; опитування',
    ipa: 'lɑ̃.kɛt',
    pos: 'n',
    gender: 'f',
  },
  { id: 'le_sondage', fr: 'le sondage', uk: 'опитування', ipa: 'lə sɔ̃.daʒ', pos: 'n', gender: 'm' },
  {
    id: 'le_temoin',
    fr: 'le témoin',
    uk: 'свідок',
    ipa: 'lə te.mwɛ̃',
    pos: 'n',
    gender: 'm',
    note: 'Завжди чоловічого роду, навіть про жінку.',
  },
  {
    id: 'levenement',
    fr: "l'événement",
    uk: 'подія',
    ipa: 'le.vɛn.mɑ̃',
    pos: 'n',
    gender: 'm',
    note: '⚠️ Чоловічий рід, а наша «подія» — жіночий.',
  },
  {
    id: 'le_fait',
    fr: 'le fait',
    uk: 'факт',
    ipa: 'lə fɛ',
    pos: 'n',
    gender: 'm',
    note: '«En fait» — «насправді», один із найчастіших зворотів розмовної мови.',
  },
  {
    id: 'la_manifestation',
    fr: 'la manifestation',
    uk: 'демонстрація, мітинг',
    ipa: 'la ma.ni.fɛs.ta.sjɔ̃',
    pos: 'n',
    gender: 'f',
    note: 'Скорочено — «une manif».',
  },
  {
    id: 'la_greve',
    fr: 'la grève',
    uk: 'страйк',
    ipa: 'la ɡʁɛv',
    pos: 'n',
    gender: 'f',
    note: '⚠️ Жіночий рід, а наш «страйк» — чоловічий. «Faire grève» — страйкувати.',
  },
  { id: 'la_crise', fr: 'la crise', uk: 'криза', ipa: 'la kʁiz', pos: 'n', gender: 'f' },
  { id: 'le_chomage', fr: 'le chômage', uk: 'безробіття', ipa: 'lə ʃo.maʒ', pos: 'n', gender: 'm' },
  {
    id: 'la_pauvrete',
    fr: 'la pauvreté',
    uk: 'бідність',
    ipa: 'la po.vʁə.te',
    pos: 'n',
    gender: 'f',
  },
  {
    id: 'linegalite',
    fr: "l'inégalité",
    uk: 'нерівність',
    ipa: 'li.ne.ɡa.li.te',
    pos: 'n',
    gender: 'f',
  },
  {
    id: 'la_democratie',
    fr: 'la démocratie',
    uk: 'демократія',
    ipa: 'la de.mɔ.kʁa.si',
    pos: 'n',
    gender: 'f',
    note: 'Читається [-сі], хоч пишеться -tie.',
  },
  {
    id: 'la_pollution',
    fr: 'la pollution',
    uk: 'забруднення',
    ipa: 'la pɔ.ly.sjɔ̃',
    pos: 'n',
    gender: 'f',
  },
  {
    id: 'le_rechauffement',
    fr: 'le réchauffement climatique',
    uk: 'глобальне потепління',
    ipa: 'lə ʁe.ʃof.mɑ̃ kli.ma.tik',
    pos: 'n',
    gender: 'm',
  },
  {
    id: 'le_dechet',
    fr: 'le déchet',
    uk: 'відходи, сміття',
    ipa: 'lə de.ʃɛ',
    pos: 'n',
    gender: 'm',
  },
  {
    id: 'le_recyclage',
    fr: 'le recyclage',
    uk: 'переробка, сортування',
    ipa: 'lə ʁə.si.klaʒ',
    pos: 'n',
    gender: 'm',
  },
  {
    id: 'la_responsabilite',
    fr: 'la responsabilité',
    uk: 'відповідальність',
    ipa: 'la ʁɛs.pɔ̃.sa.bi.li.te',
    pos: 'n',
    gender: 'f',
  },
])

/* ------------------------------------------------------------------ *
 * 11. Регістр і жива мова (B1→B2)
 * ------------------------------------------------------------------ */
const register = pack('B2', 'register', [
  {
    id: 'le_langage',
    fr: 'le langage',
    uk: 'мовлення, манера говорити',
    ipa: 'lə lɑ̃.ɡaʒ',
    pos: 'n',
    gender: 'm',
    note: 'langage — як людина говорить; langue — сама мова (українська, французька).',
  },
  {
    id: 'familier',
    fr: 'familier / familière',
    uk: 'розмовний, неформальний',
    ipa: 'fa.mi.lje',
    pos: 'adj',
  },
  {
    id: 'soutenu',
    fr: 'soutenu / soutenue',
    uk: 'високий, книжний (про стиль)',
    ipa: 'sut.ny',
    pos: 'adj',
  },
  {
    id: 'courant',
    fr: 'courant / courante',
    uk: 'звичайний, повсякденний; вільний (про мову)',
    ipa: 'ku.ʁɑ̃',
    pos: 'adj',
    note: '«Parler couramment» — вільно володіти мовою.',
  },
  {
    id: 'le_boulot',
    fr: 'le boulot',
    uk: 'робота (розм.)',
    ipa: 'lə bu.lo',
    pos: 'n',
    gender: 'm',
    note: 'Розмовний відповідник до «le travail». У листі чи на співбесіді — не вживай.',
  },
  { id: 'bosser', fr: 'bosser', uk: 'працювати, гарувати (розм.)', ipa: 'bɔ.se', pos: 'v' },
  {
    id: 'bouffer',
    fr: 'bouffer',
    uk: 'жерти, їсти (розм.)',
    ipa: 'bu.fe',
    pos: 'v',
    note: 'Грубувате. Нейтрально — manger.',
  },
  {
    id: 'le_truc',
    fr: 'le truc',
    uk: 'штука, річ (розм.)',
    ipa: 'lə tʁyk',
    pos: 'n',
    gender: 'm',
    note: 'Універсальна заміна будь-якого слова, яке забув. Дуже частотне в мовленні.',
  },
  { id: 'le_mec', fr: 'le mec', uk: 'хлопець, тип (розм.)', ipa: 'lə mɛk', pos: 'n', gender: 'm' },
  {
    id: 'le_pote',
    fr: 'le pote',
    uk: 'друзяка, кореш (розм.)',
    ipa: 'lə pɔt',
    pos: 'n',
    gender: 'm',
  },
  {
    id: 'ouais',
    fr: 'ouais',
    uk: 'ага, ну так (розм.)',
    ipa: 'wɛ',
    pos: 'adv',
    note: 'Розмовна форма «oui». У формальній ситуації звучить недбало.',
  },
  {
    id: 'vachement',
    fr: 'vachement',
    uk: 'дуже, страшенно (розм.)',
    ipa: 'vaʃ.mɑ̃',
    pos: 'adv',
    note: 'Дослівно «по-коров’ячому». Розмовний підсилювач замість «très».',
  },
  {
    id: 'du_coup',
    fr: 'du coup',
    uk: 'отже, і тому (розм.)',
    ipa: 'dy ku',
    pos: 'adv',
    note: 'Заповнювач-паразит сучасної розмовної мови — почуєш у кожній другій репліці.',
  },
  { id: 'carrement', fr: 'carrément', uk: 'прямо, цілком, ще й як', ipa: 'ka.ʁe.mɑ̃', pos: 'adv' },
  { id: 'franchement', fr: 'franchement', uk: 'відверто кажучи', ipa: 'fʁɑ̃ʃ.mɑ̃', pos: 'adv' },
  { id: 'en_gros', fr: 'en gros', uk: 'загалом, грубо кажучи', ipa: 'ɑ̃ ɡʁo', pos: 'adv' },
  { id: 'quasiment', fr: 'quasiment', uk: 'майже', ipa: 'ka.zi.mɑ̃', pos: 'adv' },
  {
    id: 'raler',
    fr: 'râler',
    uk: 'бурчати, нарікати',
    ipa: 'ʁɑ.le',
    pos: 'v',
    note: 'Улюблене заняття французів — і вони самі про це жартують.',
  },
  {
    id: 'se_debrouiller',
    fr: 'se débrouiller',
    uk: 'давати раду, викручуватися',
    ipa: 'sə de.bʁu.je',
    pos: 'v',
    note: '«Je me débrouille en français» — «я якось даю раду французькою».',
  },
  { id: 'a_vrai_dire', fr: 'à vrai dire', uk: 'правду кажучи', ipa: 'a vʁɛ diʁ', pos: 'phrase' },
  {
    id: 'en_quelque_sorte',
    fr: 'en quelque sorte',
    uk: 'певною мірою, так би мовити',
    ipa: 'ɑ̃ kɛl.kə sɔʁt',
    pos: 'phrase',
  },
  { id: 'plus_ou_moins', fr: 'plus ou moins', uk: 'більш-менш', ipa: 'ply.z‿u mwɛ̃', pos: 'phrase' },
  {
    id: 'voire',
    fr: 'voire',
    uk: 'ба навіть',
    ipa: 'vwaʁ',
    pos: 'adv',
    note: '⚠️ Не плутай з «voir» (бачити) — пишеться з -e і означає «ба навіть».',
  },
])

/* ------------------------------------------------------------------ *
 * 12. Складні зв’язки та письмо (B1→B2)
 * ------------------------------------------------------------------ */
const connect = pack('B2', 'connect', [
  { id: 'neanmoins', fr: 'néanmoins', uk: 'проте, а втім', ipa: 'ne.ɑ̃.mwɛ̃', pos: 'adv' },
  { id: 'toutefois', fr: 'toutefois', uk: 'однак, утім', ipa: 'tut.fwa', pos: 'adv' },
  {
    id: 'par_consequent',
    fr: 'par conséquent',
    uk: 'отже, відповідно',
    ipa: 'paʁ kɔ̃.se.kɑ̃',
    pos: 'adv',
  },
  {
    id: 'certes',
    fr: 'certes',
    uk: 'звісно, безперечно (з поступкою)',
    ipa: 'sɛʁt',
    pos: 'adv',
    note: 'Класична пара для есе: «Certes…, mais…» — «Звісно…, проте…».',
  },
  {
    id: 'or_conj',
    fr: 'or',
    uk: 'а проте, тим часом',
    ipa: 'ɔʁ',
    pos: 'conj',
    note: 'Книжне. Вводить факт, що змінює хід міркування.',
  },
  {
    id: 'etant_donne',
    fr: 'étant donné que',
    uk: 'зважаючи на те, що',
    ipa: 'e.tɑ̃ dɔ.ne kə',
    pos: 'conj',
  },
  { id: 'du_fait_que', fr: 'du fait que', uk: 'через те, що', ipa: 'dy fɛ kə', pos: 'conj' },
  {
    id: 'de_sorte_que',
    fr: 'de sorte que',
    uk: 'так що, унаслідок чого',
    ipa: 'də sɔʁt kə',
    pos: 'conj',
  },
  {
    id: 'quoique',
    fr: 'quoique',
    uk: 'хоча',
    ipa: 'kwak',
    pos: 'conj',
    note: 'Книжний синонім до «bien que», теж вимагає subjonctif. Не плутай із «quoi que» (хоч би що).',
  },
  {
    id: 'avoir_beau',
    fr: 'avoir beau',
    uk: 'хоч скільки, дарма що',
    ipa: 'a.vwaʁ bo',
    pos: 'phrase',
    note: '⚠️ Конструкція без прямого відповідника: «J’ai beau essayer, ça ne marche pas» — «Хоч скільки я намагаюся, не працює».',
  },
  { id: 'quel_que_soit', fr: 'quel que soit', uk: 'хоч би який', ipa: 'kɛl kə swa', pos: 'phrase' },
  {
    id: 'dautant_plus',
    fr: "d'autant plus que",
    uk: 'тим більше що',
    ipa: 'do.tɑ̃ ply kə',
    pos: 'conj',
  },
  {
    id: 'lenjeu',
    fr: "l'enjeu",
    uk: 'ставка, ключове питання',
    ipa: 'lɑ̃.ʒø',
    pos: 'n',
    gender: 'm',
  },
  { id: 'le_defi', fr: 'le défi', uk: 'виклик', ipa: 'lə de.fi', pos: 'n', gender: 'm' },
  {
    id: 'le_constat',
    fr: 'le constat',
    uk: 'констатація, висновок',
    ipa: 'lə kɔ̃s.ta',
    pos: 'n',
    gender: 'm',
  },
  {
    id: 'le_bilan',
    fr: 'le bilan',
    uk: 'підсумок, баланс',
    ipa: 'lə bi.lɑ̃',
    pos: 'n',
    gender: 'm',
  },
  {
    id: 'le_cadre',
    fr: 'le cadre',
    uk: 'рамки, контекст; керівник',
    ipa: 'lə kadʁ',
    pos: 'n',
    gender: 'm',
    note: '«Dans le cadre de» — «у рамках чогось», дуже частий канцелярський зворот.',
  },
  {
    id: 'le_domaine',
    fr: 'le domaine',
    uk: 'сфера, галузь',
    ipa: 'lə dɔ.mɛn',
    pos: 'n',
    gender: 'm',
  },
  {
    id: 'la_demarche',
    fr: 'la démarche',
    uk: 'підхід, крок, процедура',
    ipa: 'la de.maʁʃ',
    pos: 'n',
    gender: 'f',
  },
  {
    id: 'la_croissance',
    fr: 'la croissance',
    uk: 'зростання',
    ipa: 'la kʁwa.sɑ̃s',
    pos: 'n',
    gender: 'f',
  },
  {
    id: 'laugmentation',
    fr: "l'augmentation",
    uk: 'збільшення, підвищення',
    ipa: 'loɡ.mɑ̃.ta.sjɔ̃',
    pos: 'n',
    gender: 'f',
  },
  {
    id: 'la_diminution',
    fr: 'la diminution',
    uk: 'зменшення',
    ipa: 'la di.mi.ny.sjɔ̃',
    pos: 'n',
    gender: 'f',
  },
  {
    id: 'la_reussite',
    fr: 'la réussite',
    uk: 'успіх, досягнення',
    ipa: 'la ʁe.y.sit',
    pos: 'n',
    gender: 'f',
  },
  {
    id: 'la_mise_en_place',
    fr: 'la mise en place',
    uk: 'запровадження, налагодження',
    ipa: 'la mi.z‿ɑ̃ plas',
    pos: 'n',
    gender: 'f',
  },
  {
    id: 'la_prise_de_conscience',
    fr: 'la prise de conscience',
    uk: 'усвідомлення',
    ipa: 'la pʁiz də kɔ̃.sjɑ̃s',
    pos: 'n',
    gender: 'f',
  },
])

/* ------------------------------------------------------------------ *
 * 13. Ідіоми та хибні друзі (B1→B2)
 * ------------------------------------------------------------------ */
const idioms = pack('B2', 'idioms', [
  {
    id: 'avoir_le_cafard',
    fr: 'avoir le cafard',
    uk: 'сумувати, бути в депресії',
    ipa: 'a.vwaʁ lə ka.faʁ',
    pos: 'phrase',
    note: 'Дослівно «мати таргана».',
  },
  {
    id: 'couter_les_yeux',
    fr: 'coûter les yeux de la tête',
    uk: 'коштувати шалених грошей',
    ipa: 'ku.te le.z‿jø də la tɛt',
    pos: 'phrase',
    note: 'Дослівно «коштувати очей з голови».',
  },
  {
    id: 'poser_un_lapin',
    fr: 'poser un lapin',
    uk: 'не прийти на зустріч, «продинамити»',
    ipa: 'po.ze œ̃ la.pɛ̃',
    pos: 'phrase',
    note: 'Дослівно «покласти кролика».',
  },
  {
    id: 'tomber_dans_les_pommes',
    fr: 'tomber dans les pommes',
    uk: 'знепритомніти',
    ipa: 'tɔ̃.be dɑ̃ le pɔm',
    pos: 'phrase',
    note: 'Дослівно «впасти в яблука».',
  },
  {
    id: 'avoir_du_pain',
    fr: 'avoir du pain sur la planche',
    uk: 'мати багато роботи',
    ipa: 'a.vwaʁ dy pɛ̃ syʁ la plɑ̃ʃ',
    pos: 'phrase',
  },
  {
    id: 'mettre_les_pieds',
    fr: 'mettre les pieds dans le plat',
    uk: 'бовкнути зайве, влізти не туди',
    ipa: 'mɛtʁ le pje dɑ̃ lə pla',
    pos: 'phrase',
  },
  {
    id: 'faire_la_tete',
    fr: 'faire la tête',
    uk: 'дутися, ображатися',
    ipa: 'fɛʁ la tɛt',
    pos: 'phrase',
  },
  {
    id: 'avoir_la_peche',
    fr: 'avoir la pêche',
    uk: 'бути бадьорим, у формі',
    ipa: 'a.vwaʁ la pɛʃ',
    pos: 'phrase',
  },
  {
    id: 'pas_dans_son_assiette',
    fr: 'ne pas être dans son assiette',
    uk: 'почуватися недобре',
    ipa: 'nə pa.z‿ɛtʁ dɑ̃ sɔ.n‿a.sjɛt',
    pos: 'phrase',
  },
  {
    id: 'valoir_le_coup',
    fr: 'valoir le coup',
    uk: 'бути вартим того',
    ipa: 'va.lwaʁ lə ku',
    pos: 'phrase',
  },
  {
    id: 'etre_a_laise',
    fr: "être à l'aise",
    uk: 'почуватися вільно, комфортно',
    ipa: 'ɛtʁ a lɛz',
    pos: 'phrase',
  },
  {
    id: 'casser_les_pieds',
    fr: 'casser les pieds à quelqu’un',
    uk: 'набридати комусь',
    ipa: 'kɑ.se le pje',
    pos: 'phrase',
  },
  // --- хибні друзі: те, що звучить знайомо, але означає інше ---
  {
    id: 'eventuellement',
    fr: 'éventuellement',
    uk: 'можливо, за потреби',
    ipa: 'e.vɑ̃.tɥɛl.mɑ̃',
    pos: 'adv',
    note: '⚠️ Хибний друг: НЕ «врешті-решт». Означає «можливо».',
  },
  {
    id: 'sensible',
    fr: 'sensible',
    uk: 'чутливий; відчутний',
    ipa: 'sɑ̃.sibl',
    pos: 'adj',
    note: '⚠️ Хибний друг: не «розсудливий». «Розумний» — raisonnable.',
  },
  {
    id: 'la_librairie',
    fr: 'la librairie',
    uk: 'книгарня',
    ipa: 'la li.bʁɛ.ʁi',
    pos: 'n',
    gender: 'f',
    note: '⚠️ Хибний друг: це книгарня, а бібліотека — «la bibliothèque».',
  },
  {
    id: 'la_location',
    fr: 'la location',
    uk: 'оренда',
    ipa: 'la lɔ.ka.sjɔ̃',
    pos: 'n',
    gender: 'f',
    note: '⚠️ Хибний друг: не «локація». Місце — «le lieu» або «l’endroit».',
  },
  {
    id: 'assister',
    fr: 'assister à',
    uk: 'бути присутнім на',
    ipa: 'a.sis.te a',
    pos: 'v',
    note: '⚠️ Хибний друг: «assister à un cours» — бути на занятті, а не асистувати.',
  },
  {
    id: 'ignorer',
    fr: 'ignorer',
    uk: 'не знати',
    ipa: 'i.ɲɔ.ʁe',
    pos: 'v',
    note: '⚠️ Хибний друг: основне значення — «не знати», а не «ігнорувати».',
  },
  {
    id: 'pretendre',
    fr: 'prétendre',
    uk: 'стверджувати',
    ipa: 'pʁe.tɑ̃dʁ',
    pos: 'v',
    note: '⚠️ Хибний друг: не «претендувати». Стверджувати щось (часто сумнівне).',
  },
  {
    id: 'la_journee',
    fr: 'la journée',
    uk: 'день (як проміжок часу)',
    ipa: 'la ʒuʁ.ne',
    pos: 'n',
    gender: 'f',
    note: 'jour — день як одиниця лічби; journée — день як тривалість. «Bonne journée !»',
  },
])

/** Words authored for the course, grouped by lesson theme. */
const thematic: Word[] = [
  ...greetings,
  ...identity,
  ...numbers,
  ...genderNouns,
  ...family,
  ...daily,
  ...food,
  ...city,
  ...opinion,
  ...news,
  ...register,
  ...connect,
  ...idioms,
]

/**
 * Compare two entries as the same lexical item: "l'ami / l'amie" and
 * "un ami / une amie" are one word, not two dictionary rows.
 *
 * The part of speech is part of the key on purpose: `le français` (the
 * language) and `français / française` (the adjective) are different entries
 * that happen to share a head form.
 */
function lexicalKey(w: Pick<Word, 'fr' | 'pos'>) {
  const ARTICLES = new Set(['le', 'la', 'les', "l'", 'un', 'une', 'des', 'du'])
  const parts = w.fr
    .toLowerCase()
    .replace(/[’]/g, "'")
    .split('/')
    .map((p) => p.trim())
    .filter(Boolean)

  // "le / la journaliste" — skip the bare article and key on the noun itself.
  for (const part of parts) {
    if (ARTICLES.has(part)) continue
    const head = part.replace(/^(le |la |les |l'|un |une |des |du |de la |de l')/, '').trim()
    if (head) return `${head}|${w.pos ?? ''}`
  }

  // Entries that are nothing but articles ("un / une / des") key on themselves.
  return `${w.fr.toLowerCase()}|${w.pos ?? ''}`
}

/**
 * Merge the frequency core into the thematic list.
 *
 * A course word that also appears in the top 1000 keeps its richer authored
 * entry (example sentence, lesson tag) and simply gains a `rank`; only genuinely
 * new words are appended. That way the two lists can be maintained independently
 * without ever producing duplicate dictionary rows.
 */
function mergeVocabulary(): Word[] {
  const merged: Word[] = []
  const seenId = new Map<string, Word>()
  const seenKey = new Map<string, Word>()

  const remember = (w: Word) => {
    merged.push(w)
    seenId.set(w.id, w)
    seenKey.set(lexicalKey(w), w)
  }

  for (const w of thematic) remember(w)

  for (const core of CORE_WORDS) {
    const existing = seenId.get(core.id) ?? seenKey.get(lexicalKey(core))
    if (existing) {
      // The thematic entry wins on content, but inherits the frequency rank.
      existing.rank ??= core.rank
      if (!existing.tags?.includes('core')) existing.tags = [...(existing.tags ?? []), 'core']
      continue
    }
    remember(core)
  }

  return merged
}

export const WORDS: Word[] = mergeVocabulary()

const byId = new Map(WORDS.map((w) => [w.id, w]))

export function getWord(id: string): Word | undefined {
  return byId.get(id)
}

export function getWords(ids: readonly string[]): Word[] {
  return ids.map((id) => byId.get(id)).filter((w): w is Word => Boolean(w))
}

export function wordsByTag(tag: string): Word[] {
  return WORDS.filter((w) => w.tags?.includes(tag))
}
